### ISSUE TITLE
Compiler warning (unused variable) in /platforms/esp/32/clockless_rmt_esp32.h

### ISSUE THREAD

**Issue by bdaroz** [FastLED/FastLED#1067]
From FastLED 3.3.3 on ESP32.

Compiler Warning (truncated and redacted):

```
Users/xxxxxxx/Documents/Arduino/libraries/FastLED/platforms/esp/32/clockless_rmt_esp32.h:511:22: warning: unused variable 't1' [-Wunused-variable]
             uint32_t t1 = __clock_cycles();
```

**Comment by kriegsman** [comment]
Thank you for the report, @bdaroz.  
@samguyer could you take a look and see if this is easy to fix?

**Comment by samguyer** [comment]
I'll take a look. But I've also got some bigger changes to push, so maybe it's better to wait.

**Comment by Account-Git** [comment]
I just wanted to bump this issue because it has been over 3 months now and it is still giving compiler warnings.

**Comment by samguyer** [comment]
@Account-Git 
I don't think this warning exists in the current head.
