### ISSUE TITLE
apa102 end frame adjustments

### ISSUE THREAD

**Issue by focalintent** [FastLED/FastLED#107]
See http://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled - apa102 needs to send an end frame of n/2 led 1 bits.

**Comment by pup05** [comment]
Could this be related to an issue I'm seeing with APA102, FastLED 3.1, Arduino 1.0.6, Teensyduino 1.20, Windows 8.1?  I get 'scrambled' output on the FastLED 3.1 branch, but it looks correct on master.  I'm on my mobile right now, but can post code shortly.

**Comment by focalintent** [comment]
What hardware are you running with?  And the missing end frame bits should only cause an issue with leds towards the end of your chain.  The more important question is how many leds are you running?  FastLED3.1 is currently willing to push driving the APA102's up to 24Mhz (I have a board here that can support that) - odds are you might need to scale back the data rate.

```
LEDS.addLeds<APA102,RGB,DATA_RATE_MHZ(12)>(leds, NUM_LEDS);
```

**Comment by pup05** [comment]
Ah sorry, Teensy 3.1, 72 LEDs.

**Comment by pup05** [comment]
#define LED_PIN     3
    #define CLOCK_PIN   2
    #define COLOR_ORDER GRB
    #define CHIPSET     APA102
    #define NUM_LEDS    63
    ...
    FastLED.addLeds<CHIPSET, LED_PIN, CLOCK_PIN, BGR>(leds, NUM_LEDS);

Thanks in advance for the assistance, by the way.  :)

**Comment by focalintent** [comment]
Add the data rate change that I suggested:

```
FastLED.addLeds<CHIPSET, LED_PIN, CLOCK_PIN, BGR, DATA_RATE_MHZ(12)>(leds, NUM_LEDS);
```

**Comment by pup05** [comment]
Sorry, that did it, thanks!

**Comment by jar10623** [comment]
i have a Problem with fastLED since i changed from Arduino nanoV3 (all OK) to 
https://github.com/JChristensen/mini1284

i build two to test but this is only a Problem with fastLED!

with https://github.com/cpldcpu/light_ws2812 is no problem, Timing ist well


see the Data Timing with m1284p & fastLED
http://www.mikrocontroller.net/attachment/244099/m1284p_timing.jpg
![m1284p_timing](https://cloud.githubusercontent.com/assets/10545958/5756687/77961f34-9cb2-11e4-8e83-df0d60b8cc82.jpg)


with 33µs (m1284p) für one LED the ws2812b dosn't work, the 30µs is from m328p

**Comment by focalintent** [comment]
Please open/track a separate issue. This has nothing to do with the apa102.  Also the mega1284 is not a tested/supported platform for FastLED.

**Comment by jar10623** [comment]
>Please open/track a separate issue.
? i don't understand

>This has nothing to do with the apa102
OK but  where can i told you?

>Also the mega1284 is not a tested/supported platform for FastLED
thats a good reason to do nothing OMG

sorry that i live......

**Comment by focalintent** [comment]
I mean go here: https://github.com/FastLED/FastLED/issues/new and enter a "new issue" - don't just comment on some other random issue.

I didn't say I was going to do nothing OMG.  I asked you to make a new issue so that I could track it separately from this one.  I was also explaining that the reason why it currently doesn't work on the mega1284 is because I have never tested it on the mega1284 - and there are different instruction and i/o timings on that chip than the mega328.

This issue is specifically for the APA102, and in fact, is about to be closed, as I've fixed the original issue referenced in here.

**Comment by focalintent** [comment]
(For example - https://github.com/FastLED/FastLED/issues/121 )
