### ISSUE TITLE
Multiple LED arrays, updating each array individually 

### ISSUE THREAD

**Issue by QuitButton** [FastLED/FastLED#1070]
I have two LED arrays, for example...

```
CRGB LEDs[NUM_LEDS];
CRGB COLONs[2];
FastLED.addLeds<WS2812B, DATA_PIN, GRB>(LEDs, NUM_LEDS); // clock display
FastLED.addLeds<WS2812B, COLON_PIN, GRB>(COLONs,2); // 2 leds for centre colon.
```

calling FastLED.show(); updates all leds, but I want to just update the 2 LEDs on in the COLON array. Is this possible? The Multiple-Controller-Examples only seem to show examples using the same number of leds per strip.

**Comment by 5chmidti** [comment]
I belive it's
```c++
FastLED[1].showLeds(/*optional brightness uint8_t*/);
```
to update your second strip.

**Comment by marmilicious** [comment]
@QuitButton  Check out the last section of this wiki page.  
https://github.com/FastLED/FastLED/wiki/Multiple-Controller-Examples
