### ISSUE TITLE
Using FastLED for LED wall

### ISSUE THREAD

**Issue by CNSNGopenSourceProjects** [FastLED/FastLED#1078]
I really enjoy the FastLED. I am running on ESP32 and I learned a lot about it.
Now I want to control a small Led Wall (20x20), but I was not able to read the LED-file from LedEdit.
Can anyone share the file format or recommend another LED editor with open animation file?

**Comment by marmilicious** [comment]
Hello @CNSNGopenSourceProjects 
We use github "issues" here mostly just for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: https://www.reddit.com/r/FastLED

If you post your question to the reddit group please include a link to LedEdit so others know what you are referring too, and if you can provide a link to the file you are having trouble with that might be useful too.
