### ISSUE TITLE
Add top-level Arduino.h import

### ISSUE THREAD

**Issue by BarakChamo** [FastLED/FastLED#1082]
Hi there,

I've been using FastLED for a while with an ESP32 using the Espressif Arduino framework and have bee trying to gut out some of the arduino stuff while transitioning to platform.io.

I noticed that when trying to compile code using `FastLED` in any environment other than Arduino, the library build fails with many missing imports. though other Arduino libraries are building just fine. Upon further investigation, it seems that simply adding a top-level `<Arduino.h>` import in `FastLED.h` solves that problem. The issue might be with how ESP-IDF compiles required libraries.

Either way, since FastLED is built to be used with Arduino, and seems to be perfectly functional if the `<Arduino.h>` core is available, it would be great if you could add that top-level import explicitely.
This follows the same pattern used by all other Arduino libraries, such as:
- https://github.com/arduino-libraries/Ethernet/blob/master/src/Ethernet.cpp#L21
- https://github.com/espressif/arduino-esp32/blob/master/libraries/Wire/src/Wire.cpp#L33
- https://github.com/espressif/arduino-esp32/blob/master/libraries/Update/src/Updater.cpp#L2

I appreciate that `FastLED` is built for Arduino environments, but since this simple fix solves the problem in `Arduino-as-component` setups and doesn't add any overhead when `Arduino.h` is already there, it seems like an easy win.

Thanks!

**Comment by zackees** [comment]
Not relying on Arduino is sacred and means we can go into the espressif component system and compile to wasm.
