### ISSUE TITLE
Random colors in Sk6812 Leds

### ISSUE THREAD

**Issue by parmarravi** [FastLED/FastLED#1086]
I have a 150 LEDs sk6812 led strip, I tried two lib Adafruit neopixel RGBW and fastLed Demo examples. The adafruit lib works like a charm and it verifies that my LEDs are working properly.

While In the Demo example even after mentioning the type of led the color on the strip is off and it always ends up in the random pattern. It also not initialize all LEDs properly.

Tried the same code for neopixel to cross-verify all connections and MCU itself and it is working properly.

Is there a bug in lib for support of sk6812 led? Current lib use in the program is the latest one 3.3.3

**Comment by leonbohmann** [comment]
Have a look at this:
https://github.com/FastLED/FastLED/issues/1068
