### ISSUE TITLE
FastLED not working on Yun

### ISSUE THREAD

**Issue by Piornet** [FastLED/FastLED#109]
Hi!

I'm having a problem with getting the code to work properly on the Yun.  I've deleted the original folder from Arduino/Libraries and installed the latest FastLED (3.0.3), but still no luck.  The lights are all just a dim red.  Using the "blink" sample code I'm able to get the LEDs to slightly flash - but they're still red instead of white.  The same code works properly on other Arduinos I have lying around (a mega, an Uno), just not on the Yun.  Any suggestions?

Thanks!

**Comment by focalintent** [comment]
Closing for lack of any response to questions.
