### ISSUE TITLE
FastLED3.1 branch is broken with WS2811 strips

### ISSUE THREAD

**Issue by liftoff** [FastLED/FastLED#111]
I have no idea what's causing it but when I run the ColorPalette example with the FastLED3.1 branch using my WS2811 strip all I get are various colors in the spectrum between green and light blue.  I uploaded a video demonstrating what it looks like here:

http://riskable.com/files/FastLED3.1_ws2811_broken_colors.mp4

Edit:  This is using an Arduino Pro Micro.  Connected to pin 10 (probably doesn't make a difference but you never know).

**Comment by focalintent** [comment]
Pro micro working here w/WS2811 and arduino 1.6.1.

**Comment by rtimer** [comment]
"#define NO_CORRECTION 1" did it on a Adafruit Trinket 3.3V on Windows 8.1 with Arduino 1.6.3 and FastLED 3.0.3. Without it even the FastLED blink example did only show plain white when connecting to the signal Pin, e.g. 0. Thanks to you for the analysis (and the great lib, for sure)!
