### ISSUE TITLE
FastLED.Show() has a negative impact on digitalRead(GPIO_NUM_0)

### ISSUE THREAD

**Issue by alf45tar** [FastLED/FastLED#1126]
Using the latest `master` branch after a FastLED.show() call the next calls to digitalRead(0) return always LOW.
The following code prints the hash sign indefinitively even if the BOOT button (GPIO0) is not pressed.

````
#include <Arduino.h>
#include "FastLED.h"

CRGB fastleds[20];

void setup()
{
  Serial.begin(115200);

  FastLED.addLeds<NEOPIXEL, 5>(fastleds, 20);
  for (byte l = 0; l < 20; l++)
    fastleds[l] = CRGB::Red;
  FastLED.show();

  pinMode(0, INPUT_PULLUP);
}


void loop()
{
  if (digitalRead(0) == LOW) {
      Serial.print("#");
    }
}
````

The above code works as expected (print hash sign only when BOOT button is pressed) in version 3.3.3.

**Comment by Jueff** [comment]
if it's on an ESP32 this workaround may help 
https://github.com/FastLED/FastLED/issues/1130#issuecomment-737310821

**Comment by samguyer** [comment]
@alf45tar This problem should be fixed in the latest release. Let me know if you're still having problems.

**Comment by alf45tar** [comment]
I confirm it is ok now.
Thanks
