### ISSUE TITLE
Ambibox WS2812B Flicker

### ISSUE THREAD

**Issue by shaunb1980** [FastLED/FastLED#113]
Hello, this is my first attempt at adalight and I experience flickering after about 10min of use and have to change the COM port then change back.

I read on the main page here not to use IDE 1.5.7 or higher and I am using the latest BETA version from Arduino site.

Could this be related to the flickering ?

This is the sketch I am using and have not change anything.

https://gist.github.com/jamesabruce/09d79a56d270ed37870c

**Comment by emcniece** [comment]
I'm seeing this same issue, and just solved it by hard-connecting each strip. Instead of using header female/male pins/sockets, I had to [B-connector](http://www.parts-express.com/dolphin-dc-100p-super-b-crimp-connector-100-pcs--095-350) each line.

For reference, I scoped forms every 12 LEDs and adjusted the supply for 5.1V at each sink. Very stable.

**Comment by ehq** [comment]
@shaunb1980 were you able to solve the problem? I'm looking to implement a setup similar to yours, as I'm thinking of getting a Teensy 3.1 with the 144-leds-per-meter Adafruits leds strip.

If it's working for you, could you paste the code you're using to making it work?

**Comment by focalintent** [comment]
I believe this has turned into a hardware and/or ambilight problem, closing the issue for FastLED.

**Comment by hristo-atanasov** [comment]
For everyone that is struggling with fixing the ambilight random flickering and the ambilight is made with ws2812b + Raspberry Pi + Arduino there is a few things that each separate one (or any combination of them) can fix the issue. I was struggling few months too. Tried every suggestion on the web (software and hardware), missing one thing that wasn't suggested anywhere. It was not included in any tutorial too. The fix in my case was connecting one of the ground pins of the Raspberry to the grounds of the Arduino and the strip (all of them grounded in the power supply V-). There wasn't any  tutorial that was saying that they (3 of them) must have common ground. All suggestions were that I have to have common grounds on the arduino and the LED strip.

So, this is short list of things that may help:
- putting additional capacitor 1800uF 6V+ (and more) on the power supply V+ and V-
- putting resistor 470 Ohm directly or as much closer as it can be placed on the first LED DI (Data In)   connector
- using short and thick wires to power the LED Strip to prevent voltage drop and supply enough amps for the LED Strip
- If the strip is longer (let say 150, 200 or 300 leds and more) power it on a few places along its length and even on the end. Measure the voltage in between 2 power connections to check if additional power connection is needed to fix the voltage drop.
- Calculate the Amps needed to feed the strip. Each LED consumes 60mA. When buying the power supply and choosing the right one for you, use this formula to calculate how much power in watts do you need: P(W) = I(A) × V(V). So lets say 300 LED multiplied by 60mA = 18 000mA = 18A. 18A multiplied by 5V = 90W - needed only for the strip! But hey, don't be scrumpy when buying power supply - buy 100W. And read the buyer comments under the product and make sure if it is good quality. You don't want to fire you house or damage electronics for hundred dollars, right?
- When testing the configuration is done and everything works amazing, don't forget to use good quality and more thicker cables. Avoid any use of solderless power, ground and data joints. It may lead to power and voltage drops, loose/no connection at all and we know that with the bigger power comes bigger responsibility :D .

**Comment by AmberElferink** [comment]
I had the exact same thing and fixed it. I have a long ledstrip (138 leds). With an arduino uno, the leds start to flicker randomly after led ~55-70 after a while (10, minutes or so). With the arduino nano, it flickers all the leds practically immediately. With an arduino mega, everything is fine. Depending on the length of your ledstrip, your arduino can or cannot handle it. More leds means larger packages, means you need a faster controller. Upgrade your arduino would be my tip. 
(Yes it's years later, but for anyone who comes across this, it may help).
