### ISSUE TITLE
ESP32 GPIO0 gets unuseable

### ISSUE THREAD

**Issue by Jueff** [FastLED/FastLED#1130]
I discovered an issue in the current trunk, that GPIO0 pin of ESP32 can't be used as output anymore, after calling FastLed.show the first time.

I found out that it must have something to do with
void ESP32RMTController::init()
...
        rmt_tx.gpio_num = gpio_num_t(0);  // The particular pin will be assigned later
....
If I change to e.g.  gpio_num_t(22) GPIO 0 can be used as output again.
Seems the pin is set to another kind of operation, but isn't reset to default  when assigning the correct pin.

**Comment by Jueff** [comment]
As a workaround I added 

`gpio_matrix_out(gpio_num_t(0), 0x100, false, false);`

in my code after the first FastLED.show call.

**Comment by samguyer** [comment]
@Jueff Thanks for the issue report! I should be able to fix that problem in a more permanent way.

**Comment by samguyer** [comment]
@Jueff I just pushed a fix for this issue, so I'm closing it. Thanks!

**Comment by Jueff** [comment]
Thanks for the quick fix!
