### ISSUE TITLE
BULTIN RMT Driver seems to have broken interrupt

### ISSUE THREAD

**Issue by fiskn** [FastLED/FastLED#1151]
https://github.com/FastLED/FastLED/blob/master/src/platforms/esp/32/clockless_rmt_esp32.cpp#L282

I believe the above section should have a if (!FASTLED_RMT_BUILTIN_DRIVER) around it. Until I tracked this down and excluded it, my code was hanging waiting on the semaphore which was never given as it appeared the interrupt callback was never called.

**Comment by zackees** [comment]
We have the new RMT5 driver so this problem should be fixed.
