### ISSUE TITLE
Adding ATtiny 1614 support

### ISSUE THREAD

**Issue by gmoney3553** [FastLED/FastLED#1173]
I've been experimenting with the ATtiny1614 chip and was hoping that it could get supported or someone could help guide me on how to add it myself. I'm trying to make a small pcb board with this chip to control some led strips. Any and all help is very appreciated! Thanks so much!

**Comment by domdfcoding** [comment]
I too would like to use FastLED on the more powerful chips in the ATtiny 1 and 2 series. It would make porting code from the 328p Arduinos much easier, as TinyNeoPixel doesn't have the same featureset. as FastLED.

**Comment by zackees** [comment]
Does `#FASTLED_FORCE_SOFTWARE_SPI` work?

**Comment by domdfcoding** [comment]
No unfortunately. The errors are all along the lines of `FastLED/src/platforms/avr/fastpin_avr.h:70:26: error: 'DDRB' was not declared in this scope`

As I understand it, on these newer chips it's not `DDRB` but `PORTB.DIR` etc. (apparently they can also be `PORTB_DIR` to avoid the `.`)

There's a table in the megaTinyCore wiki which shows the mapping, with some caveats: https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/Ref_DirectPortManipulation.md#equivalents-to-classic-avr-registers

-----

If I define the mapping in `fastpin_avr.h` like so it still won't build:

```C
#define DDRA PORTA_DIR
#define PINA PORTA_IN
#define DDRB PORTB_DIR
#define PINB PORTB_IN
```

```
FastLED/src/platforms/avr/fastpin_avr.h:74:42: error: invalid initialization of reference of type 'reg8_t {aka volatile unsigned char&}' from expression of type 'PORT_t {aka PORT_struct}'
```

(line 74 is what was line 70 before I added the `#define`s)

**Comment by brickstuff** [comment]
Adding a +1 to this request-- spent time this afternoon digging into the library files but could not make it work.  Seems it will take more than just adding some additional port definitions, so I'm in over my head.

**Comment by Sk8rSeth** [comment]
rehashing this support request to see if anyone has gotten this to compile. im trying to use it with an attiny1616 and getting all sorts of errors trying to compile the simple example

**Comment by Sojourneer** [comment]
I'm trying to use the Tiny824 and 1624, and not getting very far with porting as per the documentation.  I'd really like to try on this library on my goto MCUs.

**Comment by jvl88** [comment]
> rehashing this support request to see if anyone has gotten this to compile. im trying to use it with an attiny1616 and getting all sorts of errors trying to compile the simple example

@Sk8rSeth  I know it has been a year, but have you managed to make it work with ATTINY1616?

**Comment by zackees** [comment]
Master now has Attiny support.

Closing this but. Feel free to re-Open if it doesn't work.
