### ISSUE TITLE
[help needed (if possible)] White temperature in kelvin

### ISSUE THREAD

**Issue by sblantipodi** [FastLED/FastLED#1177]
Hi all,
is it possible to set the white temperature in fast led?

I mean, in kelvin, like 1000L, 6500K, 7500K, 10000K ecc...

using a WS2812B LED strip.

Thank you.

**Comment by marmilicious** [comment]
There's no direct way to enter a Kelvin value, but there are a bunch of preset color corrections some of which are Kevin based that you might be able to use.  See these pages:  

http://fastled.io/docs/3.1/group___color_enums.html  
http://fastled.io/docs/3.1/color_8h_source.html

And here's an example program that goes through all the presets.  
https://github.com/marmilicious/FastLED_examples/blob/master/color_temperature_demo.ino

We use github "issues" here mostly for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: https://www.reddit.com/r/FastLED

**Comment by sblantipodi** [comment]
thank you!!!
