### ISSUE TITLE
Fastled over lan

### ISSUE THREAD

**Issue by xjustbmw** [FastLED/FastLED#1215]
Possible to make this work on esp8266 over ip ?

I am using virtual usb port mapping (virtualhere software) throgh a raspberry pi at the moment that is connected to arduino and ambibox on pc

**Comment by samguyer** [comment]
@xjustbmw This question is probably for suitable for the Subreddit: https://www.reddit.com/r/FastLED/

**Comment by xjustbmw** [comment]
Thank you for all the help. Can be closed
