### ISSUE TITLE
How to control special ws2811 led? The sequence time is different from that of standard ws2811.

### ISSUE THREAD

**Issue by feipinxiang** [FastLED/FastLED#1219]
the seller gave me the wrong datasheet. the led ic is SM16703PB.After some testing I used ws2811 to drive correctly.

T | 码元周期 | 1200 | - | - | ns
-- | -- | -- | -- | -- | --
T0H | 0 码，高电平时间 | 200 | 300 | 400 | ns
T0L | 0 码，低电平时间 | 800 | 900 | - | ns
T1H | 1 码，高电平时间 | 800 | 900 | 1000 | ns
T1L | 1 码，低电平时间 | 200 | 300 | - | ns
Trst | Reset 码，低电平时间 | 200 | - | - | us

24bit data
G7……G0 R7……R0 B7……B0

12V， 5050RGB，3 leds per address, 60pixel/m. LED-Strip Use 12v32A DC power supply, use arduino uno. With a very simple code, the LED strip will not display the correct color. The result is like a random flashing rainbow.

```#define DATA_PIN     6
#define NUM_LEDS    60
#define LED_TYPE    WS2811
#define COLOR_ORDER GRB
CRGB leds[NUM_LEDS];

void setup() { 
  delay(3000);
  FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection( TypicalSMD5050 );
  FastLED.clear();
  FastLED.show();
}

void loop() {
  for(int i=0; i<NUM_LEDS; i++) {
    leds[i] = CRGB::Red;
  }
  FastLED.show();
  delay(1000);
}
```

**Comment by feipinxiang** [comment]
Do I need to connect 12v- and arduino gnd?

**Comment by feipinxiang** [comment]
It's ridiculous, the seller gave me the wrong datasheet.
The correct ic is SM16703PB, not ws2811.I can’t see the chip because it’s covered with soft plastic.

T0H	0.3us  ±100ns
T1H	0.9us  ±100ns
T0L	0.9us  -100ns
T1L	0.3us  -100ns
reset	200us

**Comment by marmilicious** [comment]
> Do I need to connect 12v- and arduino gnd?

Yes, a common ground connection between the LED strip and your controller is **always** required.

**Comment by feipinxiang** [comment]
> > Do I need to connect 12v- and arduino gnd?
> 
> Yes, a common ground connection between the LED strip and your controller is **always** required.

Yes，After some testing I used ws2811 to drive correctly. ic is SM16703PB，The seller says it is compatible with ws2811.
