### ISSUE TITLE
Is there any plan to support newer ESP32-S2, S3, C2, C3 chip?

### ISSUE THREAD

**Issue by sblantipodi** [FastLED/FastLED#1232]
As title.
ESP32-S2 is on the road, is there any plan to support those new ESP32 chip?

**Comment by samguyer** [comment]
@sblantipodi Thanks for submitting this issue. I have to catch up on some older issues, but I want to make sure we stay up to date with the latest ESP hardware. Do you have any interest in helping out with the effort?

**Comment by sblantipodi** [comment]
@samguyer I need to understand better how fastled works but definitely yes. Still see how that devices grow up, they are pretty unstable right now...

**Comment by thijstriemstra** [comment]
Do you have access to such a board @samguyer? I'm sure espressif would sent some over to you
