### ISSUE TITLE
http://fastled.io/ is down

### ISSUE THREAD

**Issue by gnbl** [FastLED/FastLED#1239]
I am looking for the documentation but cannot find it anywhere else.

**Comment by gnbl** [comment]
https://web.archive.org/web/20210417194724/http://fastled.io/ points to https://github.com/FastLED/FastLED/wiki/Overview

Please change the links (repo description, readme).

**Comment by gslandtreter** [comment]
Looks like a DNS issue.
I was able to access fastled.io by hardcoding its IP address into my hostfiles
https://spyse.com/target/domain/fastled.io
You can use this as a workaround and at your own risk.

**Comment by Tyzzics** [comment]
Dam, i kinda need it too, hope it comes back soon

**Comment by uberjay** [comment]
I'm attempting to wrangle the necessary DNS changes. With some luck, we may be back in a day or two. (Without luck, it may take longer.)

**Comment by kosigaga** [comment]
Should be closed? @uberjay
