### ISSUE TITLE
arduino rp2040 support

### ISSUE THREAD

**Issue by SiliCarbConverter** [FastLED/FastLED#1258]
could you please let us know if there is going to be support for the rp2040 nano from arduino
in the near future. i have a project that relies on it and being a complete idiot forgot to check on compatibility issues. i am using APA102 leds the only library option i have at the moment is APA102.h . thank you.

**Comment by ageppert** [comment]
A work around in the short-term is to use the Adafruit NeoPixel library which has been updated to support the rp2040 and pico with a PIO implementation: https://github.com/Bodmer/Adafruit_NeoPixel

**Comment by SiliCarbConverter** [comment]
Thanks i will take a look.

**Comment by danw182** [comment]
Thank you

**Comment by ATLTVHEAD** [comment]
Would also love support for the rp2040 chip!

**Comment by chucks13** [comment]
The neopixel library works great for driving led strips, but it would be nice to use the utility functions in FastLED for creating animations.  Is there a way to use the library for boards that are not supported, even if it means there are no output capabilities?

**Comment by nmaas87** [comment]
https://github.com/FastLED/FastLED/pull/1261

**Comment by zackees** [comment]
It's supported and there's a builder for it that's green.
