### ISSUE TITLE
FastLED won't upload  to UNO

### ISSUE THREAD

**Issue by Mihiripenna** [FastLED/FastLED#126]
the program complies but will not upload following error comes up

avrdude: stk500_getsync() not in sync: resp=0x30

tried few uno boards to make sure no faults with the boards.
need help please.
thanks

**Comment by focalintent** [comment]
This is likely a problem with the arduino software and/or your ftdi drivers, and nothing to do with the library.  I would make sure you had the latest version of the arduino software and drivers.  The only other thing I can recommend is posting your question in the arduino forums on the main arduino website.
