### ISSUE TITLE
Inverse Glitter

### ISSUE THREAD

**Issue by d333gs** [FastLED/FastLED#1262]
This is not an issue , but I dont know where to post a question!!??
I am trying to inverse the glitter process: Ie a colored field with pixels going black then re-lighting  

Any ideas?
Thanks

**Comment by d333gs** [comment]
OK found a fading function, Mark's I believe

**Comment by marmilicious** [comment]
@d333gs  For all general discussions, help, and how-to, please use the FastLED Reddit group here: https://www.reddit.com/r/FastLED
