### ISSUE TITLE
Issue Driving NeoPixels When Running on an AVR at 8 Mhz

### ISSUE THREAD

**Issue by thoughtentity** [FastLED/FastLED#127]
When FastLED v3.0.3 is used to drive NeoPixels on an ATmega328P at 8 MHz @ 5V the NeoPixels behave sporadically with only the first few pixels lighting up. The issue appears to be related to the speed the chip is running at as the same code works fine run at 16 MHz.

**Comment by bkolbe** [comment]
exactly same here

**Comment by HironoriAbe** [comment]
me, too.

**Comment by focalintent** [comment]
I don't have any 8Mhz avr setups here that can be easily tested with.  Please retest with the latest FastLED3.1 branch and arduino 1.6.1, and re-open this if there is still an issue.

**Comment by cloudwalking** [comment]
I ran the following test program on an Arduino Uno and an 8Mhz Adafruit Gemma. It runs as expected on the Uno, but shows only white at full brightness for all LEDs on the Gemma.

Tested branch FastLED3.1, Arduino 1.6.3; test program: https://gist.github.com/cloudwalking/e03dacd31df63449980d



 (@8ee392ace11da654a99d980abb94fc7a9d568157)

**Comment by focalintent** [comment]
Reopened, I'm going to have to get some 8mhz hardware I think, to try and track what is going on.

**Comment by NicoHood** [comment]
You can run it ad 16mhz and use:
#include <avr/power.h>

and put this into setup:
clock_prescale_set(clock_div_2),

**Comment by damonwitz** [comment]
I'm having the same problem with fire fx sketches.  Only white solid LED.  I'm very new at writing code, how do I tell the Adafruit 5v Trinket to run @ 16mhz?

**Comment by cloudwalking** [comment]
Do as NicoHood writes, above. You also need to set your board to Trinket 16Mhz instead of Trinket 8Mhz.

That said, setting my Gemma's clock to 16Mhz did not fix the problem.

**Comment by damonwitz** [comment]
Thanks, did anything work?  I have a Trinket Pro, maybe that will work better?

**Comment by SeanGau** [comment]
I got the same problem. Is there any solution now?

**Comment by damonwitz** [comment]
I got it to work by downloading Arduino v1.0.5. I had read another thread that mentioned FastLED 3.3 has some issues w Arduino later than 1.5.7

**Comment by focalintent** [comment]
Those issues were fixed for AVR a while ago on the FastLED 3.1 branch (I believe you are referring to 3.0.3 - there is no 3.3 version yet).

The reason for things not working at 8Mhz is still unknown and something that I need to spend some time digging into.

**Comment by cloudwalking** [comment]
I am eagerly awaiting your verdict re: 8Mhz. Thanks for taking a look.

On Mon, May 4, 2015 at 1:25 PM, Daniel Garcia <notifications@github.com>
wrote:

> Those issues were fixed for AVR a while ago on the FastLED 3.1 branch (I
> believe you are referring to 3.0.3 - there is no 3.3 version yet).
>
> The reason for things not working at 8Mhz is still unknown and something
> that I need to spend some time digging into.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastLED/FastLED/issues/127#issuecomment-98839783>.
>



-- 
reedmorse.com

**Comment by damonwitz** [comment]
I will try it out and post my results. I sent off the neopixels to a job and will have them back next week. Thanks for all the advice.

**Comment by liyanage** [comment]
For what it's worth, when running my board at 8MHz I initially also had problems with Adafruit's NeoPixel library. To make it work at 8MHz, I had to downgrade the speed to 400kHz using the library's NEO_KHZ400 option (instead of NEO_KHZ800).

**Comment by focalintent** [comment]
Bunch of fixes checked in for 8Mhz gemma/trinket on the 3.1 branch.

**Comment by cloudwalking** [comment]
You are a true hero.

**Comment by Diaoul** [comment]
I'm using FastLED on Arduino Pro Mini 3.3V 8MHz and this fails:

```c
#include <FastLED.h>

#define DATA_PIN  4
#define NUM_LEDS  60

CRGB leds[NUM_LEDS];

void setup() {
  FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);
}

void loop() {
  fill_solid(leds, NUM_LEDS, CRGB::White);
  FastLED.show();
}
```
Important things to note are:
* Works fine on Arduino Uno
* Works fine for less LEDs (NUM_LEDS < 50)
* Works fine for other colors, only `CRGB::White` is causing me trouble
* Still doesn't work with the trick to change clock to 16MHz

Running `"FastLED version 3.001.003"`.

It was pretty hard to troubleshoot all the way to FastLED. Do you have any suggestions or anything else I could try?

**Comment by Diaoul** [comment]
OK, so I've solved this. It was actually really simple: not enough current... Sorry for the trouble
