### ISSUE TITLE
ESP32 10Mhz cpu frequency LED goes White and full brightness

### ISSUE THREAD

**Issue by peter3099** [FastLED/FastLED#1299]
Hello

I'm using FastLed to drive a single Sk6812, in my case I'm using IN-PI55QATPRPGPBPW which is a clone that you can get in digikey.
`#include <Arduino.h>
#include <FastLED.h>

#define NUM_LEDS 8
#define DATA_PIN 22

CRGB leds[NUM_LEDS];

void setup()
{
  FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);
}

void loop()
{
  for (int i = 0; i < NUM_LEDS; i++)
  {
    leds[i] = CRGB::Red;
  }
  FastLED.show();
  delay(500);
  for (int i = 0; i < NUM_LEDS; i++)
  {
    leds[i] = CRGB::Green;
  }
  FastLED.show();
  delay(500);
  for (int i = 0; i < NUM_LEDS; i++)
  {
    leds[i] = CRGB::Blue;
  }
  FastLED.show();
  delay(500);
  for (int i = 0; i < NUM_LEDS; i++)
  {
    leds[i] = CRGB::Black;
  }
  FastLED.show();
  delay(500);
}`

This code runs perfectly fine and I can achieve any colour/brightness but in order to reduce power consumption on the ESP32  I need to reduce the cpu frequency using setCpuFrequencyMhz(CPU_MHZ);

The ESP32 runs well on 10,20 or 40MHz but If I put any of those then when I call FastLED.show(); I get a full brightness full white LED, if I put 8,16 or 24MHz then it runs well but since they are not frequencies that the ESP32 uses then my power consumption is quite high defeating the whole purpose of the CPU frequency reduction. Fastled only start working when I setCpuFrequencyMhz(80); above 80MHz

Is there any way to adjust the timing on the library so I can implement the 10MHz CPU frequency for the ESP32?

Thanks in advance
Have a good one

**Comment by zackees** [comment]
This is a known problem with ESP32. From what I understand there is an 80mhz clock and if you go below that, the peripherals stop working.
