### ISSUE TITLE
FastLED Not working with New Board Manager 2.0.0

### ISSUE THREAD

**Issue by Jpipe001** [FastLED/FastLED#1300]
I am working on an esp32 Dev Module (Wroom-32) with Arduino IDE 1.8.16 with the latest version of Board Manger 2.0.0.
FastLED 3.4.0 does not compile correctly and LEDs don't work.
My solution is to go back to previous version of Board Manger 1.0.6.
This now works.

![Board_Manager](https://user-images.githubusercontent.com/24758833/134822897-178f5cfc-f8a6-4341-9469-d029533ba5f0.jpg)

**Comment by podaen** [comment]
Are You also using neopixel and fastled together? If yes which versions do have installed? I have rolleback my IDF like you did to 1.0.6... but it doesn't work for me.

**Comment by Jpipe001** [comment]
Actually, although I rolled back the board manager and got the Fastled working with WS2812 leds. I still seem to be having issues.  I am just using Fastled and not Adafruit Neopixels.  These are my libraries:

#include <Arduino.h>
#include <FastLED.h>
#include <WiFi.h>
#include <WiFiMulti.h>
WiFiMulti wifiMulti;
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include "time.h"
#include "ESPmDNS.h"

I am pretty sure that the problem is in the Fastled Library and this issue needs to be looked into.

**Comment by ATLTVHEAD** [comment]
I'm having similar problems. When you say the board manager are you referring to the Esp32 package within the Arduino Boards Manager, or the Arduino Boards Manager itself. If that is the case, how does one do that? 

Sorry for all the questions!

**Comment by Jpipe001** [comment]
A picture speaks 1000 words:
![BoardManager](https://user-images.githubusercontent.com/24758833/135098657-47c398e4-59e9-4864-b10f-4b842257da84.jpg)

**Comment by ATLTVHEAD** [comment]
Thank you so much! @Jpipe001

**Comment by podaen** [comment]
It is a bit strang for me, because I had it working on IDF 2.0.0 but I had neopixel also running and I had to downgrade it, Soo I looked to use the newest versions of the librarys. Now I got IDF 1.0.6 and not the lastest neopixel. (see my topic) Fastled is the newest.

**Comment by podaen** [comment]
Like I said, I used the all latest... except the Neopixel library, and it worked for me. Note, that I am not yet implemented the Wi-Fi for now. You need a task manager to accomplish that.

**Comment by podaen** [comment]
Quot: _You need a task manager to accomplish Wi-Fi._ 

At least that is what I read on the internet. But I had a project on the SDK 1.0.6 running without taskmanager.

**Comment by alorbach** [comment]
I am experiencing very strange problems with the default RMT driver on new SDK 2.0.0
Sometimes it works, sometimes after rebuild LEDs do not respond - FastLED.Show calls work  . but performance appears to be slower. When it works I have like 100 LED FPS and when the problem appears, its about 50 FPS.

I even had crashes which disappeared after I switched to FastLED.Show() 

Somwething is not right.

**Comment by alorbach** [comment]
So I got FastLED to work again but with I2S driver!

> # define FASTLED_ESP32_I2S true

However the I2S driver does random flickering on not controlled LEDs, which might be a problem. I would more like to use the RMT driver again which was working flawless in 1.0.6 but not anymore in 2.0.0 which means there must be a bug somewhere.

**Comment by podaen** [comment]
Did you unregistered the RMT?

**Comment by alorbach** [comment]
> Did you unregistered the RMT?

How? Btw. RMT driver did work for some time and then it stopped working again while  I was improving unrelated code.

**Comment by alorbach** [comment]
Here I made a video from I2S driver, not used LEDs blink from time to time, it does not happen with RMT:
https://user-images.githubusercontent.com/1675286/135405935-cb94f000-a1a5-4a03-a1c4-ce08c95ad7a6.mp4

**Comment by urish** [comment]
> I don't know why it wasn't happening on 1.0.6, all memory was properly initialized to 0 after reboot?

As far as I can tell, the `rmt_tx` variable lives on the stack, so it just gets whatever value that was there before. 

A possible solution (which should also be future-proof) would probably be to initialize the variable when declaring it, e.g.

```cpp
rmt_config_t rmt_tx = {}:
```
