### ISSUE TITLE
Arduino Compile Error: impossible constraint in 'asm'

### ISSUE THREAD

**Issue by FuncTech** [FastLED/FastLED#1316]
I recently used the FastLED library for the first time. My Arduino development environment uses VisualGDB running under Visual Studio 2019. I was targeting an Arduino Nano (ATMega328P 5V, 16MHz). When I made up my first test project the compile failed with many of the following messages:

```
D:\Arduino\Libraries\FastLED\src/platforms/avr/clockless_trinket.h:218:111: error: impossible constraint in 'asm'
 #define LDSCL4(B,O) asm __volatile__("ldd %[scale_base], Z + %[" #O "]\n\tclr %[" #B "]\n\tclc\n\t" ASM_VARS );
                                                                                                               ^
D:\Arduino\Libraries\FastLED\src/platforms/avr/clockless_trinket.h:379:4: note: in expansion of macro 'LDSCL4'
    LDSCL4(b0,O0)  PRESCALEA2(d0)
    ^~~~~~
D:\Arduino\Libraries\FastLED\src/platforms/avr/clockless_trinket.h:225:120: error: impossible constraint in 'asm'
 #define PRESCALEA2(D) asm __volatile__("cpse %[scale_base], __zero_reg__\n\t add %[scale_base],%[" #D "]\n\t" ASM_VARS);
                                                                                                                        ^
D:\Arduino\Libraries\FastLED\src/platforms/avr/clockless_trinket.h:379:19: note: in expansion of macro 'PRESCALEA2'
    LDSCL4(b0,O0)  PRESCALEA2(d0)
                   ^~~~~~~~~~
D:\Arduino\Libraries\FastLED\src/platforms/avr/clockless_trinket.h:228:121: error: impossible constraint in 'asm'
 #define PRESCALEB4(D) asm __volatile__("brcc L_%=\n\tldi %[scale_base], 0xFF\n\tL_%=:\n\tneg %[" #D "]\n\tCLC" ASM_VARS);
```
This can be re-created with the simplest of Arduino scripts:

```
#include <FastLED.h>  // V 3.4.0
CRGB leds[8];

void setup() {
  FastLED.addLeds<WS2812B, 6, BGR>(leds, 8);
} 

void loop()
{
}

```
The same script compiles successfully using the Arduino IDE! After a huge amount of time, I eventually found the problem:

By default VisualGDB suppresses compiler optimization for Arduino scripts (not libraries) for improved compiling speed. Once I turned optimization back on for the main script, it compiled and worked properly. The flag is found under: Project -> VisualGDB Project Properties -> Arduino Project -> "Debug build disables optimization for: __ Arduino Sketch". That check box should be off to enable optimization.

This is probably a bug of some sort, but I can see that the optimized assembler used in clockless_trinket.h is highly tuned and likely not really worth the effort to make it compile (and actually work) with optimization off. I would be happy if the issue were resolved by a documentation update (even just this issue is probably enough to save someone else a frustrating day's work trying to find the issue).

Other than this issue, I really do appreciate the capabilities of the library.
                                                                                                                         ^

**Comment by zackees** [comment]
You are overflowing the execution memory with debug code. This was a common problem but has mostly been fixed in the core driver.
