### ISSUE TITLE
Is it an unused variable?

### ISSUE THREAD

**Issue by Vincent-Stragier** [FastLED/FastLED#1319]
Out of my curiosity, I'd like to know if the following is an unused variable or if it  does serve any purpose?

https://github.com/FastLED/FastLED/blob/ccd2c7b426179ad50e4e2c0d3f132954fc6aa72c/src/FastLED.cpp#L6

**Comment by maddogjt** [comment]
It indeed serves a purpose!

https://github.com/FastLED/FastLED/commit/ae8c92019f7fda09df0522ee35dad8be7e58d181#diff-6a27dc79a9883bd15d2e80c5821c254f18758c558c1b24426fa005dc9db0bb76R25

**Comment by Vincent-Stragier** [comment]
@robertlipe, of course!
