### ISSUE TITLE
Naming conflict between FASTLED and Esp8266AUDIO

### ISSUE THREAD

**Issue by vcchm** [FastLED/FastLED#1323]
The "DIVIDER" macro in FastLED\src/platforms/esp/32/clockless_rmt_esp32.h line 150
#define DIVIDER 2

conflicts with the DIVIDER in AudioGeneratorMOD.h from Esp8266AUDIO
enum {DIVIDER = 10};

In both cases it is not a great idea to use such a common name for a macro.

Suggestion : name it FASTLED_DIVIDER instead of DIVIDER in next versions

**Comment by zackees** [comment]
Fixed a while ago. It's now CLOCK_DIVIDER or something like that.
