### ISSUE TITLE
FastLED 3.1 + Arduino 1.6.0 + Mega 2560 compile error

### ISSUE THREAD

**Issue by artur3** [FastLED/FastLED#135]
FastLED 3.1 compile error:
"...FastLED-FastLED3.1/platforms/avr/fastspi_avr.h:181:42: error: 'UCPHA0' was not declared in this scope
  UCSR0C = (1<<UMSEL01)|(1<<UMSEL00)|(0<<UCPHA0)|(0<<UCPOL0);﻿"

System: openSUSE 13.2 x86_64
Board: Mega 2560 
Arduino: 1.6.0
LED: WS2812

**Comment by focalintent** [comment]
Fixed the build issue for megas.
