### ISSUE TITLE
control reaches end of non-void function [-Wreturn-type] pixelset.h

### ISSUE THREAD

**Issue by PotoMane** [FastLED/FastLED#1376]
Hi. it's seems to not be so important. But just in case : 
[{
	"resource": "/c:/Users/Simon/Documents/PlatformIO/Projects/Table 2.0/.pio/libdeps/megaatmega2560/FastLED/src/pixelset.h",
	"owner": "cpp",
	"severity": 4,
	"message": "control reaches end of non-void function [-Wreturn-type]",
	"startLineNumber": 163,
	"startColumn": 101,
	"endLineNumber": 163,
	"endColumn": 101
}]

**Comment by zackees** [comment]
This has been fixed and is now enforced with CPP check
