### ISSUE TITLE
Doesn't compile right with Arduino 1.6 IDE

### ISSUE THREAD

**Issue by patrickday** [FastLED/FastLED#138]
Anything I compile on 1.6 just lights my TM1803 strip from my Arduino UNO as a blue/cyan color it won't blink or change colors. I tried an older IDE and the same example worked as intended.

**Comment by focalintent** [comment]
What OS are you running the arduino ide on?  Also, try using the most recent FastLED3.1 branch (I've already put some fixes on there) and let me know if that helps.

**Comment by thompson-jeff** [comment]
I too have the same error colors sort of appear but are very light variations.

**Comment by patrickday** [comment]
I'm on Mac Os X 10.10.1. 
It didn't work on 1.6 but worked on 1.0.5

i'll try FastLED3.1

**Comment by spbolton** [comment]
I am on windows 8.  Same issue with TM1803.  Failed on 1.6 and 1.59 but worked on 1.0.6.  It failed on 1.6 with FastLED3.1 also

**Comment by focalintent** [comment]
Fixed on the 3.1 branch.
