### ISSUE TITLE
WS2818 support?

### ISSUE THREAD

**Issue by laserarm98** [FastLED/FastLED#1385]
Hi, I'm attempting to use FastLED to drive WS2818B chips, but none of the preconfigured profiles are working. Will FastLED get WS2818 support anytime soon?

**Comment by marmilicious** [comment]
Related question here: 
https://www.reddit.com/r/FastLED/comments/e0szhe/ws2818_string_will_not_light/

Should work with specifying type WS2813.

**Comment by marmilicious** [comment]
@laserarm98 Did you get things to work? Let use know what you discovered. If ticket is no longer needed feel free to close it.

**Comment by laserarm98** [comment]
@marmilicious Turns out the WS2812 profile worked for me, but the R and G colors were flipped. Works well for my purpose.
