### ISSUE TITLE
How to call/ change LED colour by input(text)

### ISSUE THREAD

**Issue by lc2047** [FastLED/FastLED#1386]
Hi 

How to change the LED color by text input?
In FastLED, there have serval methods.
1. leds[i] = CRGB::Red
2. leds[i] = CRGB(0,0,255);
3. leds[i] = 0xFF0000;
4. leds[i].setRGB(0,0,255);

However, I prefer using the predefined colors list of FastLED. The list has well defined in "pixeltypes.h". 
If duplicate predefined colors list in my code, seem it is not good for memory efficiency. Also, have a risk(not align) in FastLed update.
I am a beginner in programming and don't know how to convert color name("Red") to RGB data(e.g. 0xFF0000). 

Please help and share your comments with me.

Sincerely

LC

**Comment by marmilicious** [comment]
Hello LC. We use github "issues" here mostly just for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: https://www.reddit.com/r/FastLED

**Comment by lc2047** [comment]
@marmilicious 

Thanks & note.

**Comment by lc2047** [comment]
move to correct area
