### ISSUE TITLE
Not working with ESP32 C3

### ISSUE THREAD

**Issue by Skywalkerf34** [FastLED/FastLED#1389]
Hi,

I can compile but the result is lighting 2812 LED out of control
I suspect this is "just" timer issue as ESP32 C3 is 160mhz CPU
Can you give me some ways to change and try to fix this ?

Rgds

**Comment by s-light** [comment]
do you use wifi at the same time?
could be a duplicate of #1349

**Comment by Skywalkerf34** [comment]
yes I use wifi

**Comment by s-light** [comment]
try to temporarily disable wifi - just to be sure its the same bug as #1349.

**Comment by samguyer** [comment]
@Skywalkerf34 How's it going? Do you still need support, or can we close this issue?
