### ISSUE TITLE
Add Hardware SPI for u2 Series (16u2)

### ISSUE THREAD

**Issue by NicoHood** [FastLED/FastLED#139]
Referring to #125 Hardware SPI on 16u2 currently seems not to work.
Bitbang is working fine though.

**Comment by focalintent** [comment]
Unlikely to actually support the 16u2 hardware SPI, as the world is moving to arm.  (I will continue to support the major AVR based platforms for a while longer, but the esoteric edge stuff is unlikely - I just don't have the time).

**Comment by NicoHood** [comment]
You may want to add the 8/16/32u2/at90usb82/162 (via HoodLoader2) to the 3.1 release notes. I've only tested Ws2801 but that works great via software spi.

**Comment by NicoHood** [comment]
Also a documentation of how to use every n millis functions would be nice. This sounds like something very useful. I just stumbled across this now in the release page.
