### ISSUE TITLE
fastspi.h uses wrong variable for spi1

### ISSUE THREAD

**Issue by anthonyrubalcaba** [FastLED/FastLED#1410]
/FastLED/src/fastspi.h >> line 91,92: 

template<uint32_t SPI_SPEED>
class SPIOutput<SPI1_DATA, **SPI_CLOCK**, SPI_SPEED> : public Teensy4HardwareSPIOutput<SPI1_DATA, SPI1_CLOCK, SPI_SPEED, SPI1, 1> {};

The SPI_CLOCK should be SPI1_CLOCK

Corrected:

template<uint32_t SPI_SPEED>
class SPIOutput<SPI1_DATA, **SPI1_CLOCK**, SPI_SPEED> : public Teensy4HardwareSPIOutput<SPI1_DATA, SPI1_CLOCK, SPI_SPEED, SPI1, 1> {};

This bug was discovered by user [AntiDysentery](https://forum.pjrc.com/members/86791-AntiDysentery)
in this post: 
https://forum.pjrc.com/threads/70671-Teensy-4-1-with-FastLed-No-Hardware-SPI

**Comment by zackees** [comment]
Do you know how to create a pull request for this bug fix?

Fork -> Create branch -> do changes -> git commit / push and follow the instructions that appear. Your git should now contain a pull request. Please mention this bug URL and github will link them automatically.

**Comment by ssilverman** [comment]
I made a pull request a couple of days ago that fixes this: #1413.

**Comment by zackees** [comment]
I'd ok it if I had ownership, but I don't.
