### ISSUE TITLE
Mystery PR checks fail: "Error: Unknown development platform 'atmelavr'"

### ISSUE THREAD

**Issue by ssilverman** [FastLED/FastLED#1419]
My last ~two~ three PRs can't pass checks because of an "Error: Unknown development platform 'atmelavr'" error.

https://github.com/FastLED/FastLED/pull/1413
https://github.com/FastLED/FastLED/pull/1418
https://github.com/FastLED/FastLED/pull/1420

**Comment by kriegsman** [comment]
In some places online I'm seeing 'atmelmegaavr' used instead of 'atmelavr'; looking into it, but any additional thoughts or input would be quite welcome, as I'm definitely not a CI expert here!

**Comment by kriegsman** [comment]
OK, this looks fixed by https://github.com/FastLED/FastLED/pull/1428, with thanks to @dmadison.

In order to process the PRs that were submitted in the interim, I'll probably have to Close and Re-open them to make the updated tests re-run.
