### ISSUE TITLE
Support for Seeeduino Xiao

### ISSUE THREAD

**Issue by faizannazir** [FastLED/FastLED#1426]
Please add support for seeduino Xiao

**Comment by smurphyUSI** [comment]
The Seeeduino Xiao appears to be a highly reduced variation of the Arduino Zero.

If setting your board in the IDE or code as the Zero doesn't work, then I suggest taking this topic to the Reddit.
https://www.reddit.com/r/FastLED/

You will need to provide the IDE you are using, LED model and that you have the Seedunio Xiao.
I know that other user had problems with Zero variations, especially with the pinouts, so the Reddit likely has some insights.

**Comment by zackees** [comment]
Works
