### ISSUE TITLE
support for WS2813B-B

### ISSUE THREAD

**Issue by arifainchtein** [FastLED/FastLED#1431]
Hello,
I have been using the WS2812B but because of cost, i was hoping to use the WS2813B-B.  Is the WS2813B-B cipatible withthe FastLed library? If i  have code for the WS2812 working is there any configuration changes to use the ws2813?

thanks

**Comment by smurphyUSI** [comment]
Have you attempted to use the WS2813 setup yet?
FastLED does support WS2813 variations, but sometimes the RGB order is swapped.

Try running this in your code:

#include <FastLED.h>
#define NUM_LEDS 100
#define DATA_PIN 6
// - Change the above to your actual number of LEDs and the data pin of your controller

CRGB leds[NUM_LEDS];

void setup()
{ 
  FastLED.addLeds<WS2813, DATA_PIN>(leds, NUM_LEDS);
}

If the it works, but the color is wrong, try chaning your RGB order.
There is an example script here to check the different options.
You just have to uncomment and run one-at-at time for each variation you think maybe correct:
https://github.com/FastLED/FastLED/tree/master/examples/RGBCalibrate

**Comment by arifainchtein** [comment]
Hello,
thanks fr the answer.  I have not yet used the ws2813 but i am sending some pcbs to manufacture and wanted to replace the ws2812-4020 with ws2813 because of cost.  Knowing that the FastLed library is compatible is great because i really like this library.
Will send the pcbto manufacture and will report later.
thanks

**Comment by marmilicious** [comment]
@briandilley Have you tried it? My understanding is the only difference between the WS2813 A,B,C,D variants is brightness level, so should work.

https://www.ledstripstudio.com/wiki/ws2813/

**Comment by briandilley** [comment]
Yes - it works.

**Comment by marmilicious** [comment]
@samguyer Unless @briandilley has anything else at the moment, this issue seems like it can be closed.
