### ISSUE TITLE
Read data from another controller

### ISSUE THREAD

**Issue by lepitrust** [FastLED/FastLED#1440]
With fastled is possibile to read data from data pin from another controller?

I need to read data from data pin of addressable header of pc motherboard and manage it.

Is possible?

Thanks

**Comment by zackees** [comment]
You have to handle that yourself, passing the information back and forth using SPI, IS2 or UART or simple high/low.

**Comment by samguyer** [comment]
@lepitrust I would recommend taking this kind of question over to the FastLED Subreddit: https://www.reddit.com/r/FastLED/
