### ISSUE TITLE
CRGB::Red and CRGB::Green are inverted

### ISSUE THREAD

**Issue by diegochencoconut** [FastLED/FastLED#1448]
To those whom may concern:
When we're using this repository by ATTiny, we've noticed that CRGB::Red and CRGB::Green are inverted.

When we use CRGB::Red, the light shows Green.
Otherwise, when we use CRGB::Green, the light shows Red.

We're using WS2812 & Attiny.

Thank you.

**Comment by zackees** [comment]
That's your LED strip. Change the RGB order in your FastLED template instantiation and it will work fine.

**Comment by Loaded-Dice** [comment]
Zackees is right.
To make it a little bit easier to get what he means:

Find  this line in your code

FastLED.addLeds<WS2812, DATA_PIN, RGB>(leds, NUM_LEDS); 

and change it into this line:

FastLED.addLeds<WS2812, DATA_PIN, GRB >(leds, NUM_LEDS); 

If the color order has swapped but still not correct
Adjust the three letters you changed from RGB to GRB to another order until your color order is correct.

**Comment by samguyer** [comment]
Thanks @zackees and @Loaded-Dice for helping out! @diegochencoconut, did this fix your problem? Can we close this issue?

**Comment by diegochencoconut** [comment]
@samguyer  @zackees @Loaded-Dice 

Thanks for your reply!
It fixed my problem.

**Comment by zackees** [comment]
Glad it worked! Let's close this issue then.
