### ISSUE TITLE
Going over 10 multiple controller pins crashes ESP32-S2

### ISSUE THREAD

**Issue by KodiWolf** [FastLED/FastLED#1454]
I have 12 separate clockless WS2812 LED strips of different lengths (total 188 LEDs) that need to be driven by 12 separate pins from an ESP32-S2.
I chose a S2 over an ESP32 for more GPIOs but am starting to see its hardware limitations.
Driving them using the RMT peripheral (clockless_rmt_esp32.h), and seeing that 32 is the default maximum number of controllers `#define FASTLED_RMT_MAX_CONTROLLERS 32`, I'm trying to understand why it crashes (reboots) if I setup more than 10 FastLED controllers as below.
```
FastLED.addLeds<WS2812B, ARGBLED_PWM_PIN_1, GRB>(leds, ARGBLED_START_POS[0], ARGBLED_LENGTHS[0]);
FastLED.addLeds<WS2812B, ARGBLED_PWM_PIN_2, GRB>(leds, ARGBLED_START_POS[1], ARGBLED_LENGTHS[1]);
.
.
.
FastLED.addLeds<WS2812B, ARGBLED_PWM_PIN_11, GRB>(leds, ARGBLED_START_POS[10], ARGBLED_LENGTHS[10]);
FastLED.addLeds<WS2812B, ARGBLED_PWM_PIN_12, GRB>(leds, ARGBLED_START_POS[11], ARGBLED_LENGTHS[11]);
```
The S2 only has 4 RMT channels compared to 8 on the ESP32, but I've had to further reduced this down to 2 `#define FASTLED_RMT_MAX_CHANNELS 2` as the processor would freeze up randomly after a short period from boot. In parallel to FastLED, I am making use of WiFi, SPI and LittleFS to drive a TFT LCD via TFT_eSPI, both hardware Serial ports, I2C, Pulse counter peripheral, and several interupts.

I'm using the latest code versions as below:
`FastLED @ 3.5.0`
`Arduino-ESP32 @ 2.0.5`

I was able to get all 12 controllers running on an older arduino framework v2.0.1 while still using the lastest version of FastLED v3.5.0. But it took quite a fight to get it to work with WiFi. Something about a `CORRUPT HEAP: multi_heap`.

Compromising with only 10 drivers would be a real pain as this is a completed complex project, so I'm stuck with the older framework at the moment and was wondering if there's another way to increase this apparent controller limit.

I've tried using I2S `#define FASTLED_ESP32_I2S` but got compile errors over a missing second I2S. The S2 only has a single I2S and I believe FastLED currently uses both, one for dumping the buffer while the other gets pupulated for a seamless cycle.

Any suggestions or input would be greatly appreciated.

**Comment by zackees** [comment]
Try defining FASTLED_FORCE_SOFTWARE_SPI first

**Comment by KodiWolf** [comment]
Nope, setting `#define FASTLED_FORCE_SOFTWARE_SPI` didn't fix it
```
#define FASTLED_FORCE_SOFTWARE_SPI
#include <FastLED.h>
```

**Comment by KodiWolf** [comment]
So it turns out that the 11th pin assignment I had coinsides with ESP32-S2's GPIO26 which I am now realising is a reserved pin used for SPI CS for Flash and PSRAM. This also explains why I get random but repeatable artifact lighting on the LED strip attached to GPIO26 during boot before configuring FASTLED.

I'm still baffled as to how I got it to successfully drive an LED strip while using SPIFFS during my prototyping stage. Maybe there really is a software workaround to disable the function of SPICS1 after boot. If anyone knows a proper way to disable or override it after boot, please let me know. But I think I'm forced to reassign the pin and modify the hardware. Guess that's why they have PCBA revisions.

Reference: https://esp32.com/viewtopic.php?t=21115
