### ISSUE TITLE
ESP8266 crashes when using FastLED.show()

### ISSUE THREAD

**Issue by vhaude** [FastLED/FastLED#1468]
problem got solved

**Comment by vhaude** [comment]
quick update;
I was able to narrow the problem further down:
When not using "mode_color_cycle()" for setting the color or mode of the string, FastLED.show(); works.
So I assume there is somehow a problem at transferring the currentPalette value from "mode_color_cycle()" to "FillLEDsFromPaletteColors()" and ultimately to "FastLED.show()"

**Comment by vhaude** [comment]
I was now able to solve it

**Comment by marmilicious** [comment]
Where are you going to share what was wrong?

**Comment by vhaude** [comment]
Hi, didnt know if it actually was of interest for someone. 
I was tinkering with 16LEDs while riding my code and was still using 16 in one place ( fill_solid(leds, 16, CRGB::White) ) instead of "NUM_LEDs" which when using FastLED.show() caused it to crash the program.

**Comment by marmilicious** [comment]
Thank you, glad you got it sorted out.
