### ISSUE TITLE
Any reason to not create a release?

### ISSUE THREAD

**Issue by sblantipodi** [FastLED/FastLED#1499]
As title.
Last FastLED release comes from january 2022, are there any reason why not creating a new release?

**Comment by igor-d-n** [comment]
It **NEED** release as soon as possible:
_warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]_
lots of such errors when trying to compile with new 8266 vesion.

**Comment by kriegsman** [comment]
We just released FastLED 3.6.0.  Thank you for all the help and support with the library and the FastLED community!  We're working on expanding our team so that we can do more releases, more often, and with more good content.
