### ISSUE TITLE
Typo in lib8tion.h documentation of `ease8InOutCubic`

### ISSUE THREAD

**Issue by sethtroisi** [FastLED/FastLED#1502]
I'm fairly sure

`  102      ease8InOutCubic(x) == 3(x^i) - 2(x^3)`

should be

`  102      ease8InOutCubic(x) == 3(x^2) - 2(x^3)`

**Comment by zackees** [comment]
Oh dear...

**Comment by dmadison** [comment]
This was fixed in commit 54bcb56, which has been merged but a release has not been published.
