### ISSUE TITLE
Esp32 Color is Changed

### ISSUE THREAD

**Issue by ruielias** [FastLED/FastLED#1512]
Hi,

I'm using an ESP3, on PlatformIO and using a "7Bit Ring".
When I configure it to light Red, the LEDs light Green...

And when I set it to light green, the leds light red...

What am I doing wrong?

`#include <Arduino.h>
#include <FastLED.h>

#define NUM_LEDS 7
#define DATA_PIN 13

// Define the array of leds
CRGB leds[NUM_LEDS];

void setup() { 
    
 Serial.begin(115200);
 Serial.printf("\nStart\n");	

  FastLED.addLeds<WS2812B, DATA_PIN, RGB>(leds, NUM_LEDS);  // GRB ordering is typical
  FastLED.setBrightness(5);
  delay(500);

  for(uint8_t x=0;x<6;x++)
  {
    leds[x] = CRGB::Red;
    FastLED.show();
    delay(25);
  }
}
void loop() { 
}`

PlatforIO:

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.6.0

**Comment by yesyesuk** [comment]
>> FastLED.addLeds<WS2812B, DATA_PIN, **RGB**>(leds, NUM_LEDS); // GRB ordering is typical

The "RGB" is the colour order of your string. Change that to GRB.
FastLED.addLeds<WS2812B, DATA_PIN, **GRB**>(leds, NUM_LEDS); // GRB ordering is typical

**Comment by ruielias** [comment]
Hi yesyesuk,

It is already correct.
Thank you very much.

**Comment by marmilicious** [comment]
Did you run the RGB calibrate example?

**Comment by ruielias** [comment]
I didn't execute RGB calibrate example.
But he is already working according to the help of the "yesyesuk".

**Comment by marmilicious** [comment]
Ok good. You can close this issue if it's solved.
