### ISSUE TITLE
WS2812B LED stripe with Cylon or Blink sketch red/green interchanges

### ISSUE THREAD

**Issue by Pippsen** [FastLED/FastLED#153]
Hello all,

I use an Arduino UNO R3 with the IDE 1.7.0 , the FastLed MAster library, a WS2812B LED stripe with an external 5V power supply and if I upload the Cylon or Blink sketch the LED's illuminates green instead of red (if red is chosen) or red instead of green(if green is chosen). In case I change the controller type to NEOPIXEL everything is fine.

Any ideas?

Thank you for support.

**Comment by focalintent** [comment]
You need to change your RGB ordering.  Please see https://github.com/FastLED/FastLED/wiki/Rgb-calibration for documentation on this.
