### ISSUE TITLE
[Question] Is there a way to import only the helper functions?

### ISSUE THREAD

**Issue by hitech95** [FastLED/FastLED#1530]
Hi,
I would love to use this library to import colors and math functions.
I'm not interested on the core part of the library (driving LEDs)

I somehow recall from my memory that this library was splitted into two different parts.
Is there a way to import the helper functions without importing the main FastLED.h?

I cannot import it due to the unsupported platform.

**Comment by marmilicious** [comment]
There's nothing setup for this that I know of. Have you tried manually pulling some stuff out into your own include file? Start with something simple like just a few of the math functions, along with any needed dependencies. Once you have that working then you can expand to the rest of the math functions, and then the color stuff.

I once pulled out just the EVERY_N timer stuff so I could include that as a simple .h file into a custom project. Try something similar.
https://gist.github.com/marmilicious/43cda5561971f410753e3cd050e0e4c7

**Comment by samguyer** [comment]
@hitech95 Can we close this issue? If not, can we move the discussion to the FastLED subreddit? I'm sure other people would like to see the answer (and references -- thanks @marmilicious!)

**Comment by hitech95** [comment]
I've ended up cloning the files I need and created a small packce to use.

Having a global importable .h for noise, color and math functions only would be quite handy. But I think is out of scope.
