### ISSUE TITLE
is there a way to compile for Win32/64 (Windows) to be able to simulate it?

### ISSUE THREAD

**Issue by Feneck91** [FastLED/FastLED#1549]
To be able to simulate an Arduino project, I would like to be able to compile it under Windows (Visual Studio).
I knon some PIN (A0 ... etc) are missing but It can be easilly emulated.
I don't know if someone already done it.

**Comment by zackees** [comment]
No, but there are emulators that I've seen that might work.

**Comment by marmilicious** [comment]
@Feneck91 Try out Wokwi.com for online FastLED simulation.

https://wokwi.com/projects/289631971594732040

**Comment by zackees** [comment]
I've added a linux build. But it also works for windows. See the builder badge on the readme.
