### ISSUE TITLE
No information on how to port FastLED to a new platform

### ISSUE THREAD

**Issue by rah2501** [FastLED/FastLED#1557]
I've searched the website, the wiki, the FAQ and found no information on how to port FastLED to a new platform.  I would expect at least a paragraph on what one needs to do in the codebase in order to add a new platform.

**Comment by zackees** [comment]
If you attempt to compile it you'll get a compiler error pointing you to the correct files.

The platforms can be found in the platform directory.

**Comment by samguyer** [comment]
@rah2501 I can probably help put this documentation together. I did the ESP32 support, so I had to go through the process recently (relatively recently, anyway). There's also a considerable difference between adding support for a variant of an existing platform (e.g., a different ARM board) vs a totally new platform. What are you hoping to do?

**Comment by rah2501** [comment]
> What are you hoping to do?

To be clear, I created this issue to track the lack of documentation rather than seek help for my own particular porting efforts.  The appropriate place for those discussions would be a separate issue I think.

>  There's also a considerable difference between adding support for a variant of an existing platform (e.g., a different ARM board) vs a totally new platform. 

Can I suggest for consideration, that you could write two responses, one each for both possible answers that I could give, and those responses could be included in the README.md? :-)  That way, you're helping both me and others.

**Comment by samguyer** [comment]
Do you need this documentation right now, or not? I think it's a great idea to get this information together, but I'm unclear on what the impetus is at the moment.

**Comment by rah2501** [comment]
> Do you need this documentation right now, or not?

That depends on what's in the documentation and the documentation doesn't exist :-)  So difficult to answer..

> I'm unclear on what the impetus is at the moment

The impetus for me to create this issue was the knowledge that in future, people will need to port the project and will find an absence of information on porting, as I did.

**Comment by samguyer** [comment]
What I mean, specifically, is: are you currently working on a port or planning to do so in the near future? Do you have a specific platform target in mind?

**Comment by rah2501** [comment]
> What I mean, specifically, is: are you currently working on a port or planning to do so in the near future? Do you have a specific platform target in mind?

I don't think my personal activities are relevant to this issue.

**Comment by samguyer** [comment]
It is relevant, in the following sense: this is an entirely volunteer-run project, so many of the new features and content come from user contributions, or some collaboration between us and the users who need those features. It is very much a community effort. So, if you want new documentation, you are probably going to need to engage with us a bit more.

**Comment by samguyer** [comment]
Actually, it looks like there is an existing (brief) porting document that covers the basics:

https://github.com/FastLED/FastLED/blob/master/PORTING.md

**Comment by rah2501** [comment]
> if you want new documentation

I don't want new documentation for my benefit, I want to help the FastLED project identify a barrier-to-entry which can be lowered, benefitting all.

**Comment by zackees** [comment]
If we spell it out on how to port, then there could be a lot of people attempting to do this but won't be advanced enough to actually get the platform ported and will abandon the work, but not before asking for a lot of help.

My personal assumption is that if you are advanced enough to compile for a toolchain, then you'll figure out the missing files pretty quickly. But I'm open to having a minority opinion on this.

**Comment by rah2501** [comment]
> If we spell it out on how to port, then there could be a lot of people attempting to do this but won't be advanced enough to actually get the platform ported and will abandon the work, but not before asking for a lot of help.

O_o  WTF?!

**Comment by samguyer** [comment]
@rah2501 Did you look at the PORTING.md file? It's obviously a little thin, but it is there. Do you want to keep this issue open?

**Comment by rah2501** [comment]
I've made a pull request to add a pointer to the PORTING.md which would close this issue.

**Comment by samguyer** [comment]
OK, excellent. Thank you.
