### ISSUE TITLE
Group of leds with same patron

### ISSUE THREAD

**Issue by dorcu** [FastLED/FastLED#1560]
Hello. I have a group of 12, each group is made up of 3 groups of 10 LEDs. How should I make the 3 groups of 10 LEDs have the same pattern?

#define NUM_LEDS_PER_GROUP 10
#define NUM_GROUPS 12
#define NUM_LEDS (NUM_LEDS_PER_GROUP * NUM_GROUPS)
#define DATA_PIN D1
#define LED_TYPE WS2812
#define COLOR_ORDER GRB

**Comment by samguyer** [comment]
Hi! I would recommend asking this question on the FastLED Subreddit r/fastled. You will get tons of help and support from our amazing community there!

**Comment by dorcu** [comment]
Thanks
