### ISSUE TITLE
Should default APA102 clock frequency be set lower?

### ISSUE THREAD

**Issue by zackees** [FastLED/FastLED#1568]
I've been working with 1024 APA102 leds (or maybe SK9822, not exactly sure) and realized that it's not stable until I use 6mhz.

Looking into this I saw this post about the click signal being truncated:

https://www.pjrc.com/why-apa102-leds-have-trouble-at-24-mhz/

So 24mhz only works at very short strips, and in long strips where it really counts, it doesn't work at all. So should we change the default to 6mhz?

**Comment by marmilicious** [comment]
I believe it was already reduced from 24 to a default of 12MHz.

My thought would be to leave it at 12MHz for now. But would it be useful in the example files that have the lists of pixel types in the Setup section (such as FirstLight.ino) to add a comment as to the default MHz to cue the user into that?

from this:
`// FastLED.addLeds<APA102, DATA_PIN, CLOCK_PIN, RGB>(leds, NUM_LEDS);  // BGR ordering is typical` 
to perhaps something like:
`// FastLED.addLeds<APA102, DATA_PIN, CLOCK_PIN, RGB>(leds, NUM_LEDS);  // BGR ordering is typical, defaults to 12MHz data rate`
