### ISSUE TITLE
Porting FastLED library, error message unable to find application.h!

### ISSUE THREAD

**Issue by tangan1** [FastLED/FastLED#1578]

**Comment by kriegsman** [comment]
Thanks for reporting this - could you share more information about the platform that you're porting to?  Is it an Arduino platform, or something else?

**Comment by tangan1** [comment]
> 感谢您报告此事 - 您能分享有关您要移植到的平台的更多信息吗？是Arduino平台，还是其他什么？

Using stm32 on Keil。

**Comment by zackees** [comment]
Post your code.
