### ISSUE TITLE
deftype simplepatternlist not defining?

### ISSUE THREAD

**Issue by jester101YT** [FastLED/FastLED#1590]
i want to make an andon/stack light i got the code down where i can controle each pixel individualy but the rainbow pattern doesnt want to define i have copy pasted every thing from the demo sketch but still no dice can somebody help me clean up the code and fix the defining error
![image_2024-01-22_124400027](https://github.com/FastLED/FastLED/assets/75140693/c2fd036f-adc3-4e83-99e2-1044017aa53b)

**Comment by marmilicious** [comment]
We mainly use GitHub for bug reports and improvement requests. For general help and coding questions please use the FastLED reddit group. 

https://www.reddit.com/r/FastLED

**Comment by marmilicious** [comment]
@samguyer or @kriegsman   This one can be closed as @jester101YT found us and posted on reddit. 

(or @jester101YT you can also close this)

**Comment by kriegsman** [comment]
Thanks!  Closing this issue here.
