### ISSUE TITLE
Compiling for esp-idf esp32 - link failure

### ISSUE THREAD

**Issue by PhilColbert** [FastLED/FastLED#1592]
Downloaded the latest esp-idf and fastled 3.6, running arduino core as component.

Getting linking errors for the line FastLED.addLeds<APA102, 15, 16, RGB>(leds, 4);

Tried searching for this error and tried adding 

idf_component_register(SRCS "loop.cpp" 

INCLUDE_DIRS   fastled/src fastled/src/platforms/esp/32
SRC_DIRS   fastled/src fastled/src/platforms/esp/32

also 

various different ways of adding

COMPONENT_SRCS "FastLED/src/FastLED.cpp" "FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp"
COMPONENT_ADD_INCLUDEDIRS fastled/src fastled/src/platforms/esp/32
COMPONENT_SRCDIRS fastled/src fastled/src/platforms/esp/32

But cant get it to compile, any ideas ?

Failure is 

d:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(loop.cpp.obj):(.literal._ZN14CLEDControllerC5Ev[_ZN14CLEDControllerC5Ev]+0x4): undefined reference to `CLEDController::m_pHead'
d:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(loop.cpp.obj):(.literal._ZN14CLEDControllerC5Ev[_ZN14CLEDControllerC5Ev]+0x8): undefined reference to `CLEDController::m_pTail'
d:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(loop.cpp.obj):(.literal._ZN8CFastLED7addLedsIL12ESPIChipsets6ELh15ELh16EL6EOrder10EEER14CLEDControllerP4CRGBii[_ZN8CFastLED7addLedsIL12ESPIChipsets6ELh15ELh16EL6EOrder10EEER14CLEDControllerP4CRGBii]+0x10): undefined reference to `CFastLED::addLeds(CLEDController*, CRGB*, int, int)'
d:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(loop.cpp.obj): in function `CLEDController& CFastLED::addLeds<(ESPIChipsets)6, (unsigned char)15, (unsigned char)16, (EOrder)10>(CRGB*, int, int)':
D:/espidf/examples/get-started/hello_world/main/fastled/src/FastLED.h:306: undefined reference to `CFastLED::addLeds(CLEDController*, CRGB*, int, int)'

**Comment by samguyer** [comment]
@PhilColbert I think this problem will go away with the next release (3.7) which should go out today. Let me know what happens!
