### ISSUE TITLE
color wrong

### ISSUE THREAD

**Issue by mauriziozito01** [FastLED/FastLED#1603]
Greetings
I have a WS2811 strip and I'm trying to control it with a NodeMCU.
I noticed the following:
I tried to power only LEDs 0,2,4,6 and 9 to do a test but I see that they are shifted by 1.
LED 0 is skipped.
Then I realized that the colors are wrong.
Basically if I pass 255,0,0 I get a nice blue and not the red.
I used this code:
#########################################################################
#include "FastLED.h"

#define NUM_LEDS 69
CRGB leds[NUM_LEDS];
#define PIN D4

void setup()
{
  Serial.begin(9600);
  FastLED.addLeds<WS2811, PIN, GRB>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );
}

void loop() {
  RGBLoop();
}

void RGBLoop(){
  byte red = 255;
  byte green = 0;
  byte blue = 0;
  //setAll(red,green,blue);
  setAll(0,0,0);
  delay(1000);
  setPixel(0, red, green, blue);
  setPixel(2, red, green, blue);
  setPixel(4, red, green, blue);
  setPixel(6, red, green, blue);
  setPixel(9, red, green, blue);
  showStrip();
  delay(5000);
  setAll(0,0,0);
  delay(1000);
}

void showStrip() {
    FastLED.show();
}

void setPixel(int Pixel, byte red, byte green, byte blue) {
 
   leds[Pixel].r = red;
   leds[Pixel].g = green;
   leds[Pixel].b = blue;
}

void setAll(byte red, byte green, byte blue) {
  for(int i = 0; i < NUM_LEDS; i++ ) {
    setPixel(i, red, green, blue);
  }
  showStrip();
}

###########################################################################

I'm afraid it's a connection problem or a quality problem with the material.
But before I do it all again I would like to understand if I have any way of understanding what I'm doing wrong

Thanks in advance
I'm sorry for my english

![20240303_145656](https://github.com/FastLED/FastLED/assets/75208171/ae0abd36-cdc2-461f-a495-b822be5d80af)
![20240303_145717](https://github.com/FastLED/FastLED/assets/75208171/89ab8248-5077-4bb0-a538-6345f9bfc56e)
![image](https://github.com/FastLED/FastLED/assets/75208171/7ff8b7dd-42bd-46c7-9060-fa483041994e)

**Comment by marmilicious** [comment]
Hello @mauriziozito01 
We use github "issues" here mostly just for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: 

https://www.reddit.com/r/FastLED

Please include all the good information and images you shared here with your question there too.
