### ISSUE TITLE
SD600 RGB pixel chip 

### ISSUE THREAD

**Issue by ledproduction** [FastLED/FastLED#1604]
Hello, i have rgb pixel SD600 , can i used with FastLED library?

**Comment by marmilicious** [comment]
Do you have a link to the product or a data sheet?

**Comment by ledproduction** [comment]
I atashed you dada frame chart and library which is work for arduino .

În dum., 3 mar. 2024 la 19:19, Marc Miller ***@***.***> a
scris:
