### ISSUE TITLE
Compile Issue Caused By pixeltypes.h:7,controller.h:9,FastLED.h:57, & noise.cpp:6:

### ISSUE THREAD

**Issue by ylnest2018** [FastLED/FastLED#1605]
I get this when compiling my project, I have seen other links with a similar issue on this page spreading over a couple years, everyone seems to link it to another issue but im yet to find one with a real solution.

https://github.com/FastLED/FastLED/issues/1553

`Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp: In function 'void fill_raw_2dnoise8(uint8_t*, int, int, uint8_t, q44, fract8, int, uint16_t, int, uint16_t, int, uint16_t)':
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:623:100: error: ambiguous overload for 'operator*' (operand types are 'q44' {aka 'q<unsigned char, 4, 4>'} and 'int')
  623 |     fill_raw_2dnoise8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, freq44 * scalex, y*freq44, freq44 * scaley, time);
      |                                                                                             ~~~~~~ ^ ~~~~~~
      |                                                                                             |        |
      |                                                                                             |        int
      |                                                                                             q44 {aka q<unsigned char, 4, 4>}
In file included from /Users/leo/Documents/Arduino/libraries/FastLED/src/pixeltypes.h:7,
                 from /Users/leo/Documents/Arduino/libraries/FastLED/src/controller.h:9,
                 from /Users/leo/Documents/Arduino/libraries/FastLED/src/FastLED.h:57,
                 from /Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:6:
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:909:14: note: candidate: 'uint32_t q<T, F, I>::operator*(uint32_t) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  909 |     uint32_t operator*(uint32_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:911:14: note: candidate: 'uint16_t q<T, F, I>::operator*(uint16_t) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  911 |     uint16_t operator*(uint16_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:913:13: note: candidate: 'int32_t q<T, F, I>::operator*(int32_t) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  913 |     int32_t operator*(int32_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:915:13: note: candidate: 'int16_t q<T, F, I>::operator*(int16_t) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  915 |     int16_t operator*(int16_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:623:127: error: ambiguous overload for 'operator*' (operand types are 'q44' {aka 'q<unsigned char, 4, 4>'} and 'int')
  623 |     fill_raw_2dnoise8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, freq44 * scalex, y*freq44, freq44 * scaley, time);
      |                                                                                                                        ~~~~~~ ^ ~~~~~~
      |                                                                                                                        |        |
      |                                                                                                                        |        int
      |                                                                                                                        q44 {aka q<unsigned char, 4, 4>}
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:909:14: note: candidate: 'uint32_t q<T, F, I>::operator*(uint32_t) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  909 |     uint32_t operator*(uint32_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:911:14: note: candidate: 'uint16_t q<T, F, I>::operator*(uint16_t) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  911 |     uint16_t operator*(uint16_t v) { return (v*i) + ((v*f)>>F); }
      |              ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:913:13: note: candidate: 'int32_t q<T, F, I>::operator*(int32_t) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  913 |     int32_t operator*(int32_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:915:13: note: candidate: 'int16_t q<T, F, I>::operator*(int16_t) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  915 |     int16_t operator*(int16_t v) { return (v*i) + ((v*f)>>F); }
      |             ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp: In function 'void fill_raw_2dnoise16(uint16_t*, int, int, uint8_t, q88, fract16, int, uint32_t, int, uint32_t, int, uint32_t)':
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:661:101: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q88' {aka 'q<short unsigned int, 8, 8>'})
  661 |     fill_raw_2dnoise16(pData, width, height, octaves-1, freq88, amplitude, skip, x *freq88 , scalex *freq88, y * freq88, scaley * freq88, time);
      |                                                                                              ~~~~~~ ^~~~~~~
      |                                                                                              |       |
      |                                                                                              int     q88 {aka q<short unsigned int, 8, 8>}
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:922:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint32_t = long unsigned int]'
  922 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:923:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint16_t = short unsigned int]'
  923 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:924:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int32_t = long int]'
  924 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:925:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int16_t = short int]'
  925 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:661:129: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q88' {aka 'q<short unsigned int, 8, 8>'})
  661 |     fill_raw_2dnoise16(pData, width, height, octaves-1, freq88, amplitude, skip, x *freq88 , scalex *freq88, y * freq88, scaley * freq88, time);
      |                                                                                                                          ~~~~~~ ^ ~~~~~~
      |                                                                                                                          |        |
      |                                                                                                                          int      q88 {aka q<short unsigned int, 8, 8>}
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:922:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint32_t = long unsigned int]'
  922 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:923:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; uint16_t = short unsigned int]'
  923 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:924:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int32_t = long int]'
  924 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:925:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = short unsigned int; int F = 8; int I = 8; int16_t = short int]'
  925 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp: In function 'void fill_raw_2dnoise16into8(uint8_t*, int, int, uint8_t, q44, fract8, int, uint32_t, int, uint32_t, int, uint32_t)':
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:699:106: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q44' {aka 'q<unsigned char, 4, 4>'})
  699 |     fill_raw_2dnoise16into8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, scalex *freq44, y*freq44, scaley * freq44, time);
      |                                                                                                   ~~~~~~ ^~~~~~~
      |                                                                                                   |       |
      |                                                                                                   int     q44 {aka q<unsigned char, 4, 4>}
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:922:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  922 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:923:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  923 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:924:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  924 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:925:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  925 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/noise.cpp:699:132: error: ambiguous overload for 'operator*' (operand types are 'int' and 'q44' {aka 'q<unsigned char, 4, 4>'})
  699 |     fill_raw_2dnoise16into8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, scalex *freq44, y*freq44, scaley * freq44, time);
      |                                                                                                                             ~~~~~~ ^ ~~~~~~
      |                                                                                                                             |        |
      |                                                                                                                             int      q44 {aka q<unsigned char, 4, 4>}
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:922:49: note: candidate: 'uint32_t operator*(uint32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint32_t = long unsigned int]'
  922 | template<class T, int F, int I> static uint32_t operator*(uint32_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:923:49: note: candidate: 'uint16_t operator*(uint16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; uint16_t = short unsigned int]'
  923 | template<class T, int F, int I> static uint16_t operator*(uint16_t v, q<T,F,I> & q) { return q * v; }
      |                                                 ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:924:48: note: candidate: 'int32_t operator*(int32_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int32_t = long int]'
  924 | template<class T, int F, int I> static int32_t operator*(int32_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/lib8tion.h:925:48: note: candidate: 'int16_t operator*(int16_t, q<T, F, I>&) [with T = unsigned char; int F = 4; int I = 4; int16_t = short int]'
  925 | template<class T, int F, int I> static int16_t operator*(int16_t v, q<T,F,I> & q) { return q * v; }
      |                                                ^~~~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
/Users/leo/Documents/Arduino/libraries/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
/Users/leo/Documents/Arduino/libraries/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
/Users/leo/Documents/Arduino/libraries/FastLED/src/platforms/esp/32/clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out`

**Comment by kriegsman** [comment]
Thanks for opening this issue; it'll be good to fix it.  I'll take a look.
