### ISSUE TITLE
Found an exit path from function with non-void return type that has missing return statement

### ISSUE THREAD

**Issue by BCsabaEngine** [FastLED/FastLED#1617]
In file pixelset.h
```
inline CPixelView & fill_solid(const CHSV & color) { if(dir>0) { *this = color; return *this; } }
```

**Comment by samguyer** [comment]
@BCsabaEngine Thanks. I'm surprised we've never seen that error before -- I guess no one ever sets the direction to backwards. :-)

**Comment by BCsabaEngine** [comment]
Platformio code analyzer has dropped this warning. Thanks to solve this.
