### ISSUE TITLE
gradient color palette seems to loop and doesn't loop well

### ISSUE THREAD

**Issue by xgg69** [FastLED/FastLED#1639]
## GRADIENT DEFINITION

```
DEFINE_GRADIENT_PALETTE(purpYey_gp) {
0,   255, 0, 0,  
128,   255, 255, 255,   
255,   0, 255, 0 };

CRGBPalette16 yeyPurp = purpYey_gp;
```

## how i want my gradient to look:

![gradient right](https://github.com/FastLED/FastLED/assets/84851990/1f30b7e4-28d3-42ec-8c07-82b726757f74)

## how it actually looks:

![gradient wrong 2](https://github.com/FastLED/FastLED/assets/84851990/bc96a328-09a3-41cc-8c00-4b5d2a99b52b)

it looks to me like the gradient map is looped from end 255 to start 0 and start color is mixed into the end of the gradient

**Comment by marmilicious** [comment]
The circular blending is by design. If you don't want to blend back to the start color you can stop at index 240. Here's an example: 

https://github.com/FastLED/FastLED/issues/515

https://github.com/marmilicious/FastLED_examples/blob/master/gradient_palette_full_range.ino

**Comment by xgg69** [comment]
found some other issues with the same problem, fixed now :)
