### ISSUE TITLE
2812B LED strip control via photoresistor module

### ISSUE THREAD

**Issue by vadeses** [FastLED/FastLED#1644]
Good afternoon, there is a code that allows you to get the photoresistor value from 0 to 255. Everything is checked through the port monitor mode.

Mapped brightness: 241
Applying brightness: 241
Sensor value: 966

The brightness values are displayed using an analog sensor, but the control of the LED strip itself is not possible using the photoresistor module. When adjusting the brightness in the WLED application using the slider, it does not function correctly. This leads to a conflict between the photoresistor and the application, resulting in the brightness not being regulated by the photoresistor and the LED strip not responding. Could you please tell me where and how I need to configure something in the Wled.h file?

 #include "wled.h"

class UsermodPhotoresistorBrightness : public Usermod {
private:
  unsigned long lastReadTime = 0;
  int sensorPin = A0;  // Пин фоторезистора
  int sensorValue = 0;

public:
  void setup() {
    pinMode(sensorPin, INPUT);
    Serial.begin(115200); // Инициализируем последовательную связь для отладки
    Serial.println("UsermodPhotoresistorBrightness setup complete");
  }

  void loop() {
    if (millis() - lastReadTime > 1000) {  // Читаем значение фоторезистора каждую секунду
      sensorValue = analogRead(sensorPin);
      
      // Маппируем значение фоторезистора на диапазон яркости (0-255)
      int brightness = map(sensorValue, 0, 1023, 0, 255);

      // Выводим значения в монитор последовательного порта для отладки
      Serial.print("Sensor value: ");
      Serial.println(sensorValue);
      Serial.print("Mapped brightness: ");
      Serial.println(brightness);

      // Применяем новую яркость к переменной `bri` в WLED
      bri = brightness;
      applyBrightness();  // Обновляем яркость светодиодов

      // Обновляем время последнего чтения
      lastReadTime = millis();
    }
  }

private:
  // Функция для применения яркости к светодиодам с использованием FastLED
  void applyBrightness() {
    Serial.print("Applying brightness: ");
    Serial.println(bri);
    
    FastLED.setBrightness(bri);
    FastLED.show();
  }
};

// Создаем экземпляр класса
UsermodPhotoresistorBrightness photoresistorMod;

**Comment by zackees** [comment]
Brightness control works in FastLED and this bug relates to client code.
