### ISSUE TITLE
Support issue for the Seeed Studio XIAO nRF52840 Sense 

### ISSUE THREAD

**Issue by kakapo5140cc0** [FastLED/FastLED#1648]
I have tried to edit the fastpin_arm_nrf52_variants.h file an port this specific board (like people did at #747 and #1647) but i still get invalid pin errors like:

error: static assertion failed: Invalid pin specified
static_assert(validpin(), "Invalid pin specified");
error: 'nrf_pin' is not a member of 'FastPin<3>'

Is there somewhere who has this board laying around and can help me out here? My coding experience is very limited, and with the neopixel library it would just become a mess. I really liked working with fastled.
I'm am even willing to finacially compensate you.

**Comment by zackees** [comment]
Neopixel now working in nRF52840 as of today. Upgrade FastLED to 3.7.4
