### ISSUE TITLE
Use 6 way switch to select which color is displayed on WS2812B lights

### ISSUE THREAD

**Issue by rpichler** [FastLED/FastLED#1650]
Hi there, I've got a project where we are using WS2812B strips combined with pressure sensors to tell us levels in some big liquid tanks. I am currently trying to solve 2 problems.
 
1. Colors are not displaying correctly, they seem to be inverted but I haven't had success swapping RGB for GRB in my program, it gives errors.
2. I am trying to use a manual 6 way rotary switch to select the main color that is displaying on the LEDs. My setup in testing is that I have the rotary switch powered and one position is tied to pin 3 on my arduino UNO and another position on the switch is tied to pin 4 on my arduino. The thought is that if I can figure out how to refer to the different pins in my code then I can use that switch, but so far I'm not sure how to refer to those pins.

Attached is the code I'm using and any help would be greatly appreciated. Thanks in advance!

#include "FastLED.h"

#define PIN_SLIDE_POT_A A0 // input pin of the slide pot
#define MAX_SENSOR_VALUE 1000// maximum voltage as analog-to-digital converted value, depends on the voltage level of the VCC pin. Examples: 5V = 1023; 3.3V ~700
#define MIN_SENSOR_VALUE 194

#define NUM_LEDS 300 // add number of LEDs of your RGB LED strip
#define PIN_LED_Pin3 3 // digital output PIN that is connected to DIN of the RGB LED strip
#define PIN_LED_Pin4 4 // digital output PIN that is connected to DIN of the RGB LED strip
#define LED_COLOR CRGB::DarkOrchid // see https://github.com/FastLED/FastLED/wiki/Pixel-reference for a full list, e.g. CRGB::AliceBlue, CRGB::Amethyst, CRGB::AntiqueWhite...
#define LED_COLOR_FULL_Pin3 0,63,12
#define LED_COLOR_FULL_Pin4 255,255,255
#define LED_COLOR_EMPTY CRGB::Green
#define Interval 500

CRGB rgb_led[NUM_LEDS]; // color array of the LED RGB strip

void setup() {
  Serial.begin(9600);
  
  pinMode(PIN_SLIDE_POT_A, INPUT);
  FastLED.addLeds<WS2812B, PIN_LED_Pin3>(rgb_led, NUM_LEDS);  
  FastLED.addLeds<WS2812B, PIN_LED_Pin4>(rgb_led, NUM_LEDS);  
  
  Serial.println("Setup done.");
}

void loop() {
  // 1) Analog value of slide pot is read
  int value_slide_pot_a = analogRead(PIN_SLIDE_POT_A);
  Serial.print("Slide Pot value: ");
  Serial.println(value_slide_pot_a);

  // 2) Analog value is mapped from slide pot range (analog input value) to led range (number of LEDs)
  int num_leds_switchedon = map(value_slide_pot_a, MIN_SENSOR_VALUE, MAX_SENSOR_VALUE, 0, NUM_LEDS);  

  // 3) Light up the LEDs
  // Only LEDs are switched on which correspond to the area left of the slide knob
  for (int i = 0; i < num_leds_switchedon; ++i) {
    rgb_led[i].setRGB(LED_COLOR_FULL_Pin3);
  }  
  // LEDs are switched off which correspond to the area right of the slide knob
  for (int i = num_leds_switchedon; i < NUM_LEDS; ++i) {
    rgb_led[i] = LED_COLOR_EMPTY;
  }
  
  FastLED.show();
  delay(Interval);
}

**Comment by zackees** [comment]
In this example I don't see the color ordering being passed as a template parameter.
