### ISSUE TITLE
stroboscopic effect

### ISSUE THREAD

**Issue by saeedbs** [FastLED/FastLED#1708]
Thanks for this great project

I'm trying to find a way to have stroboscopic effect on pc case fans like this video : [QX fan](https://www.youtube.com/shorts/5xYnWsJUB9E)  or this: [stroboscopic effect ](https://www.youtube.com/shorts/drZOdRXKtfw)
I'm not sure but from my understanding this needs control over light frequency and set it based on fans RPM... is this possible with FastLED? if yes can you give some tips/example about it?

Do you think if it is possible with ws2812b? 

from ws2812 datasheet: 
`Each pixel of the three primary color can achieve 256 brightness display, completed 16777216 color full color
display, and scan frequency not less than 400Hz/s.`    is this frequency that I'm looking for or scan frequency is something else?
I'm no expert at all ...neither in coding nor the physics

**Comment by nomakewan** [comment]
This is the sort of question that would be better suited for the Reddit community: https://www.reddit.com/r/FastLED

The Issues page on Github is for reporting bugs/crashes/etc.

**Comment by saeedbs** [comment]
ok sorry I'm closing this and asking there
