### ISSUE TITLE
PlatformIO cppcheck

### ISSUE THREAD

**Issue by darrenjcosborne** [FastLED/FastLED#1714]
I was just inspecting my PlatformIO project with cppcheck and noticed the following errors:

<img width="1175" alt="Screen Shot 2024-09-15 at 12 54 27" src="https://github.com/user-attachments/assets/1f24d883-842e-4d0c-85ce-81c0a5a21a54">

Can these please be addressed?
Thanks

**Comment by zackees** [comment]
How can I run this myself?

**Comment by darrenjcosborne** [comment]
> How can I run this myself?

PlatformIO Menu -> PIO Home -> Inspect

**Comment by zackees** [comment]
I've re-factored some code from switch statements to template specializations to fix this. If you see any more issues with cpp check then please re-open this bug.

**Comment by darrenjcosborne** [comment]
@zackees, I updated the library to 3.7.7 but the same errors are still present. Can you please re-open this issue?

**Comment by zackees** [comment]
It will be in next week's release, 3.7.8. Try basing your FastLED dependency on the github. We now run cppcheck on every build so this issue has been fixed as far as I can tell.
