### ISSUE TITLE
FastLED Version 3.7.6

### ISSUE THREAD

**Issue by Jpipe001** [FastLED/FastLED#1715]
I am using Fast LED with my Metar Program. see https://github.com/Jpipe001/METAR 
The program is quite big, and I am running out of memory.  Version 3.7.6 pushes the memory over the limit, so I have to use an older version and always get the following messages:

C:\Users\John\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sketch uses 1187865 bytes (90%) of program storage space. Maximum is 1310720 bytes.
Global variables use 65312 bytes (19%) of dynamic memory, leaving 262368 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.6
Serial port COM4

A.  Is there any way to reduce the memory used with the latest version?
B. The Program message " No hardware SPI pins defined.  All SPI access will default to bitbanged output" appears even though I have defined the output pin.
C. The Program message " #pragma message: ". Should read " #Program message: "?

**Comment by zackees** [comment]
Memory usage is going to get worse with 3.7.6 by a little. The RGBW stuff is taking up more memory. Sadly, you may need to pin it until we can make it come back down. The good thing is that selectively forcing -Os using pragma's seems to work well with the RGBW stuff. I'm going to set some time to put that elsewhere. We do have compiled binary size tests to make sure the binary doesn't jump up past 10% of 3.7.4, but that is going to put some people at the limit.

Finding out where the memory is takes object file forensics and is a bit complicated.
