### ISSUE TITLE
ws2811 problem with Arduino DUE

### ISSUE THREAD

**Issue by hamsafar** [FastLED/FastLED#172]
Hi
I want to use FastLED to drive multi chanel of Led strip like MultipleStripsInOneArray.ino.
When I upload it on DUE it dosn't have any output in DUE pins.
I try FastLED2.1,...
please help me

Thanks a lot

**Comment by kriegsman** [comment]
Hi! For general troubleshooting like this, please first ask the question on our G+ discussion group. If it turns into a real library bug, we'll track that ticket here. 

G+ group: http://fastled.io/+

Thanks and welcome!

**Comment by hamsafar** [comment]
Ok thanks
