### ISSUE TITLE
All releases past 3.7.5 are not compiling with ESP32/RMT driver/Espressif 1.0.x

### ISSUE THREAD

**Issue by Jueff** [FastLED/FastLED#1738]
Compiling the Blink sketch fails with **esp_idf_version.h: No such file or directory**

Board: ESP32DevBoard
FastLED: 3.7.8
esp32:esp32: Espressif 1.0.4

Message:
In file included from C:\...\FastLED\src/platforms/esp/32/fastled_esp32.h:12:0,
                 from C:\...\FastLED\src/platforms.h:42,
                 from C:\...\FastLED\src/FastLED.h:68,
                 from C:\...\FastLED\examples\Blink\Blink.ino:5:
C:\...\FastLED\src/platforms/esp/32/clockless_rmt_esp32.h:28:29: fatal error: esp_idf_version.h: No such file or directory
compilation terminated.
exit status 1

**Comment by zackees** [comment]
Weird, is there an alternative to this header?

**Comment by zackees** [comment]
Found the answer. It will be fixed in tomorrow release.

**Comment by zackees** [comment]
Release might be delayed for week.
