### ISSUE TITLE
ESP32-C3 using Master branch FastLED

### ISSUE THREAD

**Issue by CrossRec** [FastLED/FastLED#1748]
``Hello,
I add issues using FastLED V3.7.7 on arduino IDE after compilation OK.
I see on forums that you are actually working on a new release.

I m trying to use the master branch version where i see a green tag for ESP32-C3 (mine is a super mini)
My program contains FastLED (master) and the "me_no_dev" library ESPAsyncWebServer to receive http requests on my ESP32-C3 super mini.

Actually here is what i see on the serial monitor when it s working : 

`Setup init...
IP Address: 192.168.1.108
E (5074) rmt: rmt_new_tx_channel(225): DMA not supported
E (5075) led_strip_rmt: led_strip_new_rmt_device_with_buffer(259): create RMT channel failed
E (5077) rtm_strip.cpp: construct_led_strip failed because of unexpected error, is DMA not supported on this device?: ESP_ERR_NOT_SUPPORTED
ESP_ERROR_CHECK failed: esp_err_t 0x106 (ESP_ERR_NOT_SUPPORTED) at 0x4200f312
file: "c:\Users\dinis\OneDrive\Documents\Arduino\libraries\FastLED\src\platforms\esp\32\led_strip\rmt_strip.cpp" line 85
func: void fastled_rmt51_strip::RmtLedStrip::acquire_rmt()
expressi
abort() was called at PC 0x40387115 on core 0`

2 first lines are Serial prints. After that it shows a register dump and it finishes with : 
`Rebooting...
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40048b82
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0xf64
load:0x403cc710,len:0x73c
load:0x403ce710,len:0x2eb8
entry 0x403cc710`

This is looping infinitely.

If you need me to test something or give you more information, just tell me.

Thanks for your inverstment, i really appreciate.
Regards.

**Comment by zackees** [comment]
Cool, today i learned the C3 does not have DMA. I will issue a fix.

Right now there is a work around for some define that will disable DMA mode explicitly.

You'll find it somewhere in src/platforms/esp/32/led_strip/

I think the file name is defs.h

Look at the define that controls dma and explicitly set it to 0 and your problem should be solved. To respond back and let me know if this is the case.

**Comment by CrossRec** [comment]
Hey ! Thanks for the tip.
I founded this define in defs.h => #define FASTLED_RMT_WITH_DMA
In my source code I add #define FASTLED_RMT_WITH_DMA 0
But unfortunately this doesn't change anythink in the Serial Monitor messages I get .

Regards

**Comment by zackees** [comment]
C3 is really hard to test because it requires me to use a mac, and my dev station is windows.

So I hope you don't mind asking some questions.

What happens if you remove the async web server? Does that change the behavior?

**Comment by zackees** [comment]
No, you can't add it to your source code. You must make it a build level define because it needs to be propagated to the fastled cpp file when it gets compile to its own translation unit

**Comment by CrossRec** [comment]
Hummm Noice ! :D
So I changed the defs.h file to explicitely define FASTLED_RMT_WITH_DMA to 0. It seems to work now. Well done !
To answer your question, before this I commented everything about wifi http server / client requests using these libraries : 
#include <WiFi.h>
#include <HTTPClient.h>
#include <Arduino.h>
#include <AsyncTCP.h>
#include <ESPAsyncWebServer.h>
And the result was the same.

Thanks for your answers, I hope this will help other ESP32-C3 users.
Congratulations !

**Comment by zackees** [comment]
It's also fixed in master now. Glad it worked out for you.
