### ISSUE TITLE
Trying to Compile FastLED for Unit Testing on Linux

### ISSUE THREAD

**Issue by cyon1c** [FastLED/FastLED#1749]
Hi, I have an Arduino PlatformIO project where I'm trying to implement unit testing.

I've abstracted away all arduino based libraries except FastLED, and I'm hoping that I can get pointed to some documentation on how to build FastLED for linux and then point my `native` framework unit tests at the local version compiled for linux. Any guidance would be greatly appreciated.

**Comment by zackees** [comment]
[![unit tests](https://github.com/FastLED/FastLED/actions/workflows/build_unit_test.yml/badge.svg)](https://github.com/FastLED/FastLED/actions/workflows/build_unit_test.yml)
