### ISSUE TITLE
hex and RGB color not the same

### ISSUE THREAD

**Issue by Phil1988** [FastLED/FastLED#175]
I'm sending colors from an Smartphone App to my Arduino.

The color is sand as a hex value.
For example I send the hexValue = 0x123456 (1193046 as dec)

Then I light up the LEDs with that value:
leds[i] = 1193046;

Well I want to be able to save this value, so that the LEDs light up like I set it the last time.
Because each memory adress can hold one byte I save this color value as RGB value.
Color "translation" is done by:
  red = (hexValue >> 16) & 255;  // red
  green = (hexValue >> 8) & 255;   // green
  blue= (hexValue) & 255;        // blue

When I now use:
leds[i].setRGB(red, green, blue); 

The leds turn to a different value.
Especially the darker colors are even darker when I use RGB color.

Whats going on there and how can I prevent it?

**Comment by kriegsman** [comment]
Hi!  Happy to help you get this up and running as desired.  Could I ask you to re-post the question over on the G+ group for FastLED, and I'll answer it there?  I suspect this isn't a library bug, but rather an integer-truncation issue, and it would be helpful for other people to see your question there and how we resolve it.  If it does turn out to be a library bug, we can re-open this ticket and we'll fix it.

The G+ discussion group can be found here: http://fastled.io/+

Thanks!
