### ISSUE TITLE
Wrong led order TM1809

### ISSUE THREAD

**Issue by macnl** [FastLED/FastLED#176]
Anyone ever saw the same?? When i use my TM1809 the led order is not right.
0 (led 3 lights up)
1 (led 2 lights up (as it should be))
2 (the first led lichts up)
3 (led 6)
4 (led 5)
5 (led 4)
is there a way to correct this with fastLED????
RGB order is just right.. its only the chineese wrong wirering (i guess) 

I already figured it out!!

  for( int i = 0; i < NUM_LEDS; i++) 
  {

   //correctie voor foute lichtstrip!!!!
    if (i % 3 == 0)    j=i+2;      // eerste led  moet +2
    if (i % 3 == 1)    j=i;      // klopt
    if (i % 3 == 2)    j=i-2;      // derde led   moet -2
    
    
    leds[j] = ColorFromPalette( currentPalette, colorIndex, brightness, currentBlending);
    colorIndex += 3;
  }

**Comment by focalintent** [comment]
Unfortunately, there's nothing that can easily be done at the library level to fix this.  The code that you have in there, or something along those lines is what you'll have to do (other than poking your led strip supplier to get them to give you something that's better oriented).
