### ISSUE TITLE
[Chore] Large number of warnings w/ 3.9.2 on Mega 2560

### ISSUE THREAD

**Issue by nomakewan** [FastLED/FastLED#1766]
To be clear, FastLED does compile correctly, so this is a chore rather than a bug. But while a lot of the ESP32 compatibility issues were fixed with 3.9.2 (thank you!!), it would appear several parts of the code have functionality specific to other platforms which is either included erroneously, or has individual variables not omitted properly (such as by casting to `void` if on a platform which does not use said variables).

The verbose compile log is attached (error log, even removing non-FastLED-related lines, exceeded the character limit).

[fastled_392_mega2560.txt](https://github.com/user-attachments/files/17609710/fastled_392_mega2560.txt)

The sketch being compiled to generate the above errors can be found [HERE](https://github.com/gpstar81/GPStar-proton-pack/tree/v5.4.Bugfix/source/ProtonPack).

**Comment by zackees** [comment]
Most of them should be fixed now. But there might have been one or two that escaped. CPP check does not catch these so thanks for bringing it to my attention.
