### ISSUE TITLE
docs link on wiki broken (hard coded to older 3.1 version)

### ISSUE THREAD

**Issue by marmilicious** [FastLED/FastLED#1770]
The (hard coded) link on this wiki page need to be updated: 
[https://github.com/FastLED/FastLED/wiki/API-Reference](https://github.com/FastLED/FastLED/wiki/API-Reference)

If it's changed from:
**http://fastled.io/docs/3.1/**

to:
**http://fastled.io/docs/**

then it should simply pickup the latest version.

**Comment by zackees** [comment]
Done
