### ISSUE TITLE
Multiple Strips, Different # LEDs per strip.

### ISSUE THREAD

**Issue by rickvisco** [FastLED/FastLED#1787]
I see examples of how to control multiple LED strips independently, but they only have one parameter for defining the NUM LEDS PER STRIP? What if I want different strip lengths all running independently?

**Comment by marmilicious** [comment]
Hello Rick. Are you looking for something like this?

https://github.com/marmilicious/FastLED_examples/blob/master/multiple_animations_and_strips.ino

We use github "issues" here mostly just for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: https://www.reddit.com/r/FastLED  

If you want to share code please include a link to your code on pastebin.com or gist.github.com
