### ISSUE TITLE
Incorrect "invalid pin" for ESP32-C6

### ISSUE THREAD

**Issue by linhz0hz** [FastLED/FastLED#1788]
Hi, it seems that FastLED checks for pin conflict with pins used for internal flash on ESP32. For ESP32-C6, you have 
`#elif CONFIG_IDF_TARGET_ESP32C6

// GPIO 20-22, 24-26 used by default for SPI flash.
#define FASTLED_UNUSABLE_PIN_MASK (0ULL |  _FL_BIT(20) | _FL_BIT(21) | _FL_BIT(22) | _FL_BIT(24) | _FL_BIT(25) | _FL_BIT(26))
`
in src/platforms/esp/32/fastpin_esp32.h

However, after checking the datasheet more carefully. 
https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf
In page 28 I think they refer to pin number on the package, not GPIO numbers. They are actually GPIO 24-26 and GPIO 28-30. See page 19.

I need to use GPIO 21-22 so I encountered this issue.

**Comment by zackees** [comment]
If you are using platformio set your fastled source to git master to get the fix.

In the meantime you can try the following:

```C++
#define FASTLED_ALL_PINS_HARDWARE_SPI
#include "FastLED.h"
```
And see if that works for you.
