### ISSUE TITLE
Should we move away from the Wiki?

### ISSUE THREAD

**Issue by dmadison** [FastLED/FastLED#1801]
For a long time [the GitHub Wiki](https://github.com/FastLED/FastLED/wiki) was the canonical source of documentation for the library. Unfortunately it has not bee maintained, and portions of it are now significantly out of date. (see #1570, e.g.). Part of the reason for this is because the Wiki is only editable by maintainers, and it is not possible for contributors to submit PRs to modify it.

[FastLED now has a documentation website](https://fastled.io/docs) which is generated by doxygen and automatically updated via GitHub Actions on every release. Because the files used to generate the documentation are on master, in comparison to the Wiki it *is* possible for contributors to submit pull requests to add or change documentation.

I'm wondering if it might be time to leave the Wiki, and collect all of the documentation in one place on the documentation site. Wiki pages that are still relevant can be added via markdown to the [`/docs/`](https://github.com/FastLED/FastLED/tree/master/docs) folder and then included in the Doxyfile. The corresponding Wiki pages can then be changed to "This documentation has moved" links.

#### Pro:
* Documentation is generated automatically
* Documentation can be modified via PR
* All documentation is in one place

#### Con:
* Documentation needs to be regenerated manually (#1791) if it changes between releases
* Existing external Wiki links will require users to click-through to the new website 

Thoughts?

**Comment by zackees** [comment]
Feel free to submit a PR that does this. We only have one contributor.
