### ISSUE TITLE
namespace clash for ArduinoJson and FastLEDs wrapper for wasm

### ISSUE THREAD

**Issue by vortigont** [FastLED/FastLED#1805]
I can find this line `using namespace fl;` in `FastLED.h`
https://github.com/FastLED/FastLED/blob/3bd32773e52f808d9d5f986492c84e5c076fd7c5/src/FastLED.h#L87C1-L87C20

Importing namespace in a header file is so wrong! This results in definition clashing and failure to build units which includes both `FastLED.h` and real `ArduinoJson` lib's header.

i.e. like this:
```
src/embuifs.hpp:29:42: error: reference to 'JsonDocument' is ambiguous

.pio/libdeps/hdwf2_my/FastLED/src/fl/screenmap.h:23:7: note: candidates are: 'class fl::JsonDocument'
   23 | class JsonDocument;
      |       ^~~~~~~~~~~~

.pio/libdeps/hdwf2_my/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:20:7: note:                 'class ArduinoJson::V721PB22::JsonDocument'
   20 | class JsonDocument : public detail::VariantOperators<const JsonDocument&> {
```

this namespace import should be removed from `FastLED.h` or probably exclude bundled ArduinoJson and protect it with some `WASM` definition?
Why to embed a so wide-known and popular lib as ArduinoJson in the first place?

**Comment by zackees** [comment]
good catch on using namespace fl.

That's a bug. I will remove it immediately.

**Comment by zackees** [comment]
As for the embedding json. We have to if we are going to use it internally.

Ancient avr compilers will absolutely chock so i've opted to make it compile optionally with a stub replacement otherwise.

**Comment by zackees** [comment]
Okay fixed. I've also added a test to catch this in there future. Thank you for reporting this bug.

**Comment by vortigont** [comment]
thanks! That was fast!

**Comment by zackees** [comment]
Great! Now I can ship the bug fix.

We are using json to communicate with the web js app when using the wasm compiler.
