### ISSUE TITLE
ERROR: Build for ESP-IDF VSCODE EXTENSION

### ISSUE THREAD

**Issue by ngowangvinh** [FastLED/FastLED#1826]
![image](https://github.com/user-attachments/assets/420d33e5-8bd6-4b4e-a566-84db4a514398)

FastLED version: 3.9.8 (add as dependency component)
ESP-IDF version: 5.3.2
Arduino-esp32 version: 3.1.0 (add as dependency component)
IDE: ESP-IDF vscode extension on windows 10.

**Comment by zackees** [comment]
why is ` -Werror-reorder` enabled on your build? Is this the default?
