### ISSUE TITLE
random8(uint8_t lim) less flash than random8()

### ISSUE THREAD

**Issue by NicoHood** [FastLED/FastLED#187]
I just noticed that if I pass an argument to the random8() function my sketch takes less flash. The weird thing is that the function with an argument has more instructions.

An example can be found here, feel free to change the chipset for faster compiling.
https://gist.github.com/NicoHood/0ed4d54b5eb90f835549#file-fibonacci_music_demo-ino-L213

In a normal example, like the blink sketch it does not take less flash. Any ideas why this could happen? Because of the inlining?

**Comment by focalintent** [comment]
It could be because of the inlining.
