### ISSUE TITLE
getMaximumLight( ) function?

### ISSUE THREAD

**Issue by NicoHood** [FastLED/FastLED#190]
It would be nice to have a function that outputs the maximum light of a channel.
I am using HSV values where at least one channel is at maximum brightness. Then  I dim them down, so I need to know how far I've dimmed them. This way you can simply use the highest value.

```cpp
    inline uint8_t getMaximumLight( uint8_t limit = 255 )  {
        uint8_t max = red;
        if( green > max) max = green;
        if( blue > max) max = blue;
        return max;
    }
```

An equivalent with minimum would be nice as well.

Or am I wrong and this already exists?

**Comment by kriegsman** [comment]
Yep, I see what you mean there.  I'll consider it for future inclusion; I'm closing the ticket because it's not a "bug" to fix here.
