### ISSUE TITLE
Connect 2 APA102 strip on DUE

### ISSUE THREAD

**Issue by aloniba** [FastLED/FastLED#194]
Hi,

How Can I connect 2 APA102 strips on arduino DUE .
I need to control each strip separate (NOT in parallel) in high speed 

Can any one help me with some demo script code?

Thank's

**Comment by kriegsman** [comment]
Hi and welcome!  Please ask your question on the FastLED discussion group here: http://fastled.io/+ 
There are lots of helpful folks over there, and we use this github issue tracker just for library bugs.
Thanks.
