### ISSUE TITLE
Bug in fill_gradient_RGB, swapping end and start points done incorrectly?

### ISSUE THREAD

**Issue by bourkemcrobbo** [FastLED/FastLED#195]
I was reading through this code at lines 67-76 in colorutils.cpp;
{
// if the points are in the wrong order, straighten them
if( endpos < startpos ) {
    uint16_t t = endpos;
    CRGB tc = endcolor;
    startpos = t;
    startcolor = tc;
    endcolor = startcolor;
    endpos = startpos;
}

and to me it seems to set the start position to the end position, and then set the end position to the start position, which was just set as the end position. Both start and end positions look like they will be set to the same value.

I'm at uni, so can't test this on my hardware. I may have made a mistake in my reading, but I don't think I have

**Comment by kriegsman** [comment]
Yep- looks like a plain, old-fashioned Oops.  I'll fix it.

**Comment by kriegsman** [comment]
Thanks for the bug report; good spotting.
