### ISSUE TITLE
Question: Does FastLED disable interupts?

### ISSUE THREAD

**Issue by Bronzen** [FastLED/FastLED#208]
Hi, 

I'm working with a speaker that uses Tone() and I need a LED library that can work with Tone(). 
As Tone() relies on timer interrupts to generate the tones, other LED libraries will not work because they will disable interrupts when writing to pixel.

Just wondering will FastLED work in my case?

Speaker: http://www.seeedstudio.com/depot/Grove-Speaker-p-1445.html
LED strip model: WS2812B

Thank you

**Comment by kriegsman** [comment]
Hi!  I just answered this question over on G+: https://plus.google.com/u/0/+CelestaleOfficial/posts/BTQDkQ5BAL7 
Hope that helps!

**Comment by kriegsman** [comment]
(And in general, we use this issue tracker for bugs.  For questions and how-to help, try the Google Plus group for FastLED: http://fastled.io/+ )
