### ISSUE TITLE
Example code standardization

### ISSUE THREAD

**Issue by cneuzil** [FastLED/FastLED#212]
This is probably a minor problem, but I noticed the examples have different names for variables.  Some have DATA_PIN, some have LED_PIN.  Likewise for LED_TYPE and CHIPSET, CLK_PIN and CLOCK_PIN.  NUM_LEDS seems to be consistent.

The first thing I do when I get a new board and LEDs is run blink, then I run other examples like cylon to verify everything works.  If I just copy/paste the variables, I get errors because the variable names don't match.

This is kinda minor, but maybe helpful to get fixed for beginners setting up their projects.

**Comment by kriegsman** [comment]
We just did a bit of code cleanup on the examples; closing this old ticket, and thank you for the report (way back when!)
