### ISSUE TITLE
TM1812 support

### ISSUE THREAD

**Issue by ivan-mlnn** [FastLED/FastLED#221]
Your library works great with chips TM 1812 if you specify the type TM1809 chip.
The only difference is in the number of diodes on the chip 3 to 4, but the data stream there is no difference.
And the same timings in fast mode.
I have successfully tested most of the examples from the library using the Arduino and the stripe on the TM1812 chip.
Sorry for my English, I used google.translate
![wp_20151025_002](https://cloud.githubusercontent.com/assets/4255280/10717770/1c739c26-7b73-11e5-82a4-8b1ae267d471.jpg)
![wp_20151025_003](https://cloud.githubusercontent.com/assets/4255280/10717768/1c728ca0-7b73-11e5-9732-b426f94ab3a3.jpg)
![wp_20151025_004](https://cloud.githubusercontent.com/assets/4255280/10717767/1c719444-7b73-11e5-877a-80cde2e33f81.jpg)
![wp_20151025_005](https://cloud.githubusercontent.com/assets/4255280/10717769/1c7299fc-7b73-11e5-9650-c10d7081c085.jpg)

**Comment by focalintent** [comment]
Thank you for the report!  I'll check in a chip definition for TM1812 that uses the TM1809 definitions.
