### ISSUE TITLE
How to handle multiple NeoPixel types

### ISSUE THREAD

**Issue by DouglasUrner** [FastLED/FastLED#231]
According to my experience and Adafruit's product information, there are at least two types of NeoPixels with different color orders. The most recent batch that I got are in RGB order, so:

    FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);

Results in the wrong color order.

It is easy enough to fix it by changing the definition of NEOPIXEL or by using the WS2811 definition instead – but it seems like the current approach of having a NEOPIXEL type isn't sufficient. Perhaps there should be a NEOPIXEL_GRB and a NEOPIXEL_RGB?

**Comment by focalintent** [comment]
NEOPIXEL is just WS2812 locked to a GRB order (since that's the ordering that most neopixels from Adafruit time were shipping with.  If you need to change the color order just use WS2812 instead of NEOPIXEL.
