### ISSUE TITLE
Phantom FastLED.show()

### ISSUE THREAD

**Issue by ottojas** [FastLED/FastLED#242]
Following code blinks leds without explicitly calling FastLED.show().
Either undocumented feature or bug?? I am a newbie to FastLED.
This code is running on a teensyLC.  It is compiled with arduino 1.6.6

 
[TEMP.txt](https://github.com/FastLED/FastLED/files/72505/TEMP.txt)

**Comment by focalintent** [comment]
FastLED.delay calls show - as does clear.

**Comment by ottojas** [comment]
Thanks for info..

Your library is super.  Well designed.  I just recently got involved in
Smart LEDS.  Was delighted to find this.  Sorry to have jumped the gun
on bug/feature report.

regards Otto

**Comment by focalintent** [comment]
No worries!  I hope you make wonderful things - feel free to ping here or the g+ group for help (or to show off what you make :)
