### ISSUE TITLE
Error Compiling for ATtiny - "'Serial' was not declared in this scope"

### ISSUE THREAD

**Issue by Intechgreater** [FastLED/FastLED#247]
Getting the output below when attempting to compile for ATtiny85 bare, Adafruit Gema and Trinket in Arduino IDE 1.6.5 R5, ZIP version.

![attiny compile error](https://cloud.githubusercontent.com/assets/10334392/12374603/99775dca-bc6e-11e5-81fe-7a85254eaaf9.png)

**Comment by Intechgreater** [comment]
Is dump() in pixelset.h for debugging? With everything relying on Serial.print() commented out, my sketch compiles.

void dump() const {
    /*
    Serial.print("len: "); Serial.print(len); Serial.print(", dir:"); Serial.print((int)dir);
    Serial.print(", range:"); Serial.print((uint32_t)leds); Serial.print("-"); Serial.print((uint32_t)end_pos);
    Serial.print(", diff:"); Serial.print((int32_t)(end_pos - leds));
    Serial.println("");
    */
}

**Comment by NicoHood** [comment]
Probably add
```
void dump() const {
#ifdef SERIAL_PORT_MONITOR
Serial.print("len: "); Serial.print(len); Serial.print(", dir:"); Serial.print((int)dir);
Serial.print(", range:"); Serial.print((uint32_t)leds); Serial.print("-"); Serial.print((uint32_t)end_pos);
Serial.print(", diff:"); Serial.print((int32_t)(end_pos - leds));
Serial.println("");
#endif
}
```

https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/standard/pins_arduino.h#L233

**Comment by Intechgreater** [comment]
Thanks NicoHood, that works.

**Comment by focalintent** [comment]
Whoops - this shouldn't have gotten committed in the first place - yanked out.
