### ISSUE TITLE
typo in new ESP8266 implementation?

### ISSUE THREAD

**Issue by m0bygit** [FastLED/FastLED#249]
@focalintent Is it supposed to be 116? Just thought it looked odd. :-)

https://github.com/FastLED/FastLED/blob/5dff1f475f4ed7895d6ac7bdd8427c5507543380/platforms/esp/8266/fastpin_esp8266.h#L36

**Comment by focalintent** [comment]
Ah yeah - minor thing - nothing critical uses it.
