### ISSUE TITLE
Extend parallel-output support for ESP

### ISSUE THREAD

**Issue by NeoBelerophon** [FastLED/FastLED#256]
It would be nice if the parallel-output could be extended for esp. 
Running it in over-clocked mode should be fast enough to manage it also in bit bang mode?

**Comment by focalintent** [comment]
More likely for the next esp platform than the 8266   (There's a couple other platforms that are in line to get parallel output first).

**Comment by focalintent** [comment]
Code complete on this - but it needs to be tested before I push it to the world.  Unclear how well it will work at 80Mhz, it may require 160Mhz to do it's thing.

**Comment by focalintent** [comment]
Gyah - the GPIO management and layout of the ESP8266 is a nightmare for getting this to work.  It will likely only work on 4 pins once I'm finished with it.
