### ISSUE TITLE
no matching function for call to 'CLEDController::show(uint8_t&)'

### ISSUE THREAD

**Issue by tljesse** [FastLED/FastLED#259]
I am trying to get the library to work with multiple strips and [manage your own output](https://github.com/FastLED/FastLED/wiki/Multiple-Controller-Examples#managing-your-own-output) but when compiling I am getting this error:

no matching function for call to 'CLEDController::show(uint8_t&)'

and this is how I have it set up

CLEDController *controllers[NUM_STRIPS];
uint8_t max_bright = 255;

controllers[0] = &FastLED.addLeds<TM1803, 1>(leds, numLeds[0]);

controllers[strip]->show(max_bright);

**Comment by focalintent** [comment]
Ah - I hadn't realized I had documented how to manage individual objects directly (I was avoiding doing it for a long time because that portion of the API was about to undergo a major overhaul, which it has just done).

The line you want instead is:

```
controllers[strip]->showLeds(max_bright);
```

I'll update the wiki page.
