### ISSUE TITLE
Cylon demo - DATA_PIN not in code

### ISSUE THREAD

**Issue by TheAustrian** [FastLED/FastLED#260]
Hi! I tried some of the demos today and while most worked the Cylon demo seemed to crash my ESP8266 dev board since after the upload the strip didn't light up and the onboard led was on constantly (it's on pin 2).

It appears pin 2 is hardcoded into the demo instead of taking the DATA_PIN variable.

The line in the code reads:
LEDS.addLeds WS2812,2,RGB (leds,NUM_LEDS);
when it should probably be:
LEDS.addLeds WS2812, DATA_PIN,RGB (leds,NUM_LEDS);

(Or even better the LED type should be defined at the start, too, and referenced in the code by the variable name.) 

EDIT: had to remove the <>

**Comment by focalintent** [comment]
Personally, I'm actually not a fan of defining the led type with a #define - and intentionally leave some of the demos without that to show it off.  I will fix cylon to work off the DATA_PIN #define, however.
