### ISSUE TITLE
#error "XTENSA-architecture microcontrollers are not supported."

### ISSUE THREAD

**Issue by axwell** [FastLED/FastLED#264]
Hello,
i'm trying to use FastLed with node mcu 1.0 but i get the errors bellow:

FastLED/led_sysdefs.h:22:2: error: #error "XTENSA-architecture microcontrollers are not supported."
FastLED/platforms.h:22:2: error: #error "XTENSA-architecture microcontrollers are not supported"

I'm using:
http://arduino.esp8266.com/stable/package_esp8266com_index.json

Thanks.

**Comment by focalintent** [comment]
You need to get the latest version of the library directly from githib - https://github.com/FastLED/FastLED
