### ISSUE TITLE
Small issue with CRGB::colors on WS2812B (and others?)

### ISSUE THREAD

**Issue by arduinium** [FastLED/FastLED#267]
Hello, I'm a new user of this very nice library,

I just received some WS2812B LEDs from ebay, and just finished to wire one of them, so I tried the Blink example.

Of course I uncommented the line for the WS2812B, and commented the other one.

But, the LED is green instead of red. To fix it I had to change to GRB in this line:
```
FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS);
```

Is it normal or is it a bug ?

Thanks :)

**Comment by TheAustrian** [comment]
This is normal and depends on the led strip.

**Comment by arduinium** [comment]
Thanks, case solved :)
