### ISSUE TITLE
Random8() errors

### ISSUE THREAD

**Issue by jpro56** [FastLED/FastLED#277]
Recently fetched latest FastLED version in Master and found that code running OK before froze and traced the problem to a line simulating a dice throw...       dice = random8(6)+1;

Now I occasionally get a 7 back from that line !? 
Temporarily replaced the line with Arduino random() and it works ok !

Running Arduino 1.6.7 and Teensyduino 1.27 on a Teensy 3.1

**Comment by focalintent** [comment]
Ah!

random8() was taking advantage of a quirk in scale8 where scale8(x,y) would give you values in the range [0,y-1].  However, i have since fixed scale8 - so now the range is going to be [0,y] - leading to what you're seeing here.  I'll get a fix put in unless @kriegsman gets to it first.
