### ISSUE TITLE
SAM D20 Support

### ISSUE THREAD

**Issue by xxrxndxvxs** [FastLED/FastLED#28]
Sure would be cool to have SAM D20 support! :-)

http://www.atmel.com/microsite/samd20/

**Comment by focalintent** [comment]
FastLED will eventually support the D21 in the arduino zero.  Unlikely to add D20 support at this point.

**Comment by xxrxndxvxs** [comment]
That's cool. They are essentially the same IIRC, the D21 included usb support natively.
