### ISSUE TITLE
ESP8266 "XTENSA-architecture microcontrollers are not supported"

### ISSUE THREAD

**Issue by wolfcry0** [FastLED/FastLED#289]
Hello I'm trying to use the FastLED library on an ESP8266 and it's throwing an error: "XTENSA-architecture microcontrollers are not supported"

[Raw error paste](http://pastebin.com/6utGvXng)

Arduino 1.6.8
ESP8266 2.1.0
FastLED 3.1.0

Is there a fix for this error out there that I can do?

**Comment by kriegsman** [comment]
Hi! Initial aupport for the ESP8266 can be found on the "head" of the FastLED master branch at github, which is newer than the "3.1" release. It works reasonably well; Daniel and I used it this very weekend!
