### ISSUE TITLE
 support sk9822

### ISSUE THREAD

**Issue by vixns** [FastLED/FastLED#291]
Is sk9822 supported ?

vendors claim they are compatible with APA102, but according http://www.szledcolor.com/newsshow.asp?sid=1&id=199, 

"So what is the difference ? you know the first signal is different , normally the first signal ,sk9822 is a base Synchronization signal, and APA102 don't"

http://www.szledcolor.com/download/SK9822%20LED.pdf

**Comment by focalintent** [comment]
The difference is that the SK9822 latches a frame differently than the APA102 - I'm about to check in an SK9822 definition that does the Right Thing™ with SK9822 leds.

**Comment by 00fractal** [comment]
Greetings! 


Ithink you'll be happy  to  read  that  amazing article I've just found  on the web, here it is  <http://quality.greatmalaysia.com/e4hbdh>

Later, richard

78485111
