### ISSUE TITLE
Arduino M0 / M0 Pro Support

### ISSUE THREAD

**Issue by Shajariel** [FastLED/FastLED#292]
Hi i have testet my Fast LED scripts the new M0 Pro (similar to the Zero Pro) and the script is not working.
Must this M0 Pro board specially implimentet to work with FastLED ?

**Comment by focalintent** [comment]
What board are you selecting in the IDE, and what version of the arduino ide (and boards) are you using?

In theory, this board should be treated identically to the arduino zero.

**Comment by focalintent** [comment]
closing this, since there's been no response on my questions.
