### ISSUE TITLE
Allow duplication of data to more LEDs

### ISSUE THREAD

**Issue by focalintent** [FastLED/FastLED#3]
https://code.google.com/p/fastspi/issues/detail?id=41

I want to drive a lot more LEDs than I have RAM for. It would be useful to me to be able to describe some LEDs in the normal fashion, but then have a variation of the Show() method that sends all of the data out multiple times, so I could repeat the pattern I've defined an arbitrary number of times.

**Comment by jjggbb** [comment]
I am having the same issues.  Was this implemented?  I was looking at the showPixels function in dmx.h.  It looks like there is a pointer that could be reset and then the data could be repeated any number of times.  I have some programming experience but I am very noob to Github and dont have experience with c++.  How could the pointer be reset?
