### ISSUE TITLE
Addressable LED Recommendation, instead of WS2812

### ISSUE THREAD

**Issue by vinimendes3** [FastLED/FastLED#300]
Today we're using WS2812, but **noInterruptions()** made our code not work properly.

Reading issues, we've noticed that the best solution for this would be to use another addressable LED with clock control.

Reading Fast LED description we've noticed that there are some supported LEDs with clock control, but either are not in stock, or are sold only in strips.

Which LED would you recommend for us with clock control and at the same time in stock somewhere?

**Comment by focalintent** [comment]
APA102, LPD8806, and WS2801 - all of which are available in various forms at aliexpress.com - and please limit this to bug/issue reporting and conversation/question asking to the g+ group - http://fastled.io/+
