### ISSUE TITLE
Random warning

### ISSUE THREAD

**Issue by dopesong** [FastLED/FastLED#307]
What's the point of this warning?
https://github.com/FastLED/FastLED/blob/c2e9896f02497659f12dd4fb0486590908815d5a/FastLED.h#L12

My IDE also points on it at tells me to take a look into it every time.

**Comment by focalintent** [comment]
So that when people send me build logs I can see exactly what version they have/are building with (useful in cases where the have multiple versions installed).  At some point I'll replace it with a pragma message.

**Comment by dopesong** [comment]
pragma message much better option :)

**Comment by focalintent** [comment]
And is also not available on all the versions of gcc the library has been compiled/used with.
