### ISSUE TITLE
Please make Teensy's default hardware SPI 12 Mbit/sec

### ISSUE THREAD

**Issue by PaulStoffregen** [FastLED/FastLED#314]
Many LED strips can't handle 24 MHz speed well.

APA102 in particular causes the clock pulse width to shorten slightly after each LED as it "regenerates" the clock signal.  After 100 to 200 LEDs, probably often occur with 24 MHz speed because the pulse width has become too narrow.

12 MHz would give much better out-of-the-box experience.  It should also cut down on a common support request.  People who really want higher performance could always edit the code to try 24 MHz with their LEDs.

**Comment by focalintent** [comment]
It's not the APA102 chip itself - it's something about the strips - i have a 768led APA102 board that I can run at 24Mhz without any problems.  (That said, I thought I did drop the default down to 12Mhz at some point)

**Comment by PaulStoffregen** [comment]
Oh, maybe I've got an outdated copy in Teensyduino.

I'm updating now to the lastest.  Is the master branch currently the best for Teensy?  Previously I was pulling from a Teensy-specific branch.

**Comment by PaulStoffregen** [comment]
Thanks :)
