### ISSUE TITLE
Arduino Micro & WS2812B

### ISSUE THREAD

**Issue by OhhConti** [FastLED/FastLED#320]
HARDWARE : Arduino Micro
                      WS2812B + Power Supply 5V
IDE : Arduino 1.6.9
SKETCH:
`
#include <Adafruit_NeoPixel.h>         // Include Adafruit NeoPixel library
#define PIN            11             // LED on digital pin 6
#define NUMLEDS        17               // Use total of 1 LED

// Create 'leds' object to drive LEDs
Adafruit_NeoPixel leds = Adafruit_NeoPixel(NUMLEDS, PIN, NEO_GRB + NEO_KHZ800);

int wait = 5;                         // Standard wait delay of 5 milliseconds 

void setup() {
  leds.begin();                       // Initialize 'leds' object

  //Make sure LED is off to demonstrate start of sketch
  leds.setPixelColor(0, leds.Color(0, 0, 0));  // Turn off LED
  leds.show();                        // Set new value
  delay(500);
  Serial.begin(9600);
  
}

// Loop through changing R, G, and B colors
// Each color fades in from off (i=0) to fully on (i=255)
void loop() {
  leds.setPixelColor(2,255,0,255);
  leds.show();
  delay(3000);
  Serial.println("ok");
  //digitalWrite(PIN,LOW);
  
}`

I've connected the Pin 11 of the Arduino Micro to the WS2812B's data wire, but during the execution of the program nothing happens.

**Comment by kriegsman** [comment]
Hi-  Are you using the FastLED library?  From this code it looks like you're using the AdaFruit library.
If you are using the FastLED library, and you have general troubleshooting problems like this, try our Google+ group which can be found here http://fastled.io/+
(We keep the github trouble tickets here exclusively for 'bugs in the library itself'.)
