### ISSUE TITLE
Having Trouble with losing Serial Data.  Interrupts?

### ISSUE THREAD

**Issue by Menketronics** [FastLED/FastLED#325]
My project is to send RGB values from my Raspberry Pi to a WS2811 strip controlled by Arduino Uno.  I have tried sending the values through a USB cable but I am losing data.  The code I was running on the Arduino Uno is below.  I read this article but I am confused.  https://github.com/FastLED/FastLED/wiki/Interrupt-problems

Is there some other way I can send RGB values to the Arduino?  Perhaps send first from Pi through serial to another Arduino and then through SPI or I2C to the Arduino controlling the LED strip?

Here is my code.:

```
#include <Arduino.h>
#include "FastLED.h"

#define NUM_LEDS 100

#define DATA_PIN 7

String receivedLine = "";
String command = "";
String redValue = "";
String greenValue = "";
String blueValue = "";
int red = 0;
int green = 255;
int blue = 0;

CRGB leds[NUM_LEDS];

void setup(){
  
  FastLED.addLeds<WS2811, DATA_PIN, BRG>(leds, NUM_LEDS);
  Serial.begin(9600);
  
}

void loop(){

  
  if (Serial.available()) {
    
    receivedLine = Serial.readStringUntil('.');

    Serial.println(receivedLine);
    
    
    command = receivedLine.substring(0,3);
    
   
    
    redValue = receivedLine.substring(4,7);
    red = redValue.toInt();

    greenValue = receivedLine.substring(8,11);
    green = greenValue.toInt();

    blueValue = receivedLine.substring(12,15);
    blue = blueValue.toInt();

    
  } 
       for (size_t i = 0; i < NUM_LEDS; i++) {
    leds[i].r = red;
    leds[i].g = green;
    leds[i].b = blue;

    FastLED.show();
    
  }
  
}

```

**Comment by kriegsman** [comment]
Hi! And welcome -- we're happy to help answer questions like this over on the FastLED Google Plus group at http://FastLED.io/+
(We deserve this github ticket system for bugs in the library, and use google plus for project and programmibg help)
