### ISSUE TITLE
Change color order and LED Nums

### ISSUE THREAD

**Issue by hamsafar** [FastLED/FastLED#326]
Hi
How can change color order and LED nums when controller is running?
Regards.

**Comment by kriegsman** [comment]
Hi and welcome!
For performance reasons, those settings are "compiled in" and are not changeable at runtime. 
Other people have come up with work arounds, so you might want to ask your question on our Google Plus group at http://FastLED.io/+ 
I suspect you'll get a good discussion going there. (We like to reserve these github tickets for bugs in the library itself.)
Closing this, see you over on the Google Plus group!
