### ISSUE TITLE
WS2813_PORT* undefined in FastLed.h

### ISSUE THREAD

**Issue by gguuss** [FastLED/FastLED#330]
Configuration
----------------
* ESP8266 board
* FastLed 3.1
* ESP8266 community version 2.1.0 or 2.2.0

Issue:
----------------
FastLed does not compile without commenting out all lines starting with WS2813_PORT:

e.g. lines 402, 411, 418, 425 need to be commented out because WS2813_PORTA,  WS2813_PORTB, WS2813_PORTC, WS2813_PORTD are not defined.

**Comment by focalintent** [comment]
Checked in a fix for this last night (the person who submitted the pull for 2813 support missed some things)
