### ISSUE TITLE
Const qualifier not present on non-mutating functions

### ISSUE THREAD

**Issue by kavika13** [FastLED/FastLED#332]
I don't know how deep this issue is (I suspect it is missing from several places in the library, not just a single object).

I tried calling `lerp8` on a `const CRGB` object just now, and it wouldn't compile.

If you change `CRGB::lerp8` to this signature, the problem should clear up:

```
inline CRGB lerp8( CRGB & other, fract8 frac) const // <-- Notice `const` here
{
    // ...
```

**Comment by focalintent** [comment]
Pull request merged, closing this issue.
