### ISSUE TITLE
NodeMCU with FastLED

### ISSUE THREAD

**Issue by beebrain** [FastLED/FastLED#342]
I tried to use FashtLED and I got error many time.
I read and follow instruction. 
I got this error message 
C:\Users\Boobeejung\Documents\Arduino\libraries\FastLED-3.1.0/led_sysdefs.h:22:2: error: #error "XTENSA-architecture microcontrollers are not supported."
 #error "XTENSA-architecture microcontrollers are not supported."

I installed last version FastLED library it's version 3.1 and update package esp8266 board in arduino IDE 
in figure 

![image](https://cloud.githubusercontent.com/assets/10016227/18283546/fd4dce36-748f-11e6-97b1-260216eef0bc.png)

How to fix it??

**Comment by focalintent** [comment]
You need to get the most recent version of the library's master branch on GitHub.
