### ISSUE TITLE
Problem with IC SM16703P

### ISSUE THREAD

**Issue by vecio88** [FastLED/FastLED#345]
Hi, 
i have a problem with my strep led with IC SM16703P. THis IC not is between the supported chipsets. I have tried to use other chipset but not work well. For example, if i run the example "FirstLight" on the strip , the led turn on in random mode and not with a sequence how is wrote in the code.

how can i solve?

thanks

**Comment by focalintent** [comment]
The SM16703P is not a supported chipset, I will have to add support for it at some point in the future.

**Comment by makenb** [comment]
+1 for sm16703, please, please, please
Thanks

**Comment by kdauzickas** [comment]
+1 seems to be same as ws with a bit different timing

**Comment by CCERocks** [comment]
+1 for sm16703

**Comment by genkagen** [comment]
+1 for sm16703 also sm16723P(Iout:12mA), thanks!

**Comment by Agent-3P1C** [comment]
Has the chip been added since?
If not: are there other libaries that can be used?
Thanks

**Comment by focalintent** [comment]
It has not been added yet - I don’t know if there are other libraries for it or not.

**Comment by makenb** [comment]
SM16703 is supposed to be compatible with ws2811 which is supported, how ever has slightly different timing requirements. here is a link to a discussion about the differences that may be helpful: 
[http://falconchristmas.com/forum/index.php?topic=5336.0](url)

**Comment by shd7899** [comment]
Could not find any working SM16703 Arduino library. It's rather a chip in demand. No idea why some far east LED manufacturers claim that its protocol is compatible with ws2811.

**Comment by Talamis** [comment]
+1 for sm16703

**Comment by surik00** [comment]
Wow, it's been more than 2 years and still no support for SM16703

**Comment by focalintent** [comment]
That’s because major work on the library stopped about two years ago because of this - https://plus.google.com/102282558639672545743/posts/JQKcujjaXXC - and no one has submitted a PR for 16703 support.

**Comment by galgametentacle** [comment]
My 16703 is workable with WS2811 settings. It says 'CC16703 184508' on chip. Maybe from a China Factory.

**Comment by kingnoss** [comment]
I have the cc16703 chip and my work around is using Adafruit Neopixel at 400KHz, and it works like a charm. I got a RF controller with my strip, but where is the fun in that.

**Comment by NilsNippe** [comment]
For anyone looking for a solution: use the WS2811_400 led type.

FastLED.addLeds<WS2811_400, DATA_PIN, RGB>(leds, NUM_LEDS);

**Comment by ahmetcemturan** [comment]
HAs anyone been able to run a strip with the SM16703 chipset yet?  It just does not work..
