### ISSUE TITLE
"function was not declared in this scope"-error

### ISSUE THREAD

**Issue by dumbSail** [FastLED/FastLED#347]
1.6.11, issue with 

```
void setup() {
}
void loop() {
  myfunc();
}
void myfunc() {
}
```

y:4: error: 'myfunc' was not declared in this scope

exit status 1
'myfunc' was not declared in this scope

**Comment by kriegsman** [comment]
This is a general Arduino builder problem, not really a FastLED problem.  The simplest solution is to move the definition of "myfunc" to a place in the code that comes before it is called.  So just try moving myfunc up above loop.
