### ISSUE TITLE
Add basic XY matrix support

### ISSUE THREAD

**Issue by kriegsman** [FastLED/FastLED#35]
Add support for basic XY operations, including both plain "row order" matricies, and "row prime order" aka serpentine aka boustrophedon layouts.

**Comment by jasoncoon** [comment]
This is possible using the kMatrixSerpentineLayout variable in the XYMatrix demo: https://github.com/FastLED/FastLED/blob/master/examples/XYMatrix/XYMatrix.ino

Another option is this library used with FastLED: https://github.com/AaronLiddiment/LEDMatrix

**Comment by Jorgen-VikingGod** [comment]
If you are interested also in bigger matrix displays (also with multiple tiles) - you can use my fork of Aarons LEDMatrix class:
https://github.com/Jorgen-VikingGod/LEDMatrix

**Comment by marcmerlin** [comment]
and now you can also use my Adafruit Neomatrix port to FastLED: https://github.com/marcmerlin/FastLED_NeoMatrix
