### ISSUE TITLE
Compiler error: error: 'calculate_max_brightness_for_power_mW' was not declared in this scope

### ISSUE THREAD

**Issue by tgiphil** [FastLED/FastLED#352]
````
FastLED.h: In member function void CFastLED::setMaxPowerInMilliWatts(uint32_t)
 
FastLED.h: 466:77: error: 'calculate_max_brightness_for_power_mW' was not declared in this scope
   inline void setMaxPowerInMilliWatts(uint32_t milliwatts) { m_pPowerFunc = &calculate_max_brightness_for_power_mW; m_nPowerData = milliwatts; }
`````

**Comment by focalintent** [comment]
What version of arduino are you using, what version of the library do you have, and what hardware are you compiling for, and what is the code you are trying to compile?

**Comment by tgiphil** [comment]
I figured out the issue. When add a library with Arduino IDE for Visual Studio, it adds includes for all the header files when only FastLED.h is necessary.

The resolution was to remove all the references to the other header files. 

Btw. Great project! Keep up the great work!
