### ISSUE TITLE
Allow setting brightness for a led range

### ISSUE THREAD

**Issue by binloan** [FastLED/FastLED#358]
The `FastLED.setBrightness(uint8_t val)` method is handy, but would be even more interesting if it was able to set a brightness limit to only parts of a led strip. E.g, `FastLED.setBrightness(uint8_t val, uint8_t start, uint8_t length)`.

**Comment by kriegsman** [comment]
That sounds more like actually modifying the data in the buffer than adjusting the master brightness of the strip.  While what you're suggesting is possible, it would require (precious) additional RAM and CPU cycles. 

I'm going to close this ticket, but it's probably worth asking on our Google Plus group if anyone has simple existing code to do what you're thinking. 

Thanks for using the library!
