### ISSUE TITLE
Rev 3.1.3 dosen´t work on Digispark and  Arduino / Adafruit Gemma

### ISSUE THREAD

**Issue by volvodani** [FastLED/FastLED#359]
I worked with Arduino Rev. IDE 1.6.5 and 1.6.12 and DigiSpark and Arduino/Adafruit Gemma to drive WS2812B single LEDs and Strips. With 3.1 there are no error during compiling and after uploading it works on every pin. But  with 3.1.3 i get a mess of error messages (something with SPI) an i can´t upload the programm

**Comment by focalintent** [comment]
Closing this - if you're still having problems open a new issue, and include the full build output as well as the code you're tyring to compile.
