### ISSUE TITLE
Invalid duration of first delay() after FastLED.show() on Particle Photon

### ISSUE THREAD

**Issue by aboyett** [FastLED/FastLED#366]
I'm having trouble with FastLED 3.1.5 on a Particle Photon (firmware version 0.5.3) with a 12 LED Neopixel (WS2812) ring. This may be the same or a similar issue to #299.

It looks like the first `delay()` call after a call to `FastLED.show()` ends up being cut short (or skipped entirely) but every so often will last for the requested duration. A second `delay()` after the first runs for the requested duration.

This short sample program is able to reproduce the issue consistently for me and has been tested against two different Photons.

```
// This #include statement was automatically added by the Particle IDE.
#include "FastLED/FastLED.h"
FASTLED_USING_NAMESPACE;

// How many leds in your strip?
#define NUM_LEDS 12
#define DATA_PIN 3

// Define the array of leds
CRGB leds[NUM_LEDS];

int count = 0;
String msg;

void pauseAndLog(String color, int numPause = 1, int duration = 1000) {
    msg = String(count) + "  " + String(millis()) + "  " + Time.timeStr();
    Serial.println(color + " " + msg);
    for(int i = 0; i < numPause; i++) {delay(duration);}
}

void setup() {
    Serial.begin(115200);
    delay(15000); // pause allow attaching to console before messages are printed
    FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);
    Serial.println("Starting firmware.");
}

void loop() {
    leds[0] = CRGB::Red;
    FastLED.show();
    pauseAndLog("red  ");

    leds[0] = CRGB::Black;
    FastLED.show();
    pauseAndLog("black");
    count++;
}
```

With all `FastLED.show()` calls commented it pauses for 1000ms between each serial message as requested:

```
Starting firmware.
red   0  19723  Sun Oct 30 06:29:28 2016
black 0  20723  Sun Oct 30 06:29:29 2016
red   1  21724  Sun Oct 30 06:29:31 2016
black 1  22724  Sun Oct 30 06:29:32 2016
red   2  23725  Sun Oct 30 06:29:33 2016
black 2  24725  Sun Oct 30 06:29:34 2016
red   3  25726  Sun Oct 30 06:29:35 2016
black 3  26726  Sun Oct 30 06:29:36 2016
red   4  27727  Sun Oct 30 06:29:37 2016
black 4  28727  Sun Oct 30 06:29:38 2016
red   5  29728  Sun Oct 30 06:29:39 2016
black 5  30728  Sun Oct 30 06:29:40 2016
```

With `FastLED.show()` uncommented, I see brief flickers of the LED, which corresponds with the 3ms between most black to red transitions. Of note, every so often I do see the LED lit for a full second, these correspond with the instances where the `millis()` output goes backwards (visible in loops 0, 6, and 22)

```
Starting firmware.
red   0  35790  Sun Oct 30 06:32:01 2016
black 0  55870  Sun Oct 30 06:32:02 2016
red   1  55873  Sun Oct 30 06:32:03 2016
black 1  56874  Sun Oct 30 06:32:03 2016
red   2  56877  Sun Oct 30 06:32:04 2016
black 2  57878  Sun Oct 30 06:32:04 2016
red   3  57881  Sun Oct 30 06:32:05 2016
black 3  58882  Sun Oct 30 06:32:05 2016
red   4  58885  Sun Oct 30 06:32:06 2016
black 4  59886  Sun Oct 30 06:32:06 2016
red   5  59889  Sun Oct 30 06:32:07 2016
black 5  60890  Sun Oct 30 06:32:07 2016
red   6  60893  Sun Oct 30 06:32:08 2016
black 6  26106  Sun Oct 30 06:32:08 2016
red   7  61897  Sun Oct 30 06:32:09 2016
black 7  62898  Sun Oct 30 06:32:10 2016
red   8  63898  Sun Oct 30 06:32:10 2016
black 8  63901  Sun Oct 30 06:32:10 2016
red   9  63904  Sun Oct 30 06:32:11 2016
black 9  64905  Sun Oct 30 06:32:11 2016
red   10  64908  Sun Oct 30 06:32:12 2016
black 10  65909  Sun Oct 30 06:32:12 2016
red   11  65912  Sun Oct 30 06:32:13 2016
black 11  66913  Sun Oct 30 06:32:13 2016
red   12  66916  Sun Oct 30 06:32:14 2016
black 12  67917  Sun Oct 30 06:32:14 2016
red   13  67920  Sun Oct 30 06:32:15 2016
black 13  68921  Sun Oct 30 06:32:15 2016
red   14  68924  Sun Oct 30 06:32:16 2016
black 14  69925  Sun Oct 30 06:32:16 2016
red   15  69928  Sun Oct 30 06:32:17 2016
black 15  70929  Sun Oct 30 06:32:17 2016
red   16  70932  Sun Oct 30 06:32:18 2016
black 16  71933  Sun Oct 30 06:32:18 2016
red   17  71936  Sun Oct 30 06:32:19 2016
black 17  72937  Sun Oct 30 06:32:19 2016
red   18  72940  Sun Oct 30 06:32:20 2016
black 18  73941  Sun Oct 30 06:32:20 2016
red   19  73944  Sun Oct 30 06:32:21 2016
black 19  74945  Sun Oct 30 06:32:21 2016
red   20  74948  Sun Oct 30 06:32:22 2016
black 20  75949  Sun Oct 30 06:32:22 2016
red   21  75952  Sun Oct 30 06:32:23 2016
black 21  76953  Sun Oct 30 06:32:23 2016
red   22  76956  Sun Oct 30 06:32:24 2016
black 22  42169  Sun Oct 30 06:32:24 2016
red   23  77960  Sun Oct 30 06:32:25 2016
black 23  78961  Sun Oct 30 06:32:26 2016
red   24  79961  Sun Oct 30 06:32:26 2016
```

If I replace the `pauseAndLog()` calls with `pauseAndLog(<color>, 2)` to cause two 1000ms delays after each LED call, you can see 1003ms pauses, confirming the first delay gets screwed up.

```
red   4  53561  Sun Oct 30 06:14:18 2016
black 4  54564  Sun Oct 30 06:14:19 2016
red   5  55566  Sun Oct 30 06:14:20 2016
black 5  56569  Sun Oct 30 06:14:21 2016
red   6  57571  Sun Oct 30 06:14:22 2016
black 6  58574  Sun Oct 30 06:14:23 2016
red   7  59576  Sun Oct 30 06:14:24 2016
black 7  60579  Sun Oct 30 06:14:25 2016
red   8  61581  Sun Oct 30 06:14:26 2016
black 8  62584  Sun Oct 30 06:14:28 2016
red   9  64584  Sun Oct 30 06:14:29 2016
black 9  65587  Sun Oct 30 06:14:30 2016
red   10  66589  Sun Oct 30 06:14:31 2016
black 10  67592  Sun Oct 30 06:14:32 2016
red   11  68594  Sun Oct 30 06:14:33 2016
black 11  69597  Sun Oct 30 06:14:34 2016
red   12  70599  Sun Oct 30 06:14:35 2016
black 12  71602  Sun Oct 30 06:14:36 2016
```

When calling `pauseAndLog(<color>, 1, 2000)` duration I still see 3ms effective duration (instead of 2000ms requested) except for loops 0, 3, 11, and 19.

```
Starting firmware.
red   0  35791  Sun Oct 30 06:43:28 2016
black 0  56081  Sun Oct 30 06:43:29 2016
red   1  56084  Sun Oct 30 06:43:31 2016
black 1  58085  Sun Oct 30 06:43:31 2016
red   2  58088  Sun Oct 30 06:43:33 2016
black 2  60089  Sun Oct 30 06:43:33 2016
red   3  60092  Sun Oct 30 06:43:35 2016
black 3  26305  Sun Oct 30 06:43:35 2016
red   4  62096  Sun Oct 30 06:43:37 2016
black 4  64097  Sun Oct 30 06:43:37 2016
red   5  64100  Sun Oct 30 06:43:39 2016
black 5  66101  Sun Oct 30 06:43:39 2016
red   6  66104  Sun Oct 30 06:43:41 2016
black 6  68105  Sun Oct 30 06:43:41 2016
red   7  68108  Sun Oct 30 06:43:43 2016
black 7  70109  Sun Oct 30 06:43:43 2016
red   8  70112  Sun Oct 30 06:43:45 2016
black 8  72113  Sun Oct 30 06:43:45 2016
red   9  72116  Sun Oct 30 06:43:47 2016
black 9  74117  Sun Oct 30 06:43:47 2016
red   10  74120  Sun Oct 30 06:43:49 2016
black 10  76121  Sun Oct 30 06:43:49 2016
red   11  76124  Sun Oct 30 06:43:51 2016
black 11  42337  Sun Oct 30 06:43:51 2016
red   12  78128  Sun Oct 30 06:43:53 2016
black 12  80129  Sun Oct 30 06:43:53 2016
red   13  80132  Sun Oct 30 06:43:55 2016
black 13  82133  Sun Oct 30 06:43:55 2016
red   14  82136  Sun Oct 30 06:43:57 2016
black 14  84137  Sun Oct 30 06:43:57 2016
red   15  84140  Sun Oct 30 06:43:59 2016
black 15  86141  Sun Oct 30 06:43:59 2016
red   16  86144  Sun Oct 30 06:44:01 2016
black 16  88145  Sun Oct 30 06:44:01 2016
red   17  88148  Sun Oct 30 06:44:03 2016
black 17  90149  Sun Oct 30 06:44:03 2016
red   18  90152  Sun Oct 30 06:44:05 2016
black 18  92153  Sun Oct 30 06:44:05 2016
red   19  92156  Sun Oct 30 06:44:07 2016
black 19  58369  Sun Oct 30 06:44:07 2016
red   20  94160  Sun Oct 30 06:44:09 2016
black 20  96161  Sun Oct 30 06:44:09 2016
red   21  96164  Sun Oct 30 06:44:11 2016
black 21  98165  Sun Oct 30 06:44:11 2016
```

Interestingly the timer starts consistently going backwards when I specify a 1ms delay duration:

```
Starting firmware.                        
red   0  35791  Sun Oct 30 06:48:25 2016  
black 0  55903  Sun Oct 30 06:48:26 2016  
red   1  55906  Sun Oct 30 06:48:26 2016  
black 1  55908  Sun Oct 30 06:48:26 2016  
red   2  55911  Sun Oct 30 06:48:26 2016  
black 2  55913  Sun Oct 30 06:48:26 2016  
red   3  55916  Sun Oct 30 06:48:26 2016  
black 3  55918  Sun Oct 30 06:48:26 2016  
red   4  55921  Sun Oct 30 06:48:26 2016  
black 4  55923  Sun Oct 30 06:48:26 2016  
red   5  55926  Sun Oct 30 06:48:26 2016  
black 5  55928  Sun Oct 30 06:48:26 2016
red   6  55931  Sun Oct 30 06:48:26 2016
black 6  55933  Sun Oct 30 06:48:26 2016
red   7  55936  Sun Oct 30 06:48:26 2016
black 7  55938  Sun Oct 30 06:48:26 2016
red   8  55941  Sun Oct 30 06:48:26 2016
black 8  55943  Sun Oct 30 06:48:26 2016
red   9  55946  Sun Oct 30 06:48:26 2016
black 9  55948  Sun Oct 30 06:48:26 2016
red   10  55951  Sun Oct 30 06:48:26 2016
black 10  55953  Sun Oct 30 06:48:26 2016
red   11  55956  Sun Oct 30 06:48:26 2016
black 11  20170  Sun Oct 30 06:48:26 2016
red   12  55961  Sun Oct 30 06:48:26 2016
black 12  20175  Sun Oct 30 06:48:26 2016
red   13  55966  Sun Oct 30 06:48:26 2016
black 13  20180  Sun Oct 30 06:48:26 2016
red   14  55971  Sun Oct 30 06:48:26 2016
black 14  20185  Sun Oct 30 06:48:26 2016
red   15  55976  Sun Oct 30 06:48:26 2016
black 15  20190  Sun Oct 30 06:48:26 2016
red   16  55981  Sun Oct 30 06:48:26 2016
black 16  20195  Sun Oct 30 06:48:26 2016
red   17  55986  Sun Oct 30 06:48:26 2016
black 17  20200  Sun Oct 30 06:48:26 2016
red   18  55991  Sun Oct 30 06:48:26 2016
black 18  20205  Sun Oct 30 06:48:26 2016
red   19  55996  Sun Oct 30 06:48:26 2016
black 19  20210  Sun Oct 30 06:48:26 2016
red   20  56001  Sun Oct 30 06:48:26 2016
black 20  20215  Sun Oct 30 06:48:26 2016
red   21  56006  Sun Oct 30 06:48:26 2016
black 21  20220  Sun Oct 30 06:48:26 2016
red   22  56011  Sun Oct 30 06:48:26 2016
black 22  20225  Sun Oct 30 06:48:26 2016
red   23  56016  Sun Oct 30 06:48:26 2016
black 23  20230  Sun Oct 30 06:48:26 2016
red   24  56021  Sun Oct 30 06:48:26 2016
black 24  20235  Sun Oct 30 06:48:26 2016
red   25  56026  Sun Oct 30 06:48:26 2016
black 25  20240  Sun Oct 30 06:48:26 2016
```

**Comment by focalintent** [comment]
The problem is that writing out WS2812 data requires disabling interrupts -and the clock/timer is advanced by interrupts.  FastLED will try to adjust the timer appropriately - but it's approximate, and not always exact.

Adding the line:

```
#define FASTLED_ALLOW_INTERRUPTS 1
```

before you include FastLED.h may help - as it will allow the SYSTICK interrupts to fire when expected, advancing the clock appropriately.

**Comment by aboyett** [comment]
Thanks for the quick response. Unfortunately, adding that definition at the top of the program doesn't appear to help. I'm still seeing the issue.

To drill down deeper, the value of `millis()` changes after `FastLED.show()` in every iteration of `loop()`

I'm now using an event loop rather than calls to `delay()`. See https://gist.github.com/aboyett/23ccea0b89fe5feef1fe330f43c04840 for the code and output both with FastLED enabled and disabled.

 The code prints an output line both before and after each call to FastLED.show(). In `Output_without_FastLED.show()`, the value of `millis()` (column four) closely matches the `millis()` value at the beginning of the loop (called "ls:" in the output) in both the before and after cases. Compare that to `Output_with_FastLED.show()` where the value of `millis()` before a call to `FastLED.show()` matches the loopstart value, but afterwards it varies. After the first call (setting the LED to red), millis() - loopstart is 16122. After the second call (setting the LED to black) and for every call there after, millis() - loopstart = 34792

**Comment by focalintent** [comment]
Hmm - you know what, I wonder if the sparkcore firmware is using the _CYCCNT debug cycle count register to do its clock/millis timing (if so, that'd be really stupid) - as I use that register for cycle accurate counting for getting the output timings correct.  I'll have to get a hold of particle's firmware code to check on how, exactly, they're doing their millis timing.

**Comment by focalintent** [comment]
Yup - that's the problem - they're using DWT->CYCCNT to try to harden up against interrupts disabling the SYSTICK timer from counting/incrementing - https://github.com/spark/firmware/blob/ef92286e147acdc3730b7752737e1503059f1d2c/platform/MCU/shared/STM32/src/hw_ticks.c  - the problem is, that's a debug register that I also use for the timing control, and part of that involves resetting the value of the timer (to remove the complexity that comes with dealing with/worrying about overflow).  I can work on rewriting that at some point (though  at the moment my time available for working on this stuff is very limited - and the particle is a pain in the ass to work with as a library developer because of other fuckery with their build environment that I've been waiting years for them to fix).  This is the first time that i've seen platform code use the debug registers in a way that expects user code to not use them.

**Comment by focalintent** [comment]
(ah - this was a change they made this past april - which would explain why I didn't see this issue at all when I was initially working on/writing this code)

**Comment by focalintent** [comment]
And I think I have a way to fix - depending on how work goes today I should be able to get it in sometime during the day today, if not then hopefully tonight after work.

**Comment by aboyett** [comment]
No need to prioritize this. For the projects I was working on the event-loop approach is a better choice, I just was trying to take the lazy approach initially by using `delay()`.

It looks like these changes to `millis()` and `micros()` were merged in the latest patch release ([0.5.3](https://github.com/spark/firmware/releases/tag/v0.5.3)) put out less than a month ago. I'll try testing both 0.5.2 and one of the 0.6 release candidates and report back. I suspect the issue won't be present in 0.5.2 as it is lacking the changes you identified (from https://github.com/spark/firmware/pull/943).

**Comment by jassmith** [comment]
I hope you dont mind my asking aboyett but how are you managing to run FastLED master on a particle photon? Any time I try to build I get: led_sysdefs.h:27:43: fatal error: platforms/avr/led_sysdefs_avr.h: No such file or directory

I have googled and found references to people saying FASTLED_USING_NAMESPACE; fixes it for them, but that doesn't seem to work for me (I am already doing that). I am using the FastLED-Sparkcore repo in the mean time, but I would very much like to be running the tip of fastled instead.

**Comment by focalintent** [comment]
Tell the particle folks to make it less of a pain in the ass to manage libraries in their system :p. Between not functioning with the same directory layout as arduino libraries and requiring librar directory structures to be flat, it's enough of a pain that I'm not planning on doing the next push to spark core until I finish the rgbw work.

**Comment by focalintent** [comment]
(That's why I have the separate sparkcore repo)

**Comment by jassmith** [comment]
@focalintent if you are happy enough to explain to me how to do it I am more than happy to maintain your port. I looked at what you did and it seems you *mostly* flattened it out, however there are some other tweaks (especially around the math library) I don't understand why you did them.

**Comment by jogleasonjr** [comment]
I'm with @jassmith  and would contribute. It's not immediately clear to me what, at a high level, is different in the Sparkcore variant since the current one has many more commits. 

I also experience the missing references in `led_sysdefs_avr.h`. I'm sure the particle compiler has something to do with it, but it'd be great to have a Particle fork in relative lockstep with this repo, possibly using automated migration if there's a pattern of things to do.
