### ISSUE TITLE
Redbearlab BLE Nano v1.5 error: yield was not declared in this scope

### ISSUE THREAD

**Issue by danlsk** [FastLED/FastLED#369]
New problem with BLE Nano compilation. 

`C:\Users\...\Documents\Arduino\libraries\FastLED\FastLED.cpp: In member function 'void CFastLED::delay(long unsigned int)':`

`C:\Users\...\Documents\Arduino\libraries\FastLED\FastLED.cpp:133:9: error: 'yield' was not declared in this scope`

`   yield();`

In FastLED.cpp:
`#if defined(ARDUINO) && (ARDUINO > 150) && !defined(IS_BEAN)`
`		yield();`
`#endif`
I commented out  to get it working.
`//yeild();`

**Comment by focalintent** [comment]
They really should be defining this function, even as a nop, in their library/framework - I would file a bug with them.

**Comment by danlsk** [comment]
Did Redbearlab includes the yield()?

**Comment by focalintent** [comment]
The problem should be a bug for redbearlab - not castle, which is why I closed it.
