### ISSUE TITLE
Leds Not Showing

### ISSUE THREAD

**Issue by pipoblak** [FastLED/FastLED#375]
Im using the NodeMcu 1.0 hardware.

Code: https://gist.github.com/pipoblak/66582a53667cf6eca870f8fb8b2db910

I don't know why, but the leds do not showing, can you help me?

**Comment by kriegsman** [comment]
Hi and welcome!  
For general troubleshooting questions like this, please ask in our Google Plus forum: http://fastled.io/+
We keep the github issue tracker just for problems with the library itself; for general usage and assistance questions, we use G+.
