### ISSUE TITLE
Build support for RaspberryPi b+/2 using PiDuino?

### ISSUE THREAD

**Issue by shadowkrazee** [FastLED/FastLED#384]
i can compile sketches of varying complexity for the Pi without the FastLED library, but trying to compile any of my sketches written for the Uno with the Pi board selected as target yeilds these errors:

#########################################################

"C:\Users\JOHNAT~1\AppData\Local\Temp\builda6f9e29c8de7932251ef1235ff570d90.tmp\preproc\ctags_target_for_gcc_minus_e.cpp"
In file included from C:\Users\johnathan\Documents\Arduino\libraries\FastLED313/led_sysdefs.h:27:0,

                 from C:\Users\johnathan\Documents\Arduino\libraries\FastLED313/FastLED.h:44,

                 from C:\Users\johnathan\Documents\Arduino\sketchbook\libraries\FastLED313\examples\Noise\Noise.ino:1:

C:\Users\johnathan\Documents\Arduino\libraries\FastLED313/platforms/avr/led_sysdefs_avr.h:12:20: fatal error: avr/io.h: No such file or directory

 #include <avr/io.h>

                    ^

compilation terminated.

Using library FastLED313 at version 3.1.3 in folder: C:\Users\johnathan\Documents\Arduino\libraries\FastLED313 
exit status 1
Error compiling for board RaspberryPI B+/2.
###############################################

I hope to replace my arduino with a Pi 2 as the controller for my LEDs, as it has much more memory and Ethernet connection available for SSH login and control, but i'd like to keep all of the programs i've written for the Uno for use on the Pi with as little re-writing as possible. 

FastLED is the best library i've found for these applications, and frankly i've grown very used to writing my programs using it, and would like to be able to continue doing so to build for the Raspberry Pi.

Is this a realistic possibility?

**Comment by focalintent** [comment]
FastLED doesn't support the pi (or any environment with an OS, really).  It would be a non-insignificant amount of work to do, so we've preemptively decided to not go down that path at all - I've got a full plate of platforms to add support for where we are running directly as it is.
