### ISSUE TITLE
Cant include fastLED Libary

### ISSUE THREAD

**Issue by Cramery** [FastLED/FastLED#385]
When I try to Include the FastLED-Libary, I just get an error "fatal error: FastLED.h: No such file or directory" so I cant even go to the point where I can have problems with coding with the FastLED :D

**Comment by marmilicious** [comment]
When you unzipped it, did you rename it from FastLED-master to just FastLED ?
Also remember to restart the Arduino IDE after installing a new library.

**Comment by Ramy602** [comment]
Thx, just solved it. It didnt worked when I just add the Libary, I had to copy it to the directory :)
