### ISSUE TITLE
Doesn't compile for Genuino 101

### ISSUE THREAD

**Issue by DaniFoldi** [FastLED/FastLED#388]
I get this error message:

> In file included from /Users/***/Documents/Arduino/libraries/FastLED-3.1.3/led_sysdefs.h:27:0,
                 from /Users/***/Documents/Arduino/libraries/FastLED-3.1.3/FastLED.h:44,
                 from /tmp/arduino_modified_sketch_65304/Blink.ino:1:
/Users/***/Documents/Arduino/libraries/FastLED-3.1.3/platforms/avr/led_sysdefs_avr.h:12:20: fatal error: avr/io.h: No such file or directory
 #include <avr/io.h>
                    ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino 101.

How do I fix this or can you please if it's not my mistake Pls?

**Comment by focalintent** [comment]
The genuino 101 is not a supported board, and unlikely to be in the near future.
