### ISSUE TITLE
FastLED library error in Particle build when importing

### ISSUE THREAD

**Issue by steeley** [FastLED/FastLED#392]
When using 'contribute library' for FastLED, Particle Build gives this error:
Library is not valid, please fix the errors below and resubmit.
Metadata

    name: FastLEDSmartMatrix
    author: Daniel Garcia, Mark Kriegsman
    license: MIT
    version: 3.1.5
    description: (Temporary!) FastLED with SmartMatrix compatibility - A packaging of FastLED 3.1 for sparkcore and photon
    namespace: NSFastLED

Metadata Validations

    spark.json file is present
    spark.json file is in the JSON format
    spark.json file is invalid
        version is present
        version is in valid format
        version is not unique 3.1.5 is already released
        version is greatest so far
        name is present
        name is already taken by another user
        author is present

Files and Directories

    main header file (firmware/FastLEDSmartMatrix.h) was found
    main source file (firmware/FastLEDSmartMatrix.cpp) was found
    examples/ folder was found
    license file exists

Documentation

    README.md file was found

**Comment by focalintent** [comment]
That is not the main branch of the library.  You need to file this on the FastLEDSmartMatrix fork.
