### ISSUE TITLE
Auto Mode

### ISSUE THREAD

**Issue by LedArts** [FastLED/FastLED#395]
Can anybody add 'auto mode' function. By which Automatically effects are change one by one with some delay.

**Comment by kriegsman** [comment]
Check out the example called "DemoReel100" for one way to do this. This example is included in the library by default. You can use it as-is, or add more animations if you wish. 
Closing the ticket.

**Comment by LedArts** [comment]
thanks a lot sir, will try this.
Sir, there are six effects in demo Reel100 {rainbow, rainbowWithGlitter, confetti, sinelon, juggle, bpm}
can u tell me how much effects are present in fast led for pixal led strip.
i want run all the effects one by one in pixal led strip. please tell and give me all the effects of fast led with one program. I am using arduino with ic 328. Please sir, It will be more help full for me.

**Comment by focalintent** [comment]
FastLED is not a library of LED effects.  It is a library for _making_ LED effects - as such, there's no such thing "all the effects" in FastLED - DemoReel100 attempts to show off some of the types of things you can do.   If you have specific coding questions, please ask on the g+ group at http://fastled.io/+

**Comment by LedArts** [comment]
ok thank you sir...i have a one question. If i have to add more effects in demoReel100 how i add and which software should i use arduino or AVR Studio.

**Comment by DeuxVis** [comment]
@LedArts in case that wasn't clear in @focalintent previous answer, you should **please ask on the g+ group at http://fastled.io/+** for all your questions.

Here - github - your will only get answers about "bug reports, feature requests and library changes".

Thanks !

**Comment by alvin666666** [comment]
Hello,

We have one new led strip,gs8206,first it have the breakpoint continue ,then,the full color same with ws2811. Another important is,that have 33 kinds of color in the gs8206ic,no need the controller. but,if you connect the controller like ws2811,also is ok. It can be 12v and 24v. If you want to know more,send email to me.
Email:Alvin@witop-tech.com

**Comment by kasperkamperman** [comment]
Is it possible to mark this Alvin guy as spam somewhere?

**Comment by DeuxVis** [comment]
@kasperkamperman : Open its profile - clicking his icon or name - and use the "block or report user" feature there.
