### ISSUE TITLE
How to have multiple controllers on one strip?

### ISSUE THREAD

**Issue by MacNetron** [FastLED/FastLED#397]
Hi,

I have a WS2812B 93 "ledstrip" which consists of multiple rings, 1 8 12 16 24 32 (ie 93 leds).
It has been soldered to be one big strip, with the outer ring having the first led and the tiny inner ring being the last one.
With the demoreel100 example I have validated that the strip works correctly.

Now I would like to implement multiple controllers for each ring, so they can display different things (as in the end the outer rings should behave like a clock, the inner rings should show data from various sensors, like temperature, humidity, etc).

I have been playing with the offset setting in the FastLED.addLeds function but that does not give me the results I wanted.

So, is it possible to define multiple controllers for configurable parts on one strip? And if yes, can you please give an example how?

**Comment by focalintent** [comment]
No - controllers are related to physical sets of leds on a single pin.  Instead, what you want to do is access different portions of your led arrays.  So, for example - leds 0-31 will be your outter ring, leds 32-55 will be your next inner ring 56-71 will be your next, etc... etc... 

For more general programming questions/how to use led arrays/etc... - ask on the fastled g+ community - http://fastled.io/+ -- there's a lot more people there who can provide basic programming help - I'd really like to keep the issues here to bug reports and feature requests and library changes, thank you.
