### ISSUE TITLE
non parallel setup

### ISSUE THREAD

**Issue by tonton81** [FastLED/FastLED#403]
is possible without octows2811 or parallel output as well? would not like to use the whole port if i only need one pin

**Comment by focalintent** [comment]
I'm not sure I understand what you're asking for here.  If you only want to use one pin - then you just call addLeds with the one pin that you want to use.  

For basic "how do i use the library" questions - I'd strongly recommend using the g+ group - http://fastled.io/+ -- I'd really rather keep the github issues for bugs and feature requests.
