### ISSUE TITLE
Reciving error

### ISSUE THREAD

**Issue by pipoblak** [FastLED/FastLED#408]
Hi, i'm using that code :
https://gist.github.com/pipoblak/a83f9f7475dfe4150f183a3deb801650

And after a time, i recive that error:

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112

I'm using a NODEMCU DEVKIT 1.0.

Can anyone help me ?  =D

**Comment by kriegsman** [comment]
HI!  For general 'help' questions like this, please ask over on our Google Plus community for FastLED: http://fastled.io/+

If this turns out to be an actual library bug, we can re-open this ticket.  Thanks!
