### ISSUE TITLE
WS2812B just turns on white

### ISSUE THREAD

**Issue by usersxm** [FastLED/FastLED#424]
I've tried this library, and the adafruit one but no one seems to be working for me. I don't know what's the problem, I've also tried using an arduino uno and a nano to power just one led (cut off from a led strip).
Here it is the sketch for the blinking example, and also a picture of all the wirings (in case you cannot see, there's a 100ohm resistor for the data pin which I've read was recommended):
![img_0969](https://cloud.githubusercontent.com/assets/9682572/23838195/c40df892-0771-11e7-81ca-3fbabf6a1573.JPG)
![img_0970](https://cloud.githubusercontent.com/assets/9682572/23838309/1af46a5a-0773-11e7-91ee-9bad20697bf7.JPG)

```
#include "FastLED.h"

// How many leds in your strip?
#define NUM_LEDS 1

// For led chips like Neopixels, which have a data line, ground, and power, you just
// need to define DATA_PIN.  For led chipsets that are SPI based (four wires - data, clock,
// ground, and power), like the LPD8806 define both DATA_PIN and CLOCK_PIN
#define DATA_PIN 5
//#define CLOCK_PIN 13

// Define the array of leds
CRGB leds[NUM_LEDS];

void setup() { 
      // Uncomment/edit one of the following lines for your leds arrangement.
      FastLED.addLeds<WS2812B, DATA_PIN, RGB>(leds, NUM_LEDS);
}

void loop() { 
  // Turn the LED on, then pause
  leds[0] = CRGB::Red;
  FastLED.show();
  delay(500);
  // Now turn the LED off, then pause
  leds[0] = CRGB::Black;
  FastLED.show();
  delay(500);
}
```

The most weird thing is that when I unplug the arduino from the computer and plug it back again the led won't turn on, I need to move, unplug the 5v, ground and data pins and sometimes after doing this it turns back on. It is driving me mad! How is it possible that I can't achieve such a simple task!

**Comment by focalintent** [comment]
See the arrow on the strip?  That indicates which way data is flowing.  You've wired things to the output side of the led (DO == data out) instead of the input. Move your connections to the other side of the led chip.

**Comment by focalintent** [comment]
Nothing that I can obviously see here - but I prefer to keep GitHub issues for bug reports a if you ask on the g+ community (http://FastLED.io/+) you will be more likely to come across folks who can definitively answer you.

**Comment by electrokean** [comment]
@usersxm it looks like you don't have anything connected to the -V side of the power supply, but instead you're using the earth terminal.  The earth is for mains earthing for safety, and is not necessarily common with the -V (usually there is a capacitor between them, so no current flows).  Also make sure you have a common ground connection between the LEDs, PSU (-V), and Arduino.
