### ISSUE TITLE
WS2812 100 Hz strobe effect with different duty cycles?

### ISSUE THREAD

**Issue by Nyte7** [FastLED/FastLED#430]
I'm wondering if it's possible to generate a strobe effect using the Arduino UNO and WS2812 LED strip with different duty cycles?

Currently, I use the FastLED library connected to PWM pin 6 of my UNO board and I'm able to do basic things with the LED strip (change color, delay, blink, etc.).

I power the board through USB and use the 5V/GND from the same board to power the strip.

Now, I would like to set all my LEDS on the strip (6 of them) to strobe at 100 Hz (10 ms) frequency.  I would also like the duty cycle to be 10%/90% (or 20%/80%) for HIGH/LOW.

I would just like to confirm if this would indeed generate a nice 10/90 duty cycle strobe effect across all my leds?  Because it flashes at 100 Hz, I can't tell (I don't have access to a scope) if it's working properly or not.  I do see it "flicker" though, and in some non-WS2812 setups I've seen online, they don't suffer or mention a "flicker" problem

I'm trying to replicate a strobing effect that others have accomplished with standard RGB led strips as seen here:
http://www.instructables.com/id/TimeFrame-a-Time-Portal-to-Put-on-Your-Desk/

However, in their guide, they seem to play around with the Atmel register settings to achieve their effect.  I'm not sure if they specifically ignored the WS2812 LEDs because it was impossible to accomplish or not with the currently available libraries from FastLED or NeoPixels.

My main loop code is currently like this:

// Apply a 10 and 90 percent ON OFF duty cycle
void loop() {
   for (int i = 0; i < 6; i++){
       leds = CRGB::White;
   }
   FastLED.show();
   delay(1); // This is supposedly in milli-seconds, so delay for 1
   for (int i = 0; i < 6; i++){
       leds = CRGB::Black;
   }
   FastLED.show();
   delay(9); // LEDs off, delay for 9 milli-seconds
}

Stephen

**Comment by focalintent** [comment]
(For discussion and how-to questions I'd really prefer that folks use the g+ group  - http://fastled.io/+ - I would like to keep the github issues limited to bug reports)

The WS2812 is a terrible chipset to use for strobing.  It has a 400hz PWM cycle - so the minimum time for a flash that you can reliably get is 2.5ms (and even then, depending on the timing of writing out subsequent frames it might be more like 5ms or even 7.5ms) - which at your 10/90 duty cycle is a cycle of 25ms at best or 40hz.

You'll get a strobe effect of sorts, but not sure it'll actually be what you want.
