### ISSUE TITLE
First LED problems in OctoWS2811 mode w/ Faster or Fastest Optimizations

### ISSUE THREAD

**Issue by Swap-File** [FastLED/FastLED#442]
While using FastLED in OctoWS2811 mode on the Teensy 3.2 if Faster or Fastest is selected under compiler optimizations in the Arduino IDE, the first LED in a strip seems to be skipped over when updating a strip.  The first LED will show blank, or occasionally update and get stuck on a color.  The second LED and beyond is still updated fine.

I tested this with the Arduino IDE 1.8.2 and the latest Teensyduino, with a few versions of FastLED (including the master branch).

I only noticed it because I think that Visual Micro changed it's default to Faster when I updated it (or else I bumped the setting).

Should this be brought up in the OctoWS2811 repo instead, since technically it's not FastLED's problem?  Or is this more of a compiler problem (meaning, just don't use other settings)?

Either way, it would be useful to get it documented somewhere.  I didn't see it mentioned anywhere..

**Comment by Sushisource** [comment]
I have also noticed this - quite annoying.

**Comment by bechtold** [comment]
Can confirm the bug.
But "Faster with LTO" and "Fastest with LTO" is working as expected.

**Comment by Sushisource** [comment]
The LTO ones still have the bug on my 3.2

**Comment by focalintent** [comment]
I think this is an OctoWS2811 bug - as the wrapper just does the bit rotation to get the data in a format OctoWS2811 wants internally in its draw buffer, otherwise OctoWS2811 is doing all the work.
