### ISSUE TITLE
CHSV to int?

### ISSUE THREAD

**Issue by mgcrea** [FastLED/FastLED#445]
Not sure if I've missed something in the docs, but I have functions that takes an HTML color as an input (eg. `CRGB::White`) that does seem to be an `int` type.

How can I feed a custom CHSV color to this same function? So convert a CHSV to an int?

```
static CHSV myColor = CHSV(160, 255, 255);
```

```
src/led/led.cpp:115:142: error: cannot convert 'CHSV' to 'int' for argument '2'
```

Tried `myColor.raw` but got an error:

```
src/led/led.cpp:115:146: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'int'
```

**Comment by kriegsman** [comment]
Hi! For general help questions like this, try the FastLED Google+ discussion group at http://FastLED.io/+
We usually only use GitHub bug tickets for bugs in the library itself. 

Also, this may help:
static CHSV myColor(160,255,255);
Maybe!

**Comment by kriegsman** [comment]
Closing this ticket, and we can continue the conversation over on the G+ group.
