### ISSUE TITLE
WS2813_800kHz not defined

### ISSUE THREAD

**Issue by ssilverman** [FastLED/FastLED#450]
Commenting out the "case OCTOWS2813" line in FastLED.h lets it compile.
My code is currently on master, commit # da2f0f3d2c39d5d4181bdc32c6b0fb8ad926c2f3

**Comment by fromcph** [comment]
Experiencing the same issue when trying to compile the exact code from the OctoWS2811Demo without any changes for the Teensy 3.1/3.2 board. Running on Arduino 1.8.3 on Win10 with FastLED 3.1.5. 
But thanks for the tip @ssilverman , that fixed it!

**Comment by focalintent** [comment]
The problem is having an older version of the OctoWS2811 library installed that doesn't have the 2813 timings.  Fixing that onw.
