### ISSUE TITLE
WeMos D1R2 ESP2866

### ISSUE THREAD

**Issue by AAli77** [FastLED/FastLED#458]
Hi Sir, I am new to the Arduino Environment but my background is from programming field.

Issue:  Code successfully compile but no result, can you please help me with this.

thanks

I am using WeMos D1R2 ESP2866, and WS2812B

The coding:
#include <FastLED.h>

#define NUM_LEDS 30 
#define DATA_PIN 2 

CRGB leds[NUM_LEDS];

void setup() { 

  FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS); 
  
  Serial.begin(500000);

}

void loop() {
  
  for(int i = 0; i < NUM_LEDS; i++) {
    
    if (Serial.available() > 0) {
      
      Serial.readBytes( (char*)leds, NUM_LEDS * 3);
      Serial.flush();
    }
    
    FastLED.show();
    delay(10);
  }

}

**Comment by jasoncoon** [comment]
Hello!  This issue tracker is for bugs with the library.  For general help, please read through the [Frequently Asked Questions](https://github.com/FastLED/FastLED/wiki/Frequently-Asked-Questions), and then post in the [FastLED community](http://fastled.io/+), as mentioned in the [Getting Help](https://github.com/FastLED/FastLED#getting-help) section.
