### ISSUE TITLE
WS2811S chipset Support

### ISSUE THREAD

**Issue by Nik1990** [FastLED/FastLED#459]
I've a strip led with WS2811S (note the "S"). Is the chipset supported from the library?
With the following code (blink.ino) 

`
#include "FastLED.h"

// How many leds in your strip?
#define NUM_LEDS 60

// For led chips like Neopixels, which have a data line, ground, and power, you just
// need to define DATA_PIN.  For led chipsets that are SPI based (four wires - data, clock,
// ground, and power), like the LPD8806 define both DATA_PIN and CLOCK_PIN
#define DATA_PIN 13

// Define the array of leds
CRGB leds[NUM_LEDS];

void setup() { 
      FastLED.addLeds<WS2811, DATA_PIN, RGB>(leds, NUM_LEDS);
}

void loop() { 
  // Turn the LED on, then pause
  leds[0] = CRGB::Red;
  FastLED.show();
  delay(500);
  // Now turn the LED off, then pause
  leds[0] = CRGB::Black;
  FastLED.show();
  delay(500);
}
`

the strip led now work (random colors)

Thanks

**Comment by focalintent** [comment]
I haven’t done anything explicit to support it - and a quick search for a data sheet to get the timing isn’t turning anything up.  If you can find a data sheet for it (that isn’t the WS2811 data sheet) then I can add support for it.

**Comment by Nik1990** [comment]
Hi, i have found only this

http://www.world-semi.com/solution/details-106-4.html

but after opened data-sheet it seems that ws2811 and ws2811s are the same.

**Comment by focalintent** [comment]
Also what hardware are you testing this on?

**Comment by jasoncoon** [comment]
The WS2811S seems to be the same chip (and protocol), just in a SOP-8 (small outline package), as opposed to DIP-8 (dual in-line package).

**Comment by Nik1990** [comment]
With a Arduino Uno. Data pin connected to PIN 13.

**Comment by focalintent** [comment]
What happens if you try a different pin?  (Pin 13 is attached to the onboard led - I wonder if that is messing with signal timing)

**Comment by focalintent** [comment]
Also what version of arduino are you using?

**Comment by Nik1990** [comment]
So, i connected the DATA Pin of strip LED to pin 8 of arduino and the problem is the same. Arduino version is the "Arduino UNO". But it is a not original version. It is possible that the problem is this?

**Comment by marmilicious** [comment]
No, what version of the Arduino IDE.  1.8.0,  1.6.8,  etc.?

**Comment by Nik1990** [comment]
This:

![arduino_v](https://cloud.githubusercontent.com/assets/3687153/26677999/5c318738-469c-11e7-9ec5-1b36426e3891.png)

**Comment by focalintent** [comment]
This is not a version of arduino that I have tested with - it is possible that they have made compiler changes that are interfering with the asm code for the WS2811.  Try going back to 1.6.x or 1.8

**Comment by electrokean** [comment]
@focalintent @Nik1990 I believe that is Arduino 1.0.5 packaged for Debian Linux - pretty old, but Arduino don't allow third party distribution of newer versions so you have to download and install a newer version from arduino website, not via the Linux package manager

**Comment by focalintent** [comment]
Ah I misread, looked like it was 2.0.5 - that said
Arduiono 1.0.x hasn’t been tested/supported in a long time.  Try getting 1.6.x or 1.8.x (the readme for the library even explicitly states this)

**Comment by Nik1990** [comment]
I have just tried Arduino 1.6.0 under windows and the problem is the same. Same sketch only changed the pin (12 to 4).

**Comment by MFornander** [comment]
Could you connect a normal WS2811 or WS2812 strand in the exact same place so we can see if it's hardware or software?

**Comment by Nik1990** [comment]
Just tried also Arduino IDE 1.8.1. Same problem. And no, i don't have WS2811 or WS 2812. Only 5m of this chipset strip led.

**Comment by electrokean** [comment]
@Nik1990 It is possible the WS2811S that you have are 400kHz version - can you try an LED type of WS2811_400
In other words, change your setup code to:
`FastLED.addLeds<WS2811_400, DATA_PIN, RGB>(leds, NUM_LEDS);`

As you don't have any other strips to test, you could instead do some testing using the Adafruit NeoPixel library and see if they work with that, either as NEO_KHZ800 or NEO_KHZ400

**Comment by Nik1990** [comment]
@electrokean Nothing, i tried WS2811_400 and Adafruit NeoPixel library. Same problem.

**Comment by electrokean** [comment]
Hmmm... Maybe your LED strip is faulty - or at least the first chip/LED, which I've seen happen before.
Can you desolder or cut the strip into 1m sections and test the separately?

**Comment by focalintent** [comment]
How do you have things wired up?  This is beginning to sound like either a problem with you led hardware or your wiring.

**Comment by Nik1990** [comment]
![whatsapp image 2017-06-01 at 14 59 17](https://cloud.githubusercontent.com/assets/3687153/26696020/fa61a986-46da-11e7-9225-d69ba85b96a9.jpeg)

For debug i cutted only 3 led (1 chip) connected to 12v 3A power supply. All library seems to show random colors with simple code. I also tried a 5v 2A power supply and only red led switch on. Tried also the @electrokean  suggest of test other first chipset of strip and the problem is the same.

**Comment by Blink515** [comment]
You need to connect the ground from your power supply to the strip and the
Arduino board.

**Comment by focalintent** [comment]
You need to also connect ground on the led strip to ground on the arduino - it's not enough to just connect the data line.

**Comment by Nik1990** [comment]
Thanks boys :D. Two days for a wire, problem solved.
