### ISSUE TITLE
Compile Error in Attiny85 internal 16MHz

### ISSUE THREAD

**Issue by xpix** [FastLED/FastLED#46]
Hello,

i'm very happy to found this lib. But, i run in some compile errors with FastLED 2.1:

`Blink.cpp.o: In function CLEDController* CFastLED::addLeds<(EClocklessChipsets)4, (unsigned char)3, (EOrder)10>(CRGB const*, int, int)':
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/FastLED.h:139: undefined reference to '__cxa_guard_acquire'
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/FastLED.h:139: undefined reference to '__cxa_guard_release'
Blink.cpp.o: In function 'ClocklessController_Trinket<(unsigned char)3, 4, 10, 6, (EOrder)10, 50>::showRGBInternal_AdjTime(int, bool, int, unsigned char, unsigned char const*)':
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/clockless_trinket.h:84: undefined reference to 'timer0_millis'
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/clockless_trinket.h:84: undefined reference to 'timer0_millis'
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/clockless_trinket.h:84: undefined reference to 'timer0_millis'
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/clockless_trinket.h:84: undefined reference to 'timer0_millis'
C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/clockless_trinket.h:84: undefined reference to 'timer0_millis'
Blink.cpp.o:C:\Users\xpix\Dropbox\arduino-1.5.4\libraries\FastLED/clockless_trinket.h:84: more undefined references to 'timer0_millis' follow
`

I hope u can help :)

cu
Frank

**Comment by kriegsman** [comment]
Note from past implementors to future implementors:  FastLED can supply some of this now, via this:
#define NEED_CXX_BITS
