### ISSUE TITLE
Mirroring

### ISSUE THREAD

**Issue by zombodotcom** [FastLED/FastLED#461]
Is there a way to split 1 strip into 4 separate sections to mirror?

**Comment by electrokean** [comment]
Can you just do it in hardware?  The input pin(s) can just be wired in parallel on all strips.

**Comment by focalintent** [comment]
Either that or write your own code to copy led data from one portion of the strip to the other 3 areas. 

(Please use the g+ group - http://fastled.io/+ for general "how do I" questions - id like to keep github issues to bug reports)
