### ISSUE TITLE
ws2818 led strip programmable is same with ws2811?

### ISSUE THREAD

**Issue by Ethanmose** [FastLED/FastLED#468]
I prepare buy some ws2818 led strip to test,because,it is have the same function(break-point continue) with ws2813,when one ic broken,the others led will work normally. So,it is more stable than ws2811. But i can use the  same programm or controller with ws2811?

**Comment by focalintent** [comment]
Try the different WS controller settings - I did a quick skim of the data sheets and the timings look close, but they aren’t exactly the same.

**Comment by jessie012** [comment]
Hey My friend. the Ws2811 and ws2818, when test ,you can use the same program or controller,
