### ISSUE TITLE
APA102 global brightness

### ISSUE THREAD

**Issue by skandragon** [FastLED/FastLED#469]
I noticed in the APA102 driver code, the colors are scaled using the global brightness value.  Has the brightness register on these chips been tried and rejected, or were they never tried?

There is a 5-bit brightness value sent as the low order bits of the first byte: 0b111x xxxx, but it looks like the code intentionally sets this to full brightness and uses the color scaling functions to change all three values during transmission.

I'll likely give it a try tonight, but I'm wondering if there are known dragons...

**Comment by kasperkamperman** [comment]
See: https://github.com/FastLED/FastLED/issues/91

**Comment by skandragon** [comment]
Thanks!
