### ISSUE TITLE
ESP8266 / ESP32 - SPI Support

### ISSUE THREAD

**Issue by Hokyjack** [FastLED/FastLED#471]
Hello, I would love to use this awesome library in my project,
however I am using ESP8266 boards, and it seems that SPI isn't supported yet.

I have some basic C/C++ skills, so maybe I could help to implement this,
but I have no idea where to begin, and some hints where to begin would be cool.
How difficult is to implement the SPI support? Few days of work?

**Comment by jdschuitemaker** [comment]
Same question here..
