### ISSUE TITLE
Any Update on NRF52XXX

### ISSUE THREAD

**Issue by searayca** [FastLED/FastLED#476]
I am porting an Arduino project to the Nordic NRF52XXX. Any update FastLED porting progress?

Any way we might be able to help?

Greg

**Comment by focalintent** [comment]
No - I’m still not actively working on the library right now.

**Comment by searayca** [comment]
Thank you.

Greg

**Comment by gazrowntree** [comment]
Hi, just wanted to add my interest to this item.

**Comment by pcaddict** [comment]
I have made some progress on this [here](https://github.com/pcaddict/FastLED). So far SPI based chipsets should work but I only have APA102s to test with.
