### ISSUE TITLE
I can only show 170 neopixel 2427 leds. Could somebody help me?

### ISSUE THREAD

**Issue by tdzuc** [FastLED/FastLED#486]
I have 192 neopixel 2427 leds. But it always only show 170 leds. If I change to the led from neopixel to ws2811  in the rfduino'code. It will show 192 leds ,but the color is wrong. It seems it has some problem in the libery? Could I help me to solve it ?thank u very much

**Comment by focalintent** [comment]
My guess is that you're running into problems where interrupts are running that are always taking long enough that it's cutting off writing the frame - try adding the line:

```
#define FASTLED_ALLOW_INTERRUPTS 0
```

before your `#include <FastLED.h>`

**Comment by tdzuc** [comment]
Thank u very much . It works.
