### ISSUE TITLE
Random colors when starting and flashing sketch

### ISSUE THREAD

**Issue by Hokyjack** [FastLED/FastLED#497]
Hello, I know this is not strictly related to FastLED library, but more generaly to any LED system, but I'd like to know if tehre is any way how to solve this.
Each time I start ESP8266 (or Arduino) = plugging USB cable into PC, the APA102 strip lights up random color (mostly of time just white) to some random part of strip - in the beggining.

What more, when I am flashing a new sketch random colors starts loading up from begging of the strip to end.

Can I somehow disable randomly lighting the strip, before the library is initialized?

I guess it is caused by some random garbage on data/spi pins when the arduino is booted or flashed, is it true?

Thanks for tips!

**Comment by tablatronix** [comment]
Did you try different pins ? Does your board have pullups/downs on that pin ? Does it happen with an empty sketch ?
