### ISSUE TITLE
using FastLED while producing sounds

### ISSUE THREAD

**Issue by nitbeat** [FastLED/FastLED#499]
Hi,

I noticed this issue:
https://github.com/FastLED/FastLED/issues/208

It's from 2015, so I'm just hoping for a current solution using FastLED while producing sounds.
If not Tone() maybe someone knows a working alternative ?

How do you make sounds while using FastLED 

Arduino Nano V3 - Atmegs328

**Comment by focalintent** [comment]
Use leds that don't require disabling interrupts - for example APA102's.  Also - as mentioned in the issue that you linked to - for general "how do I" questions, please use the g+ group.

> (And in general, we use this issue tracker for bugs. For questions and how-to help, try the Google Plus group for FastLED: http://fastled.io/+ )

**Comment by focalintent** [comment]
Alternatively, use a platform, like the teensy 3.2, that allows running interrupts while writing out WS2812 led data.

**Comment by nitbeat** [comment]
What is different in teensy 3.2 ? is it the MCU being used there, or the platform itself ?

**Comment by focalintent** [comment]
The difference is the MCU - the teensy 3.2 is a 32-bit arm cpu running at 72-168Mhz, while the nano is an 8-bit avr cpu running at 16Mhz.  There's simply not enough spare cpu cycles on the avr to drive the WS2812 leds _and_ allow interrupts to process.
