### ISSUE TITLE
SPI Slave Select pin ???

### ISSUE THREAD

**Issue by Serveurperso** [FastLED/FastLED#516]
Documentation is pretty bad about this, where I can setup the slave select pin ?

https://github.com/FastLED/FastLED/wiki/SPI-Hardware-or-Bit-banging

**Comment by focalintent** [comment]
Fastled doesn’t use space select at all, since none of the supported led chipsets use it.  (Supporting doing that is part of a planned rewrite of the spi parts at some point, for folks who have wired up their own slave select hardware).

**Comment by Serveurperso** [comment]
I can't use my simple SPI multiplexer ? bad:(

**Comment by Serveurperso** [comment]
please support the basic 74HC595 chip !

**Comment by focalintent** [comment]
Supporting the *595’s requires driving the pwm in software with interrupts which is something I took out of the library years ago when I started supporting a mix of platforms. 

As far as slave select support - you can do it yourself by pulling your choice of slave select pin down low before calling FastLED.show().

**Comment by Serveurperso** [comment]
Thanks, you can close. Because I switch to colorduino a better hardware solution than shift register to drive the 8x8 matrix
