### ISSUE TITLE
WS2812B flickering blue

### ISSUE THREAD

**Issue by SilverBzH** [FastLED/FastLED#528]
Hello,

I am working on a project using ws2812b strip with smd5050 leds. In total i got 502 LEDs and I am controlling 502 them with my Arduino Uno R3 (Chinese version).

### Here is my issue:
The first 182 LEDs are turned off then from the 183 to the 502th one they are turned on in Red (I code for that). 
the issue is that: the LEDs in Red are flickering in blue sometimes.

### Connection

- The Ground is well connected to the arduino ans the dataline as well
- The strip is powering in 5V every meters/ two meters 
- The data line is connected in series

### Here is the code I am using (Arduino IDE)
`#include <FastLED.h>

#ifdef __AVR__
  #include <avr/power.h>
#endif

#define NUM_LEDS 502
#define DATA_PIN 6 

#define STRIP0 182 //3.25m
#define STRIP1 205      //0.30m
#define STRIP2 244      //0.40m
#define STRIP3 289      //0.65m
#define STRIP4 337      //0.75m
#define STRIP5 403      //0.8m
#define STRIP6 457      //0.90m
#define STRIP7 502     //1.1m

#define DELAYTIME 10

CRGB leds[NUM_LEDS];

void setup() {
  delay(3000); //Safety Power Up
  FastLED.addLeds<WS2812B,DATA_PIN,GRB>(leds,NUM_LEDS).setCorrection(TypicalSMD5050); //2812B
  FastLED.setBrightness(255);
  turnOn(CRGB::Black); //Initialiser toutes les LEDs
}

void loop()
{
  turnOnStripToStrip(STRIP0,STRIP1,CRGB::Red);
}

void turnOn(CRGB color)
{
  for(int i=0 ; i<NUM_LEDS ; ++i)
  {
    leds[i] = color;
  }
  FastLED.show();
}

void turnOnStripToStrip(int strip1 , int strip2, CRGB color)
{
  for(int i = strip1 ; i < strip2 ; ++i)
  {
    leds[i] = color;
  }
  FastLED.show();
}`

### Conclusion
Thanks for your help and feel free to ask me if anything is not clear enough !

**Comment by brendanmatkin** [comment]
See my comment in another issue. Maybe the same problem: https://github.com/FastLED/FastLED/issues/537#issuecomment-355669180
