### ISSUE TITLE
no beat function for +- waves

### ISSUE THREAD

**Issue by steeley** [FastLED/FastLED#529]
Needs a beatsin wave function that cycles around 0 and goes pos neg.

**Comment by kriegsman** [comment]
Just use subtraction.  Subtract a constant offset, half the range:

`int k = beatsin8( 60, 0, 100); /* range is 0..100 */
k = k - 50; /* range is now -50..+50 */
`

Make sure to use signed integers (not unsigned) and that the types you use are wide enough to hold your data. Signed 8-bit integers ("int8_t") can only hold -128..+127, and signed 16-bit integers ("int16_t" or sometimes just "int" on Arduino) can only hold -32768..+32767.

Thanks for using the library!  We only use github tickets for tracking bugs in the library.  For general programming help, and general discussions like this, please use the FastLED G+ group: http://fastled.io/+
