### ISSUE TITLE
Fastled chip timing

### ISSUE THREAD

**Issue by hamsafar** [FastLED/FastLED#541]
Hi,
In this class:
`class WS2812Controller800Khz : public ClocklessController<DATA_PIN, NS(250), NS(625), NS(375), RGB_ORDER> {};`

what is 252ns and 625 and 375 in this class?
According to ws2812 datasheet T0H is 350ns, T1H is 700ns, T0L is 800ns and T1L is 600 ns
Thanks

**Comment by focalintent** [comment]
The original WS2812 datasheets that I had done this off of years ago had T0H as being 250ns, TOL 1µs and T1H being 875ns and T1L being 375ns give or take.  The important part is to make sure the total timing is 1.25µs per bit which these timings are - the newer datasheets have different timings, however I'm not going to change the timings in the library until I get back to actively working on it and can do a full round of testing with different timings (the timings in here are based on hundreds of hours of writing/running tests and checking output w/scopes, etc...) 

As for the three numbers - call them T1, T2, and T3.  T0H is equal to T1, T0L is equal to T2+T3, T1H is equal to T1+T2 and T1L is equal to T3.  T1 is the point in time where the signal goes from high to low for a zero.  T1+T2 is the point in time where the signal _always_ goes to low (if it's already low from being a zero, this doesn't change anything), and T1+T2+T3 is the total amount of time that must pass before starting the next bit.  The timings are defined for how the code uses them.
