### ISSUE TITLE
change number of leds in sketch

### ISSUE THREAD

**Issue by dwc56** [FastLED/FastLED#543]
The number of leds is set in setup can you change it in the loop?

**Comment by tonton81** [comment]
i set it dynamically in one of my demos so yes

**Comment by dwc56** [comment]
what demo?

**Comment by tonton81** [comment]
fastled controller over i2c/spi/websockets

its quite a big project i worked on

**Comment by parmarravi** [comment]
How to change the number of leds dynamically?

**Comment by marmilicious** [comment]
@dwc56  @parmarravi   The FastLED library wasn't really designed to have NUM_LEDS be variable, but if you search here and in the G+ group you might find a few solutions.
The easiest work around is to define NUM_LEDS with the maximum number of pixels you'll ever light up, and then use a second variable which you can vary and use in your code as needed.
