### ISSUE TITLE
Teensy3.1 unusual behavior beyond ~60 leds

### ISSUE THREAD

**Issue by VoswijkC** [FastLED/FastLED#545]
I loaded up a very simple rainbow test, but the strip behaved rather unusual and i have no possible explanation as to Why.
-The entire string and code works perfectly fine with a normal arduino so the strip,Code and power supply aren't faulty.
-A small 24led string connected to the Teensy work well aswell. So my level shifter seems to be working normal too.
-Also works pretty well if the program is set to assume the strip is pretty small.
-when it is asked to add more than ~65 leds it goes haywire with flickering and whatnot. This is regardless if i only ask it to use a small portion of the string or all of it. Which suggests a problem within the software

Apparantly once i ask the library to add more than a certain amount of leds (around 60) on the Teensy it stops working properly with the set amount of leds turning off and the rest showing random colours. Perhaps there is a bug in the Fastled code itself?

This is with fastled release 3.1.6, arduino IDE 1.8.5,Teensyduino 1.4 (and 1.4.1-beta1)

**Comment by focalintent** [comment]
Try disabling interrupts and see if that helps.  See https://github.com/FastLED/FastLED/wiki/Interrupt-problems - the ws2813 changed some of the timings around reset, and the code hasn’t been fully updated to account for that (and probably won’t be for a while, still).

**Comment by VoswijkC** [comment]
Ah. that seems to do the trick! Did not know fastled allowed interrupts to be handled between each led on ARM devices.

Thank you very much for the assistance!
