### ISSUE TITLE
Select color from input CRGB::"value"

### ISSUE THREAD

**Issue by zombodotcom** [FastLED/FastLED#547]
is there a way to set the color from user input? 

```
if (txtMsg == "swipe") {
      Serial.print("What color?");
      color = Serial.readString();
      color = colorfix(color);
      clen = color.length();
      while (clen != 0)
      { for (int i = 0; i < NUM_LEDS; i++) {
          leds[i] = CRGB::color;
          FastLED.show();
          // clear this led for the next time around the loop
          leds[i] = CRGB::Black;
          delay(30);
        }

      }
    }
```

I want to be able to set CRGB:: "value"

**Comment by focalintent** [comment]
You have to do your own parsing of color names to color values.  There isn't anything in the library for that (the string tables to keep in memory/flash would be way to expensive for me to make that a standard part of the library)
