### ISSUE TITLE
Compiling errors with lib

### ISSUE THREAD

**Issue by oliverh57** [FastLED/FastLED#548]
Shows Error but doesn't prevent from running. 

```
C:\Users\olive\OneDrive\Documents\Arduino\libraries\FastLED-3.1.6/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.006

 #    pragma message "FastLED version 3.001.006"
                                      ^

**Comment by focalintent** [comment]
It's not an error, it's a message informing what version of FastLED is being compiled - see where it says message and note?  It's a bug in the arduino IDE that it highlights it as an error.
