### ISSUE TITLE
Esp32 crashes when connecting internet after FastLED.show() has been used

### ISSUE THREAD

**Issue by hutje** [FastLED/FastLED#554]
All processes that are used with wifi are not usable after one time using FastLED.show(). When I do use a wifi related function the esp32 crashes.
When I don't use FastLED.show() everything works just fine until I use it.

**Comment by focalintent** [comment]
@samguyer - thoughts?

**Comment by samguyer** [comment]
@hutje Which branch of FastLED are you using?

**Comment by samguyer** [comment]
Sounds like a problem with interrupts.

**Comment by hutje** [comment]
I am using ws2812. Now somebody told me to put the FASTLED_ALLOW_INTERRUPTS 0 before including the library.
Also without the interrupts, the timing of the leds is bad. Apparently there is another branch of this code where the timing is better for esp32.  https://github.com/samguyer/FastLED

**Comment by hutje** [comment]
But the main problem of not able to reconnect to internet is solved... Now I need to find a right timing

**Comment by hutje** [comment]
Solved it

**Comment by mkriegsman** [comment]
Glad to hear it, @hutje.  Any lessons learned that might be good to share with other folks?

**Comment by kriegsman** [comment]
Glad to hear it, @hutje.  Any lessons learned that might be useful to share with other people?

**Comment by hutje** [comment]
Yeah, I needed the library of @samguyer. Thanks man! The results 56 inch Digital Clock https://imgur.com/gallery/cJPW2

**Comment by kriegsman** [comment]
Looks great!
(Closing the ticket.)
