### ISSUE TITLE
How to fade?

### ISSUE THREAD

**Issue by raebel-christo** [FastLED/FastLED#555]
I am new to using this library. How do I fade the LEDs? Also how to control all LEDs at once?

**Comment by ryancasler** [comment]
Since Google+ is no more, I would really love to know how someone is supposed to ask a basic question now.  I've been trying to figure this out for 2 days and I'm really starting to lose it over here.  A simple answer to the question this person posed would have saved me a ton of trouble.

**Comment by fuse314** [comment]
Google+ was retired, the FastLED community has moved over to reddit:
[https://www.reddit.com/r/FastLED/](https://www.reddit.com/r/FastLED/)
