### ISSUE TITLE
Update wiki page Power notes to clarify

### ISSUE THREAD

**Issue by Cubox-** [FastLED/FastLED#556]
Hi,

I had a problem with my LEDs going haywire when using them through an external source, with the arduino powered with USB. Quick google search made me find the issue, I had to connect the external power ground with the arduino ground to fix it.

The power notes mention this, but I missed it with the wording of the sentence.

> "If your setup is USB-powered and having trouble, try powering your LED strips from an external (5v) power supply. Make sure to connect the Ground from the external power supply to the USB-based Ground. If your animation flickers and goes nuts when exclusively USB powered, but works fine with an external power supply, you were out of power."

My brain went to "If your setup is USB-powered and having trouble", and skipped this section.

I can't seem to find how to issue pull requests for wiki items, but wording this differently would have saved me hours of tinkering trying to find what the hell was wrong :)

No hard feelings, since the library is really awesome! But that's my suggestion.

**Comment by focalintent** [comment]
Updated
