### ISSUE TITLE
Attiny45 - undefined timer error - reproducible with RGBcalibrate example, DATA_PIN 3

### ISSUE THREAD

**Issue by cluelessperson** [FastLED/FastLED#56]
Compiling 'RGBCalibrate' for 'ATtiny45 @ 8 MHz'
RGBCalibrate.cpp.o:In function `CLEDController* CFastLED::addLeds<(EClocklessChipsets)4, (unsigned char)3, (EOrder)10>(CRGB const*, int, int)'
FastLED.h:undefined reference to`__cxa_guard_acquire'
FastLED.h:undefined reference to `__cxa_guard_release'
RGBCalibrate.cpp.o:In function`ClocklessController_Trinket<(unsigned char)3, 2, 5, 3, (EOrder)10, 50>::showRGBInternal_AdjTime(int, bool, int, unsigned char, unsigned char const*)'
clockless_trinket.h:undefined reference to `timer0_millis'
clockless_trinket.h:undefined reference to`timer0_millis'
clockless_trinket.h:undefined reference to `timer0_millis'
clockless_trinket.h:undefined reference to`timer0_millis'
clockless_trinket.h:undefined reference to `timer0_millis'
RGBCalibrate.cpp.o:B:\Dropbox\Programming\ARDUINO\libraries\FastLED\clockless_trinket.h:83: more undefined references to`timer0_millis' follow
Error creating .elf

**Comment by andig** [comment]
+1 for interest in attiny85 support. So much more compact than sticking a nano in ;)

**Comment by focalintent** [comment]
@andig there's already attiny85 support in there - and I know folks have gotten other attinys to work as well.  Personally, I'd rather use something like the LPC8xx - as compact as a tiny, but a full 32-bit arm cortex m0+ :)

**Comment by andig** [comment]
@focalintent really OT and I apologize. Didn't know about the LPC8xx thingies. Is there an Arduino platform that could be installed via boards manager? A pointer would be appreciated, thanks!

**Comment by focalintent** [comment]
No worries - LPC8xx support isn't officially in the codebase yet (still working on that) - that said, LPC programming is a bit more involved than your standard arduino environments (and, in fact, I don't believe there's arduino IDE support for the LPC8xx)
