### ISSUE TITLE
WS2813 Pin Out and Bug

### ISSUE THREAD

**Issue by KangKamal** [FastLED/FastLED#566]
i'm using ws2813 and some people says don't connected pin Di1, and just connect pin Di2 to digital arduino,. it's working but my first and second led are as once... so first led and second led assign id 0 (first led and second led = id0), how to fix it to make first led is id 0, second led is id 1, etc...

**Comment by focalintent** [comment]
Ask on the g+ community - http://FastLED.io/+  - you are more likely to run across current WS2813 users who can help you with your wiring.  I prefer to keep the FastLED issues limited to library bugs/enhancements/tracking.
