### ISSUE TITLE
How did you push APA102 to 24MHz?

### ISSUE THREAD

**Issue by t-walker-wei** [FastLED/FastLED#577]
I use FastLED for my APA102 led strip, but it seems very slow.I want to know how you make it so fast.Thanks.

**Comment by marmilicious** [comment]
The github bug tracker here is mostly just for bugs in the library itself.  For general discussions, help, and how-to, check out the G+ FastLED discussion group here: http://fastled.io/+

@t-walker-wei  When you post please tell what controller you are using, and put your code on gist.github.com and share the link to the code.  Someone there should be able to give you some tips.
