### ISSUE TITLE
Feature request: add built-in ability to blink/flash

### ISSUE THREAD

**Issue by sensboston** [FastLED/FastLED#585]
I know, it's a pretty easy to make on LED blink; blinking many LEDs are also not too complicated. BTW, will be good to have this functionality built-in in library somehow. I'm not talking about changing CRGB structure (too many possible side effects) but it should be safe & useful way to add periodically blinking LEDs functionality to the library.

**Comment by focalintent** [comment]
Not really - the library mostly focuses on color management and writing out data to actual LEDs, with some utility functions to make writing patterns/animations easier.  What I'm trying to stay away from doing, outside of the example projects, is having the library itself manage animation directly - that's a task for a higher level library.
