### ISSUE TITLE
wrong color on a code for a rainbow

### ISSUE THREAD

**Issue by Hexxdroid** [FastLED/FastLED#588]
[hello,] i just bought an addresable ledstrip, and want to make a rainbow wave. im using arduino nano to controll and power the led.

i have tried different option such as neopixel and it still also have the same problem.
the led that im using is SK6812, but people said that is works as WS2812B.

this is the color that i have:
![jpeg_20180328_192955](https://user-images.githubusercontent.com/37915729/38116127-19524d3e-33af-11e8-9818-38277deb4ed0.jpg)

this is the color that i want: 
![screenshot_1](https://user-images.githubusercontent.com/37915729/38116156-34462f98-33af-11e8-8301-c6c358fb38f0.png)

here is the code that im using: (i would appreciate it alot for helping me)

#include <FastLED.h>

#define PIN 4
#define NUM_LEDS 160

CRGBArray<NUM_LEDS> leds;
uint8_t hue[NUM_LEDS];

void setup() {
  FastLED.addLeds<NEOPIXEL, 4>(leds, 160);
    for (int i = 0; i < NUM_LEDS; i++) {
      hue[i] = 255 / NUM_LEDS*i;
      
      }
      
}

void loop() {  
  for (int i = 0; i < NUM_LEDS; i++) 
  {
    leds[i] = CHSV(hue[i]++, 255, 255);
  }
  
  FastLED.show();
  delay(20);
 
}

**Comment by JosefKuchar** [comment]
First of all try RGB, if red is red, green is green, blue is blue. If not, you have different color order (it's GRB for me). Look at this https://github.com/FastLED/FastLED/wiki/Rgb-calibration

**Comment by Hexxdroid** [comment]
the colors are correct , I have done that.

**Comment by Hexxdroid** [comment]
I followed a guide to see wich chipset my led have. (there was some problem here)
but the colors where wrong and if i tried diffrent RGB ordering(1 red led, 2 green led & 3blue led) and it there was even more problem.

so i tried only 1 led at the time . I started with red
and my red ordering was blue si no proble there

the i do the 2 next and there was more problem
![dsc_0695](https://user-images.githubusercontent.com/37915729/38193332-e156a360-3671-11e8-9e5f-d52d1cfafea7.jpg)
the led should be  1 red en 2 green

the i tried all of them again and i got this
![dsc_0696](https://user-images.githubusercontent.com/37915729/38193367-04183bde-3672-11e8-8ddd-437a1ff6d16a.jpg)

some of the led wont even show up...

**Comment by JosefKuchar** [comment]
I successfuly compiled my sketch with SK6812 declaration, you can try it

**Comment by Hexxdroid** [comment]
I have RGBW led, is this like the problem of it?

**Comment by Hexxdroid** [comment]
@JosefKuchar I don't understand you. did you send code?

**Comment by JosefKuchar** [comment]
@Hexxdroid Looks like RGBW strips are not supported yet #482

**Comment by Hexxdroid** [comment]
well thank you very much for helping me.
I was at a lost and you have brght me up thank you! you have my eternal gratitude!
