### ISSUE TITLE
Parallel? How to make 10*150 WS2811?

### ISSUE THREAD

**Issue by alonperl** [FastLED/FastLED#593]
Hi, I have just found this wiki https://github.com/FastLED/FastLED/wiki/Parallel-Output
I wonder how can I use this OctoWS2811 lib to create 10 lines parallel? 
and is it possible with 150 each line?

**Comment by marcmerlin** [comment]
the issue tracker is not for support requests, you should use the G+ community

**Comment by focalintent** [comment]
OctoWS2811 is only 8 lines - you can use WS2811_PORTDC to get up to 16 lines of parallel output without using the OctoWS2811 library as a backend,.
