### ISSUE TITLE
Issues with IR remote and FastLED

### ISSUE THREAD

**Issue by BigKMac** [FastLED/FastLED#601]
I'm trying to set up a string of WS2812b LED's to change color/ brightness using an IR remote and the IRLib2 library.

I think i have everything working the way i need it to as far as getting the arduino to change the colors/ brightness of the LED based on different button inputs. However, after a random amount of time, the board just stops accepting inputs and will remain on whatever the last color set was. Sometimes it will work for several minutes and lets me changes settings MANY times - other times it only makes it about 30 seconds and freezes. The only way to fix the issue is to unplug the board from the power source and plug it in again to restart it.

Any input or a push in the right direction would be GREATLY appreciated.

**Comment by focalintent** [comment]
Start here: https://github.com/FastLED/FastLED/wiki/Interrupt-problems

**Comment by pille** [comment]
my workaround is to distinguish two modes: LED and IR and never have them run at the same time in `loop()`. 

i've tested this with demoreel100, by putting this at the beginning of `loop()`:
```cpp
  if (irrecv.decode(&ir_results)) {
    if (ir_results.value != 0xFFFFFFFF) {
      time = millis();
      Serial.print(ir_results.value, HEX);
      Serial.print(" at ");
      Serial.print(time);
      Serial.println(" mode: IR");
      
      FastLED.setBrightness(BRIGHTNESS/4);
      FastLED.show();
      
      irrecv.resume(); // Receive the next value
      
      while (millis()-time < 2000) {
        if (irrecv.decode(&ir_results)) {
          if (ir_results.value != 0xFFFFFFFF) {
            Serial.println("");
            Serial.println(ir_results.value, HEX);
            time = millis(); // prolong IR mode
            //time = 0;  // force LED
          }
          irrecv.resume(); // Receive the next value
        }
      }
      if (time != 0) Serial.println("timeout");
      Serial.println("mode: LED");
      FastLED.setBrightness(BRIGHTNESS);
    }
    irrecv.resume(); // Receive the next value
  } 
```

so what this does is:
1) start in LED mode
2) when a IR code is received, goto IR mode (LED brightness reduced as feedback)
3) in IR mode the first code is thrown away, as it is probably garbage (recorded in LED mode). 
4) now in regular IR mode, just scan for codes and reset the timeout after each success
5) when timeout hits (2sec) switch back to LED mode

this example just outputs the IR codes to serial console. 
in order to run this, you'll need to modify demoreel100 boiler-plate code:
```cpp
#include <IRremote.h>
#define IR_PIN     11

IRrecv irrecv(IR_PIN);
decode_results ir_results;
unsigned long time;   // millis
```

and in `setup()`:
```cpp
Serial.begin(9600);
Serial.println("Enabling IRin");
irrecv.enableIRIn(); // Start the receiver
Serial.println("Enabled IRin");
```

**Comment by ON4AVJ** [comment]
Thanks, this solution helped me a lot

**Comment by keshavmix** [comment]
> I'm trying to set up a string of WS2812b LED's to change color/ brightness using an IR remote and the IRLib2 library.
> 
> I think i have everything working the way i need it to as far as getting the arduino to change the colors/ brightness of the LED based on different button inputs. However, after a random amount of time, the board just stops accepting inputs and will remain on whatever the last color set was. Sometimes it will work for several minutes and lets me changes settings MANY times - other times it only makes it about 30 seconds and freezes. The only way to fix the issue is to unplug the board from the power source and plug it in again to restart it.
> 
> Any input or a push in the right direction would be GREATLY appreciated.

I found below solution which is working fine for me. However it is not 100% reliable but due to hardware limitations, this solution can be acceptable.
`IRrecv irrecv(RECV_PIN);
decode_results results;

loop() {

    /* do effects here */

    while (!irrecv.isIdle());  // if not idle, wait till complete

    if (irrecv.decode(&results)) {  
        /* respond to button */

        irrecv.resume(); // Set up IR to receive next value.
    }

    FastLED.show(); 
}`
