### ISSUE TITLE
Too little power causes flickering and random effects.

### ISSUE THREAD

**Issue by DaleB-1** [FastLED/FastLED#603]
Hi Guys,
I love your work with the FastLED library. I have been building the sound sensitive lamp found at Instructibles and one problem and solution I encountered that I didn't see listed in the FAQ was how insufficient power can affect a light strip. When I had my light strip (72 LEDs), Arduino Nano and sound sensor powered by the USB hub connected to my PC, everything worked perfectly. When I disconnected from the PC and used two 1A phone chargers for power everything went bad. Flickering, LEDs lighting up at random, strange patterns etc. When I powered the lamp with a 4A power supply, everything went back to normal. I think people (including me) underestimate the power requirement for an LED strip. Just thought you might want to add this to the FAQ.
Keep up the good work - Dale

**Comment by focalintent** [comment]
https://github.com/FastLED/FastLED/wiki/Wiring-leds#a-word-on-power already talks about power and the effects of too little power and https://github.com/FastLED/FastLED/wiki/Chipset-reference has some power numbers for various chipsets.
