### ISSUE TITLE
fill_rainbow() with negative led count

### ISSUE THREAD

**Issue by krisha** [FastLED/FastLED#613]
what do you think about supporting a negative count on fill_rainbow() function for reverse direction?

**Comment by marmilicious** [comment]
@krisha  The range for hue is 0-255.   Subtracting below 0 will wrap around 255 (and then you can keep subtracting and go down from there).
See this post for some more info and examples:
https://plus.google.com/100542328320334100166/posts/Y5BdWFEvfo1

**Comment by chrisparton1991** [comment]
Sounds logical to me. Are you happy for the issue to be closed, @krisha?

**Comment by krisha** [comment]
yes, think this is enough. thx!
