### ISSUE TITLE
Servo/Interrupts Solution

### ISSUE THREAD

**Issue by J3698** [FastLED/FastLED#620]
In the wiki under "Interrupt problems," I see that 

> If the lack of serviceable interrupts is causing problems for servos, you are out of luck - make one of the hardware switches mentioned above, or use a dual-controller setup where one avr talks to servos, and the other avr talks to the leds.

However Adafruit made a new servo library to fix this called TicoServo that works with a bunch (not all) of the Arduino boards, perhaps that should be mentioned.
https://learn.adafruit.com/neopixels-and-servos/the-ticoservo-library

**Comment by focalintent** [comment]
Added to the wiki

**Comment by damiannogueiras** [comment]
The library [PWMServo](https://platformio.org/lib/show/600/PWMServo) work well with FastLed.
Servo sporadic movements disappear.
