### ISSUE TITLE
Arduino Zero millis() and FastLED.delay() are 4x slower with WS2812B

### ISSUE THREAD

**Issue by lights0123** [FastLED/FastLED#633]
I have started to play around with the native FastLED support for the Arduino Zero (instead of using FastLED's math with [Adafruit's ZeroDMA](https://github.com/adafruit/Adafruit_NeoPixel_ZeroDMA)). I loaded the ColorPalette example, and noticed that the framerate and update frequency were ¼ of the actual speed. Changing `FastLED.delay(1000 / UPDATES_PER_SECOND);` to `FastLED.delay(1000 / UPDATES_PER_SECOND / 4);` and `uint8_t secondHand = (millis() / 1000) % 60;` to `uint8_t secondHand = (millis() *4 / 1000) % 60;` resolved the issue. This only occurs when FastLED is being constantly updated: changing `FastLED.delay` to `delay` resulted in exactly 1 FPS, not ¼ FPS.

This issue occured with a strip of 240 WS2812Bs and an off-brand Arduino Zero using the same board definition and bootloader.

**Comment by focalintent** [comment]
Yeah - the SAMD code doesn't attempt to try to fix the clock - if interrupts are enabled then millis should update as expected.
