### ISSUE TITLE
ESP32 Flickering and inconsistencies even with interrupts disabled

### ISSUE THREAD

**Issue by HinamoreCh4n** [FastLED/FastLED#637]
Hello, im trying to port a esp8266 sketch that syncs ws2812b pixels to music, now it does kind of work on my esp32 but there are major flickering issues and animation inconsistencies, the framerate also sometimes drops to 1 every second or two. i suspect this is because im fetching the led information over wifi but it works perfectly fine on a esp8266. Heres the sketch: https://hastebin.com/ebukadurow.cpp

**Comment by marmilicious** [comment]
For the ESP32 try using the FastLED fork by @samguyer 
https://github.com/samguyer/FastLED

**Comment by focalintent** [comment]
Which has now been merged into master/FastLED 3.2
