### ISSUE TITLE
The syntax is not highlighted

### ISSUE THREAD

**Issue by HardProg** [FastLED/FastLED#642]
I can not open Pull requests, so I open Issue
The syntax is not highlighted:
setMaxPowerInVoltsAndMilliamps
setMaxPowerInMilliWatts
setMaxRefreshRate
clearData
setDither

### clearData	KEYWORD2
setMaxPowerInVoltsAndMilliamps	KEYWORD2
setMaxPowerInMilliWatts	KEYWORD2
setMaxRefreshRate	KEYWORD2
setDither	KEYWORD2

**Comment by ChristofKaufmann** [comment]
Also `CRGBArray` is missing. Somehow your pull request #643 is broken and should probably be closed. I will open a new one.
