### ISSUE TITLE
WS2812B doesnt keep colour

### ISSUE THREAD

**Issue by M3gaFr3ak** [FastLED/FastLED#65]
when I color my led w/ a single color (red/green/blue) and then delay(time) after FastLED.show(), it stays on between the show calls. But if i use mixed colors (0xFFFF00), it turns off when the delay starts and goes back on when it FastLED.show()s again!

**Comment by arturogomezle** [comment]
Hi, did you got this fixed?

I'm having the same issue with a single WS2812B LED, It won't keep the white color on.

Any sugestions?

Thanks!

**Comment by arturogomezle** [comment]
Never mind, I added the ".setCorrection" extention and it worked! Thank you again!
