### ISSUE TITLE
ARDUINO_SAMD_ZERO extra/different hardware SPI with SERCOM1

### ISSUE THREAD

**Issue by DylanMeng** [FastLED/FastLED#652]
Hello, currently on Arduino zero the hardware SPI for FastLed is defined by digital pin 24 and 23
#define SPI_DATA 24 
#define SPI_CLOCK 23

The problem is when you have other devices on the same SPI. The LED strip will react to any data due to missing chip select.

To get around this problem I am trying to create another hardware SPI on a different SERCOM (SERCOM1).

I successfully created another SPI on SERCOM1 (tested and fully working at 8Mhz)
```
SPIClass mySPI (&sercom1, 12, 13, 11, SPI_PAD_0_SCK_1, SERCOM_RX_PAD_3);
pinPeripheral(11, PIO_SERCOM); 
pinPeripheral(12, PIO_SERCOM); 
pinPeripheral(13, PIO_SERCOM);
```

But the problem is that I am not sure how to link this new hardware SPI to the Fasted library.

Any ideas on how I could do that?

**Comment by focalintent** [comment]
FastLED currently doesn't have any hardware SPI support for the D21 - so you can just tell it to use any pair of pins for clock/data and it will fall back to bitbang'd SPI.
