### ISSUE TITLE
Support for APA-102 / APA-104 chipsets

### ISSUE THREAD

**Issue by robot-head** [FastLED/FastLED#66]
It would be awesome if you could implement support for APA-102! These strips are very nice and achieve 144 led/meter density

**Comment by theDiverDK** [comment]
How to use Fastled for APA104, the https://github.com/FastLED/FastLED/releases says it is supported, but i can only in the code find a apa102controller.

Do i just use that?

**Comment by theDiverDK** [comment]
I see the APA104 is supported as well, can anyone confirm it works?

**Comment by focalintent** [comment]
Apa104 is basically a ws2812 clone.  And yes, it is in there.

**Comment by theDiverDK** [comment]
Thanks Focalintent for clarifying it :)

**Comment by Linda-sfleds** [comment]
Just for completion here is a link to the APA102 chip, which is a similar as WS2812B,but much better:
http://www.sfleds.com/Blog/150.html#.VlWHKC6MW1Y
