### ISSUE TITLE
Color Correction for multiple LEDs on same data pin

### ISSUE THREAD

**Issue by jbud** [FastLED/FastLED#660]
I have 2 strips wired together on the same data pin, both are TM1803 however the controllers seem to have a slight difference, the color order on the first strip is GBR, the second is RBG. Is there a way to correct this?

**Comment by focalintent** [comment]
No, in this case you will have to do the R/G swapping by hand for the affected leds before calling show and then undo it afterwards.  Ordering in the library is done on a per pin basis and there’s no provision for switching it partway through (and isn’t going to be)
