### ISSUE TITLE
AnalogOutput brightness is 8bit, but seems to need 10bit

### ISSUE THREAD

**Issue by demlak** [FastLED/FastLED#664]
Hi,
when i play with this example: https://github.com/FastLED/FastLED/blob/master/examples/AnalogOutput/AnalogOutput.ino
On my Wemos D1 Board, the brightness is not at the maximum.

I mesured the voltage o the output. it is at ~0,84V instead of 3,3v that it should have.

well.. 0,84v is 1/4 of 3,3v
and 256 is 1/4 of 1024

so it seems to me, that the wemos d1 has a 10bit pwm output, but fastled just puts 8bit to the analog pins. 

any idea on how to fix this?

**Comment by CyanoFresh** [comment]
same

**Comment by focalintent** [comment]
FastLED is currently 8 bit internally - you could, for now, multiply the values by 4 before writing them out in the analog outout example (just make sure you put the values in an int so that it doesn’t get cut off at 8 bits).  (In the future FastLED will be either 8 or 16 bit internally, which will make it more trivial to support 10/12/16 bit outputs directly).

**Comment by CyanoFresh** [comment]
yep, but multiplying is not smooth for rainbow animation

**Comment by demlak** [comment]
8bit is not smooth for anything.


btw. i canceled the use of FastLED for my Project. And i bought a PCA9685 to get smooth 12bit output for my analog LED Stripes. I will see, what software i will use to drive this.

**Comment by chrisparton1991** [comment]
@demlak I've found 8 bits to be smooth enough for my use cases.

Also, please keep in mind that @focalintent has given us countless hours of his time and effort for free, so politeness is the least we can offer in return :)

**Comment by demlak** [comment]
I did not and will not discredit any work of any fastled member

**Comment by focalintent** [comment]
He’s right - 8bit is pretty poor - for my own work I do all my higher level color work in 16bit and then convert down to 8-bit hsv/rgb at the last moment.  This is why I’m adding support for 16-bit rgb and hsv pixels in addition to the current 8-bit CRGB/CHSV as part of the RGBW rewrite - they will convert down to 8/10/12 bit as necessary depending on your output device.

**Comment by marmilicious** [comment]
Oooh, that sounds excellent @focalintent

**Comment by focalintent** [comment]
This'll happen by default once FastlED supports > 8 bit color/output work.
