### ISSUE TITLE
APA102 and fill_rainbow()

### ISSUE THREAD

**Issue by MorganBarbier** [FastLED/FastLED#674]
Hi everybody,

My first experience with electronic stuff and leds strip! (5m of 30leds/m => 150 leds) ( [https://fr.aliexpress.com/item/1m-2m-4m-5m-5V-APA102-digital-smart-rgb-led-pixel-strip-light-30-32-60/32794298843.html?spm=a2g0s.9042311.0.0.40696c37u2EY2e](url) [https://fr.aliexpress.com/item/LAFVIN-De-Base-Starter-Kit-pour-Arduino-UNO-MEGA-2560-avec-Tutoriel/32869624633.html?spm=a2g0s.9042311.0.0.40696c37u2EY2e](url) )

What I see: quickly a rainbow but the blue pixels become either red or green... so it is a mix between green and red.

What I did:
using FastLED v3.2.1

+ -> 5V power Arduino supply
- -> GND Arduino
CLK -> pin 5 
DAT -> pin 6 
(5 and 6 to enjoy PWM if necessary...)

Since some colors changed into rainbow I tested different things, one of them is really strange for me:

```
#include <FastLED.h>

  #define NUM_LEDS 150
  #define DATA_PIN 6
  #define CLOCK_PIN 5

  #define COLOR_ORDER BGR

  CRGB leds[NUM_LEDS];


  void setup()
  {

       FastLED.addLeds<APA102, DATA_PIN, CLOCK_PIN, BGR>(leds, NUM_LEDS);
       fill_rainbow(leds, NUM_LEDS, 128);
       FastLED.show();
  }

  void loop()
  {

  }
```

and after some seconds some blue leds becames either red either green....

My questions are:
 - is it a bug of FastLED?
 - I did a mistake in electronic?
 - I did a mistake in programming?
 - My LEDs strip is dead?

thank you for your help!!!!

**Comment by marmilicious** [comment]
What if you move the fill_rainbow and Fast.LED.show lines out of setup and into the main loop?

Also, how are you powering your pixels?

Probably not related, but did you run the FastLED RGBCalibrate example here:
https://github.com/FastLED/FastLED/tree/master/examples/RGBCalibrate
