### ISSUE TITLE
ESP32 IRAM interrupthandler

### ISSUE THREAD

**Issue by edjeed** [FastLED/FastLED#676]
The function:
Interrupthander for the ESP32 (using RMT) is placed in IRAM, but calls functions that are not in IRAM.
The result of this is that sometimes errors occur, and the leds are not being updated anymore.

The documentation states:
```
Interrupt handlers must be placed into IRAM if ESP_INTR_FLAG_IRAM is used when registering the interrupt handler. In this case, ISR may only call functions placed into IRAM or functions present in ROM.
```

**Comment by kriegsman** [comment]
Thanks for opening this ticket.  What are your thoughts, @samguyer ?

**Comment by marcmerlin** [comment]
@edjeed in the meantime did you try changing the driver to use IRAM and does it work better for you? If so, submit a pull request if Sam is too busy to look at this.
