### ISSUE TITLE
attiny44 not enough memory

### ISSUE THREAD

**Issue by helenchg** [FastLED/FastLED#677]
Is there another way of looping through the dotstar LEDS without using the CRGB leds[NUM_LEDS];  array?
I am trying to control 72 APA102 LEDs, but when I tried to upload the code to the attiny44 using the Arduino IDE, it says low memory. I lowered the NUM_LEDS to 32 and it worked but I would like to control the entire strip.

**Comment by focalintent** [comment]
Not with FastLED, no - its controllers are frame, not stream, based.

**Comment by marcmerlin** [comment]
@helenchg do you mind resolving this issue?
Basically you need a more powerful microcontroller with more RAM. An ESP8266 would work fine and only costs $3 or so.

**Comment by helenchg** [comment]
I just changed my chip to an T84.
