### ISSUE TITLE
WS2812B Show only one color

### ISSUE THREAD

**Issue by dzuljo** [FastLED/FastLED#685]
Hi
I work with esp8266-fastled-webserver
With APA102 everything is good.
With WS2812B i have problem,only one color is showing.
example:
RGB green is working
GRB red is working
GBR blue is working
WS2812B pass the test but i have problem with sketch.
Microcontroler is Nodemcu
Some sugestion ?

Thanks

**Comment by marcmerlin** [comment]
Have you used the simple demo examples that come with FastLED to see if colors work there?
