### ISSUE TITLE
Sample defines brightness then ignores value

### ISSUE THREAD

**Issue by CyborgShadow** [FastLED/FastLED#688]
https://github.com/FastLED/FastLED/blob/8f2e86434b2bfa4d6178622ca3745a68303f8b00/examples/ColorPalette/ColorPalette.ino#L5

In this same, brightness is defined on line 5.

Brightness is then ignored on line 63 (https://github.com/FastLED/FastLED/blob/8f2e86434b2bfa4d6178622ca3745a68303f8b00/examples/ColorPalette/ColorPalette.ino#L63)

All values should use the defined brightness.

**Comment by focalintent** [comment]
Not in this case - no - the BRIGHTNESS define on line 5 is used set the global brightness on line 41.  The brightness on line 63 is only used as a passed in variable to ColorFromPalette - which doesn't have anything to do with the global brightness, but rather is a scaling value for the color that one is looking up in a palette.
