### ISSUE TITLE
FastLED + muxShield

### ISSUE THREAD

**Issue by StefanoMancuso** [FastLED/FastLED#689]
Hello! I'm trying to use multiple led strips with multiple sensors, so I got the Mux Shield II with 3 lines of 16 pin I/O (48 I/O total).
Is it possible to set the data pins as some pins of the Shield? Probably I have to change something inside the library, but I don't know where.
The muxShield library has a method for get an output that is:

`muxShield.digitalWriteMS(line,pin,value)`

Could someone help me to fix this issue? Thank you

**Comment by focalintent** [comment]
No - FastLED currently doesn't allow working through a mux shield - there's no way to get the timings tight enough
