### ISSUE TITLE
Changing LEDS freezes I2C connection

### ISSUE THREAD

**Issue by zzxjl1** [FastLED/FastLED#692]
I‘m currently using esp8266 as a master and arduino nano is a slave, i seems to be fine when i leave it idle, but when there is some light effects going on on my arduino nano the connection freezes and never recover.
NOTE: It won’t have the same issue on my esp8266，is this a performance problem？

**Comment by focalintent** [comment]
I don't know - I think it depends on how i2c is being used and whether or not you can set things up to flush/ignore a bunch of data from i2c.
