### ISSUE TITLE
Support ItsyBitsy M4

### ISSUE THREAD

**Issue by sandman15951** [FastLED/FastLED#693]
I am trying to use FastLED with an ItsyBitsy M4.  I made the edits to the 3 .h files discussed in #662 (in fact I replaced the entire library to be safe).  The edits fixed the errors I was getting, however I am still getting some new errors.  I get them even on the blink sketch.

What causes these errors is the FastLED.addLeds function

 ```
`Arduino: 1.8.7 (Windows 10), Board: "Adafruit ItsyBitsy M4 (SAMD51), Enabled"

In file included from C:\Users\gbkic\Documents\Arduino\Blinkv2\Blinkv2.ino:1:0:

C:\Users\gbkic\Documents\Arduino\libraries\FastLED/FastLED.h:14:21: note: #pragma message: FastLED version 3.002.001

 #    pragma message "FastLED version 3.002.001"

                     ^

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s: Assembler messages:

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:655: Error: invalid register list to push/pop instruction -- `pop {r4,r5,r6,r7,r8,r9,r10,fp,pc}'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:729: Error: lo register required -- `ldr pc,[sp],#4'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:767: Error: instruction not supported in Thumb16 mode -- `subs r0,r0,r3'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:884: Error: instruction not supported in Thumb16 mode -- `adds r2,r2,#1'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:886: Error: unshifted register required -- `and r2,r2,#7'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:888: Error: unshifted register required -- `tst r2,#1'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:894: Error: Thumb does not support conditional execution

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:895: Error: Thumb does not support conditional execution

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:898: Error: instruction not allowed in IT block -- `lsls r1,r2,#30'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:899: Error: IT falling in the range of a previous IT block -- `itt mi'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:900: Error: Thumb does not support conditional execution

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:902: Error: Thumb does not support conditional execution

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:905: Error: instruction not supported in Thumb16 mode -- `lsls r2,r2,#29'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:907: Error: Thumb does not support conditional execution

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:910: Error: instruction not allowed in IT block -- `adds r3,r3,#16'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:928: Error: instruction not supported in Thumb16 mode -- `adds r3,r3,#1'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:945: Error: instruction not supported in Thumb16 mode -- `subs r1,r1,#1'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:950: Error: instruction not supported in Thumb16 mode -- `subs r3,r3,#1'

C:\Users\gbkic\AppData\Local\Temp\cc0VJQ5s.s:957: Error: instruction not supported in Thumb16 mode -- `adds r2,r2,#1'

exit status 1
Error compiling for board Adafruit ItsyBitsy M4 (SAMD51).
```
`

**Comment by AzureEmpyrean** [comment]
I have also gotten a similar issue when compiling for the ItsyBitsy M4

**Comment by marcmerlin** [comment]
not quite what you want to hear, but seems to me that it's an unsupported architecture and until someone (you?) submits a pull request with clean support to add it, it won't work. Maintainers don't have all hardware available out there, and do rely on outside contributors to add support.

**Comment by manitou48** [comment]
I got FastLED working for SAMD51 (both adafruit itsbitsy and feather express).  I got rid of compile errors for itsbitsy, but only tested on M4 feather express using both neopixel and dotstar strips and onboard neopixel. Changed files are at
https://github.com/manitou48/samd51/tree/master/FastLED-m4

**Comment by devoh747** [comment]
Can a new Arduino library be pushed out for FastLED?  I'd love to have the SAMD51 support.

**Comment by s-light** [comment]
@manitou48 would you be able to fork the FastLED and create a branch with your modifications?
and then make a pull-request here on github?
i am not an maintainer here - so i can't accept/merge anything
but its the easiest way for the maintainers to check if your changes fit in the concept -
and this way most likely to get merged.

additionally i had a short look through the releases and fount that in [3.1.8](https://github.com/FastLED/FastLED/compare/3.1.8...master)
there was already a commit that states [*Enable SAMD51 (ARM Cortex M4) Support*](https://github.com/FastLED/FastLED/commit/c22a57f7e2402c099deaa20824a14a3a9a48f789)
so would be good to search a little bit more and check to also include the correct pin-mappings (if they are needed)

@devoh747 if it is merged it will take some time till a release is generated.
but if there is a branch / pullrequest - you have the option to manually install the library to test / use it!

**Comment by devoh747** [comment]
I have forked @manitou48's changes and issued pull request #803. It's my first PR, so let me know if it's ok. I did test his changes and they work great on my itsyBitsy M4 with a string of 60 WS2812's.

**Comment by s-light** [comment]
in my last project i used the current master (with your merged pullrequest) on a ItsyBitsy M4 in combination with a String of 3*144=432 APA102 Pixels - worked nicely!
it think with this we can close this issue?!

**Comment by devoh747** [comment]
I agree. It appears to be working fine.

**Comment by marcmerlin** [comment]
@sandman15951  yes, please close the issue, we can't do it for you :)
