### ISSUE TITLE
First LED not working (WS2813)

### ISSUE THREAD

**Issue by cyberponk** [FastLED/FastLED#699]
I have hooked up a WS2813 strip and the first LED of the strip never comes on (not a faulty LED problem).

I think it might be a problem with the leds[0] being skipped in the loop? I am looking at the code but having a hard time figuring out how it works.

EDIT: I figured that I have to connect both data cables (not just one of them) to the arduino output pin. That fixed it.  I´ll leave this here for future reference.

**Comment by spattinson** [comment]
Thanks, I'm having the same problem and found this. ws2813 has redundancy so one failed led will not cause a problem with the rest of the strip as long as there are not two failed leds together. Thats what the two data lines are for. At least thats my understanding, not tested.
