### ISSUE TITLE
LED "skipping"

### ISSUE THREAD

**Issue by Spajker7** [FastLED/FastLED#702]
Hi, I am using an ESP8266 with a 120 led WS2812B strip. 

I made a simple sketch that looks like this
```
int mode0step = 0;

void loop() {
	for(int i = 0; i < NUM_LEDS; i++) {
		leds[i].red = 0;
		leds[i].green = 0;
		leds[i].blue = 0;
	}

	leds[mode0step].red = 255;
	leds[mode0step].green = 0;
	leds[mode0step].blue = 0;

	FastLED.show();

	mode0step++;

	if(mode0step >= NUM_LEDS) {
		mode0step = 0;
	}
			
	delay(100);
}
```

My problem is that as the led "moves" it'll randomly skip ( like the index is bad ) and then go back to the correct led.
For example, lets say that LED 5 blinks, The next LED to blink should be LED 6, but sometimes, it'll skip to a random LED on the strip, lets say LED 80, before going back to LED 7.

What could be causing this issue? Is my led strip bad?

**Comment by marcmerlin** [comment]
typical issues
1) bad wire (loose or too thin for how long you're going) / cross talk between the wiring (if more than 50cm let's say, you should cross signal and ground in twisted pair)
2) low/bad voltage (you are sending 3.3V when the strip wants 5V and it works on 3.3V most of the time).
