### ISSUE TITLE
CRGB::maximizeBrightness() causes Divide By Zero error with color Black

### ISSUE THREAD

**Issue by K1ngjulien** [FastLED/FastLED#704]
The function does not check if all of the color channels are zero and therefor tries to divide by zero when maximizing the brightness.

https://github.com/FastLED/FastLED/blob/8f2e86434b2bfa4d6178622ca3745a68303f8b00/pixeltypes.h#L477

**Comment by kriegsman** [comment]
Thank you; I’ll take a look, should be quick. Much appreciated.
