### ISSUE TITLE
Add RFduino Support

### ISSUE THREAD

**Issue by Squeegy** [FastLED/FastLED#72]
Anyone ever tried to compile FastLED for an RFduino? This is an ARM chip, which I thought was supported.

When I `#include <FastLED.h>` I get a lovely:

    In file included from /Users/alex/Documents/Arduino/libraries/FastLED/controller.h:4:0,
                     from /Users/alex/Documents/Arduino/libraries/FastLED/FastLED.h:16,
                     from sketch_sep03a.ino:1:
    /Users/alex/Documents/Arduino/libraries/FastLED/led_sysdefs.h:21:20: fatal error: avr/io.h: No such file or directory
     #include <avr/io.h>
                        ^
    compilation terminated.

Other sketches seem to compile fine without the FastLED library.  I upgraded to 2.1 to see if that would fix it, but no luck.

You shouldn't need a physical unit to compile, you can install the RFduino support to Arduino 1.5.x as described here:
http://www.rfduino.com/wp-content/uploads/2014/04/RFduino.Quick_.Start_.Guide_.pdf

Am I doing something wrong or is this chip not supported for some reason?

**Comment by focalintent** [comment]
It's on the 3.1 branch.
