### ISSUE TITLE
very low speed >60 LEDS

### ISSUE THREAD

**Issue by lyon470** [FastLED/FastLED#775]
Hello,
I have an teensy 3.2 an run the ArrayOfLedArrays demo.
As soon as i put the num leds higher the Output Speed gets very slow.
The Interrupt order have i already tested.

Any other Solutions ?

**Comment by focalintent** [comment]
This is likely just math.  So with the 3 strips at 60 leds - it takes 5.4ms to call FastLED.show().  In addition, there's a delay(100) in there after each time FastLED.show() is called - so each dot takes 105.4ms in total.  To show all 180 dots would take ~19 seconds.

Now - if you make that 120 leds on each strip, or 360 leds - it will take 10.8ms to call FastLED.show(), in addition, there's a delay(100) in there after each time FastLED.show() is called so each dot now takes 110.8ms - but now there's 360 dots so now you're looking at nearly 40s 

and so on and so on and so on.

You can try taking out the delay(100) to speed things up a bit, but you're still going to run up against the basic math of this and the timings involved.
