### ISSUE TITLE
FastLed cause program stop functioning

### ISSUE THREAD

**Issue by yaronze** [FastLED/FastLED#792]
i am using Arduino nano & tested with Uno too, using FastLed library.
the project includes SD module and serial communication via USB.
when i put the line -FastLED.addLeds<NEOPIXEL,DATA_PIN>(leds, NUM_LEDS); starts very strange behaviors like - part of the program not running as suppose too, sometimes reset the nano with no reasonable cause.
when i make this code line as comment - all problems go away and everything work s fine.
what is the problem with the FastLeds? are there any conflict with other libraries or hardware?
thanks

**Comment by focalintent** [comment]
It's hard to say without seeing what the rest of your code is like.  It's possible you're running into issues with interrupts.  It's possible you're running out of memory.  It's possible that you have a memory corruption issue somewhere that's corrupting memory only used by FastLED, so when you comment out the addLeds line FastLED is effectively not doing anything, and therefor not hitting it.
