### ISSUE TITLE
Need to make Pixel LED Circle 

### ISSUE THREAD

**Issue by wijayapriya** [FastLED/FastLED#800]
I need to make like this https://www.youtube.com/watch?v=wc3HgP-Hoxw

Please help me,, How to edit this code like this.

**Comment by kriegsman** [comment]
Hi and thanks for trying out FastLED.  For general help questions like this one, please join us on the FastLED forum here on reddit https://www.reddit.com/r/FastLED 

We use github 'issues' only for bugs in the library itself.  All other general programming, project, and help discussions take place now on reddit https://www.reddit.com/r/FastLED
