### ISSUE TITLE
Documentation organisation is poor.

### ISSUE THREAD

**Issue by ah3243** [FastLED/FastLED#806]
I'm trying to look for a definition of certain functions or methods and there's no apparent easy way to understand what parameters are needed. Why should i have to read a whole tutorial to find one bit of information. Such a great project is let down by poor documentation organisation/usability. Please fix this..

**Comment by focalintent** [comment]
There's documentation here - http://fastled.io/docs/3.1/ - which is linked to/referenced from the project wiki - https://github.com/FastLED/FastLED/wiki/Frequently-Asked-Questions

I want to do an overhaul of the library documentation (but not until I finish the current overhaul of the library that I'm working on) - but time is not something that I have a whole lot of right now, so it's slow moving.

**Comment by senorblasto** [comment]
ah3243, who exactly are you asking to fix this?  If not you then who?
