### ISSUE TITLE
Adalight Ambibox connection fails after restarting computer

### ISSUE THREAD

**Issue by AmberElferink** [FastLED/FastLED#817]
Hi, I have an Arduino Mega with the Adalight code connected to Ambibox. 
OS: Windows 10

If I start my computer (from full shutdown, which includes my arduino), it can take a very long time for the Arduino to notice Ambibox sending data. From minutes to hours (more often hours though).
I have tried to narrow the problem down:

Scenario's that don't work
I start my computer
My Arduino does not perform the flash sequence, except for when I press the power button of the computer, before even the bios has started.
Starting ambibox after this: it says its connected in Ambibox, is capturing and backlight is on
The RX on the Arduino flickers. The leds show no output.
Sometimes it randomly does the flash sequence after a half hour or hours and it suddenly works. Most of the times, it doesn't.

Things I tried:
I make sure Ambibox is off on windows start, and start everything manually, no difference.
If I press the arduino's reset button (with ambibox closed), it does the flash sequence. 
However it gives the same result starting Ambibox after that: The RX flickers, but there is no output to the leds.

To manually fix that I can:
Turn off backlight in ambibox
pull out the arduino (it still says its connected even when plugged out)
I select another disconnected port.
I select the correct port, now it shows it is deconnected
I plug in the arduino
It does the setup with flashing colors
I check on backlight in Ambibox
The RX flickers as if receiving data
It correctly captures and shows the colors in the leds

Performing exactly these steps does fix it, but of course this is not desirable every time I start my pc.

To be clear:
Just switching the ports in Ambibox does not work, I really need to unplug.
Just unplugging doesn't work, I really need to switch the ports back and forth in Ambibox (or it will say connected when it's plugged out and not give led output after).
Leaving the backlight on does not work, with switching the port and replugging the usb, it does give disconnected and connected, but the leds stay out.

Does anyone also have this problem, or maybe a solution?

**Comment by focalintent** [comment]
This doesn’t really sound like a FastLED issue - to try to reach a wider range of users you could try asking on the FastLED community on reddit - http://FastLED.io/r - or in a community/repo dedicated go adalight/ambibox
