### ISSUE TITLE
Making CRGB::operator bool() explicit would be useful

### ISSUE THREAD

**Issue by ssilverman** [FastLED/FastLED#819]
It's easy to assign CRGB to an integral value for a number of reasons, however, if you aren't careful to use your own, for example, `uint32 toColor` function, the `bool()` operator is used.

My suggestion is to make `CRGB::operator bool()` `explicit`.

Ref: See mention of the Safe Bool idiom mentioned in the "Explicit Conversion Operators (C++11)" section at: https://stackoverflow.com/a/16615725.

I find myself doing this:

```c++
// Extends FastLED's CRGB to add a uint32_t conversion and make
// `operator bool()` explicit.
class MyCRGB : public CRGB {
 public:
  MyCRGB() : CRGB(){};
  explicit MyCRGB(const CRGB &rhs) : CRGB(rhs){};
  explicit MyCRGB(const CHSV &rhs) : CRGB(rhs) {}
  explicit MyCRGB(uint32_t c) : ::CRGB(c) {}
  ~MyCRGB() = default;

  MyCRGB &operator=(const CRGB &rhs) {
    CRGB::operator=(rhs);
    return *this;
  }

  MyCRGB &operator=(const CHSV &rhs) {
    CRGB::operator=(rhs);
    return *this;
  }

  explicit operator bool() const {
    return CRGB::operator bool();
  }

  // Converts a CRGB to a 32-bit colour having an alpha of 255.
  explicit operator uint32_t() const {
    return uint32_t{0xff000000} |
           (uint32_t{r} << 16) |
           (uint32_t{g} << 8) |
           uint32_t{b};
  }
};
```

**Comment by kriegsman** [comment]
Thanks for the suggestion; I think it's a great idea.
I want to think about how and in what ways this is going to change the (compile-time or run-time) behavior of existing code, but overall I really like this idea.

**Comment by ssilverman** [comment]
Yes, a large enough set of users means even testing things that "shouldn't" have an effect. :D

Having said that, I'm willing to bet adding `explicit` here will find usage errors in code that attempts to assign to any integral value, having an unintended consequence.

**Comment by ssilverman** [comment]
One other note is that implicit conversions will need to be explicitly cast or used as a Boolean expression. See here: https://github.com/ssilverman/QNEthernet/blob/master/README.md#operator-bool-and-explicit

If that caveat is fine, then let’s get this in.
