### ISSUE TITLE
ESP32 Clockless I2S Pin addition

### ISSUE THREAD

**Issue by computergeek1507** [FastLED/FastLED#828]
If there a way to add support for pin GPIO33-36, and 39 to Sam's Clockless I2C output for the ESP32.

**Comment by focalintent** [comment]
@samguyer is there?  My guess is no, given that 33-39 are on a separate GPIO pin than 0-31 and this works by doing all its work with the entire gpio register at a shot.

**Comment by hpwit** [comment]
The I2S driver will support pin 33 but pins 34->39 are either non usable or input only pins hence cannot be used either.

**Comment by samguyer** [comment]
Yes, pins 34-39 are input only (part of the ESP32 specification)
