### ISSUE TITLE
Conflict with ESP8266 solved

### ISSUE THREAD

**Issue by todocono** [FastLED/FastLED#832]
Using Arduino IDE 1.8.7 AND platforms/esp/8266/led_sysdefs_esp8266.h:15:17: error: conflicting declaration 'typedef uint8_t boolean'
 typedef uint8_t boolean;

**Comment by focalintent** [comment]
This was already fixed - see #790 - and FastLED 3.2.7 went out last month to make it available in the Arduino IDE.
