### ISSUE TITLE
Conflict with ESP8266 solved

### ISSUE THREAD

**Issue by todocono** [FastLED/FastLED#833]
Using Arduino IDE version 1.8.7 and ESP8266 version 2.5.2, it doesn't  compile given to the error:
.... "platforms/esp/8266/led_sysdefs_esp8266.h:15:17: error: conflicting declaration 'typedef uint8_t boolean'
 typedef uint8_t boolean;
.

By commenting the line 15 of platforms/esp/8266/led_sysdefs_esp8266.h, it stops having the error and it can work correctly. The line is " typedef uint8_t boolean; "

**Comment by focalintent** [comment]
This was already fixed - see #790 - and FastLED 3.2.7 went out last month to make it available in the Arduino IDE.
