### ISSUE TITLE
CRGB::DeepSkyBlue (HTML Value) VS. CRGB( R, G, B)

### ISSUE THREAD

**Issue by landtree** [FastLED/FastLED#844]
Code:

https://pastebin.com/cfZkB5aw

I have a simple project that has a chase sequence("sec1" in the code).

The whole idea is to have sensor 1 turn on the sequence then have sensor 2 add in more color every time it trips.

The chase runs fine when I use CRGB::DeepSkyBlue or any other HTML color but if I use CRGB( color1R, color1G, color1B) the LEDS update exactly one time then stalls and never updates after that set. So, what am I missing here? I feel like its a dumb mistake in my chase that I cannot just see.

I am hoping that when sensor 2 trips it updates color1R, color1G, color1B then slips back into the sequence and the chase continues.

Is this a way the lib handles the two different ways to set color?

**Comment by marmilicious** [comment]
This was answered on the Reddit group.
(Problem was trying to write data to pixels that don't exist.)
This can be closed.
