### ISSUE TITLE
PR Ready -- Enable TravisCI builds

### ISSUE THREAD

**Issue by henrygab** [FastLED/FastLED#848]
See PR "Enable TravisCI builds #846".

Enabling TravisCI builds will help prevent build breaks (much like my own earlier failure).

The PR builds all platforms except for Teensy boards, and ensures all supported examples build for those platforms.

**Comment by henrygab** [comment]
Is there any interest in this?

**Comment by focalintent** [comment]
There is but it is a large enough set of changes that I don’t want to pull it in until I can spend some time with it here.

**Comment by henrygab** [comment]
OK, thanks for the update.  Let me know if any questions.

**Comment by henrygab** [comment]
With the addition of GitHub actions, and the continued maintenance requirements, I am going to close this for now.

**Comment by henrygab** [comment]
Re-opening this, as it seems that a functioning CI check would provide immediate value, both for PRs in the official FastLED repository, as well as in any forks that enable TravisCI.

NOTE: Accepting this PR (or pulling once it is accepting) will *NOT* enable TravisCI builds by itself.
