### ISSUE TITLE
Fade in and stay for a second then all off. Help please.

### ISSUE THREAD

**Issue by Robiv8** [FastLED/FastLED#859]
OK
I go to
Reddit FastLED discussion group here: http://fastled.io/r

**Comment by marmilicious** [comment]
@Robiv8 The github bug tracker here is mostly just for bugs in the library itself.  For general discussions, help, and how-to, please check out the Reddit FastLED discussion group here: http://fastled.io/r
Also, when sharing code there, please use pastebin.com or gist.github.com and share the link to your code.
