### ISSUE TITLE
Does FASTLED work with Adafruit Grand Central

### ISSUE THREAD

**Issue by winyguy** [FastLED/FastLED#869]
Has anyone had success using FastLED with the Adafruit Grand Central (Microchip ATSAMD51 Cortex M4)? At first glance there appears to be pin assignment issues and problems enabling/disabling interrupts. I haven't had time to do any serious debugging. Any insight would be appreciated!

Thanks.

**Comment by focalintent** [comment]
I should have one next week to go play with.

**Comment by winyguy** [comment]
Great, thank you!

**Comment by winyguy** [comment]
Does anyone know if an update has been posted to support the Grand Central?

Thanks.

**Comment by winyguy** [comment]
Is there an update available for Grand Central support?
