### ISSUE TITLE
Division by zero in countFPS()

### ISSUE THREAD

**Issue by limpens** [FastLED/FastLED#881]
This issue maybe caused by calling FastLED.show() too frequently, but running FastLED on an ESP8266, with the CPU at 160Mhz, I occasionally have a 'millis() == 8191' and lastframe also 8191.

With the logic at https://github.com/FastLED/FastLED/blob/master/FastLED.cpp#L212 this will end up in a 'now' becoming 0 and an exception calculating the m_nFPS.

Sincerely, Eric.

**Comment by andjoeg** [comment]
Trying out changing from millis() to micros() to give higher resolution
