### ISSUE TITLE
Unnecessary macro 

### ISSUE THREAD

**Issue by tttapa** [FastLED/FastLED#892]

**Comment by henrygab** [comment]
@tttapa -- can you fill in some information?  what macro?  what file?  why is it unnecessary?

**Comment by tttapa** [comment]
That's strange, I accidentally hit enter when entering the title of https://github.com/FastLED/FastLED/issues/893 and it created an empty issue. I then edited it to fix it, I didn't remember there being multiple issues. My apologies.

I can only close this issue, I can't delete it, but I think that contributers should be able to just delete it, which is probably the best thing to do.
