### ISSUE TITLE
Serial.print color from palette

### ISSUE THREAD

**Issue by sigmarpriest** [FastLED/FastLED#897]
Hi, 
I'd like to send color from palette via UART to another device.
I tried:
`for(uint8_t i=0; i<16; i++){`
`String bufColor= String(targetPalette[i]);`
`Serial.println(bufColor);`
`}`
and I got only '1' for every color.
Is any function to read colors from palette?

**Comment by marmilicious** [comment]
What about something like this:

```
for (uint8_t i=0; i<16; i++) {
  CRGB bufColor = targetPalette[i];
  Serial.print(bufColor[0]); Serial.print("\t");
  Serial.print(bufColor[1]); Serial.print("\t");
  Serial.println(bufColor[2]);
}
```

**Comment by sigmarpriest** [comment]
Thank You so much, I was sure, that colors are stored as one HEX value.
