### ISSUE TITLE
How to find out the number of WS2812B LEDs within a strip?

### ISSUE THREAD

**Issue by yell0w4x** [FastLED/FastLED#898]
Sorry for asking this here, but I'm searching web for a few hours with no success. 
Is it possible to detect the number of LEDs in runtime? I also inspected the FastLED API and found nothing about this. May be I missed something...

I would like to connect strips of LEDs with arbitrary length to the device and have them work.

Thanx in advance.

**Comment by kriegsman** [comment]
There’s no way for the Arduino to “read” any data at all from the LED strips: not LED type, not color order, and not the number of LEDs; the communication is entirely one way from the Arduino to the LEDs, not the other way. 
For general help questions like this, please join the FastLED discussion group on reddit, https://www.reddit.com/r/FastLED and thanks for using FastLED.
