### ISSUE TITLE
Teensy 4 Bits are inverted

### ISSUE THREAD

**Issue by seymar** [FastLED/FastLED#899]
I am running the blink example on both Teensy 4 and Teensy LC with the same LED strip.
The Teensy LC works correctly. The Teensy 4 however inverts the bits that are sent out.
It blinks Cyan & White instead of Red & Black.

```C++
#include <FastLED.h>

#define NUM_LEDS 1
#define DATA_PIN 17

CRGB leds[NUM_LEDS];

void setup() {
  FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS);
}

void loop() {
  leds[0] = CRGB(0b11110000, 0, 0);
  FastLED.show();
  delay(200);
  leds[0] = CRGB::Black;
  FastLED.show();
  delay(800);
}
```

Arduino version 1.8.8
FastLED version 3.3.2

**Comment by marmilicious** [comment]
@seymar  Have a look at this post on the Reddit group regarding using the Teensy 4.

https://www.reddit.com/r/FastLED/comments/d9z2os/teensy_40_and_fastled_along_with_ws2811_ws2812_ws/

**Comment by seymar** [comment]
Great! Thank you.
