### ISSUE TITLE
Why does FastLED.delay contain a "show" function call?

### ISSUE THREAD

**Issue by dpinvidic** [FastLED/FastLED#901]
While writing some simple code, I found that the LED's were constantly updating even after I commented out the FastLED.show call.  It turns out that calling the FastLED.delay function also does a show.
Sorry if this is a dumb question.....but can someone explain?

Regards,
Dan

void CFastLED::delay(unsigned long ms) {
	unsigned long start = millis();
        do {
#ifndef FASTLED_ACCURATE_CLOCK
		// make sure to allow at least one ms to pass to ensure the clock moves
		// forward
		::delay(1);
#endif
		show();
		yield();
	}
	while((millis()-start) < ms);
}

**Comment by marmilicious** [comment]
Check out this page:
https://github.com/FastLED/FastLED/wiki/FastLED-Temporal-Dithering

**Comment by dpinvidic** [comment]
Thanks...That was a big help.
Cheers....

Dan

**Comment by dpinvidic** [comment]
That Article explains a lot....
