### ISSUE TITLE
Keil :: cannot open source input file "avr/io.h": No such file or directory

### ISSUE THREAD

**Issue by borbier** [FastLED/FastLED#918]
I've included FastLED library to my project on Keil. (I've planned to use STM32F767ZI for controlling WS821B) The code in main is fine and didn't shown up errors but when I'm compiled the error is occured as image below.
![bugs](https://user-images.githubusercontent.com/14361087/68773899-e8c2e280-065e-11ea-98e8-0fff92634396.png)

Are ther any solution or work-around to get it working?

**Comment by AndKe** [comment]
are you using STM32-core ?

**Comment by borbier** [comment]
> are you using STM32-core ?

Yes, but I just tried other library and set up configuration for DMA and PWM and made it worked.
[Here is my repository](https://github.com/borbier/stm32f7xxxx-ws2812b)

I appreciated your reply anyway.

**Comment by AndKe** [comment]
Great, I am using STM32F103C8 , do you think it'll work?
