### ISSUE TITLE
Tracking NRF52 pending PRs

### ISSUE THREAD

**Issue by henrygab** [FastLED/FastLED#948]
Until the depot resumes taking PRs, I'm integrating those needed for the nrf52 series of chips into [my nrf52 fork](https://github.com/henrygab/FastLED/tree/nrf52_fixes), as a way to help simplify getting people up and running during this transitional time.

Currently integrated PRs:
* [x] #946 Missing underscores in `_FL_DEFPIN` causing compilation fail (regression from #866) (Issue #938)
* [x] #900 Fix compilation fail for NRF52832 (and other single-port NRF52 chips) (Issue #919)

Feel free to reference additional NRF52 related PRs within this issue, that you'd like to see integrated in the interim.

**Comment by lmh91** [comment]
I think #917 should be added here?

I also have a Arduino Nano 33 BLE (nRF52840) and can't compile FastLED with the same error as in this issue.

**Comment by henrygab** [comment]
#917 is a different issue … that's for support of a brand new board.  I'll follow-up on #917.
