### ISSUE TITLE
Arduino Serial Read , Integer primary expression error

### ISSUE THREAD

**Issue by aesopp99319** [FastLED/FastLED#949]
Hello i am new to FastLed and I am trying to control a WS2812 with ardunio firefly & grasshopper. I want to control the LED to light up according to the integer value from serial read from firefly.

However the error message display primary expression before int.

Please advice how to fix this issue, Thank you!

#include <FastLED.h>
#include "FastLED.h"
#define NUM_LEDS 30
#define DATA_PIN 9
#define BRIGHTNESS  1000
#define NUM_LEDS 30
#define DATA_PIN 9
#define CLOCK_PIN 13

CRGB leds[NUM_LEDS];
      

void loop() { 
  
    while (Serial.available() == 0);
    int val = Serial.read()-'0';
    
  for(int led > 0; led < 30; ) { 
  // Turn the LED on, then pause
  leds[int] = CRGB::Blue;
 
  FastLED.show();
  delay(500);
  // Now turn the LED off, then pause
  leds[0] = CRGB::Black;
  FastLED.show();
  delay(500);
  }
}

**Comment by marmilicious** [comment]
I think your current problem is it does not understand "int" here:
leds[int] = CRGB::Blue;
I am guessing you wanted to put the this:
leds[led] = CRGB::Blue;

There are other problems with your code, such as you are missing the entire setup section.  And FastLED's master BRIGHTNESS is a range from 0-255, so if you set BRIGHTNESS 1000 that will become value 232, actually less then full brightness.

We use github 'issues' here mostly just for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: http://fastled.io/r  Note the rules about posting code there-- please do not post programs in reddit comments.

**Comment by kriegsman** [comment]
I'm going to close this issues; if there's further discussion let's move it to reddit as @marmilicious suggested. Good luck!
