### ISSUE TITLE
Remapping Array while read RAW data from SD Card 

### ISSUE THREAD

**Issue by Kamal-Sonani** [FastLED/FastLED#953]
i connected 200 led and record .RAW data in Jinx 
```
while (fxdata.available())
  {
    fxdata.readBytes((char*)leds, NUM_LEDS * 3);
    FastLED.show();
  }
this while loop is sort data as address {1,2,3,4,5,6,7,8,9,10,11,12,13,...........200};
```

How to remap array in
```
CRGB tmp[] = {1,3,5,7,9,11,13,15,.............,198,199,2,4,6,8,...........,200};
```

**memcpy** OR **memset** is key for static Array remap ,but i don't know how to do.....

**Comment by marmilicious** [comment]
We use github 'issues' here mostly just for bugs or improvements in the library itself.  For all general discussions, help, and how-to, please use the FastLED Reddit group here: http://fastled.io/r

You can try using memmove8
`memmove8( &leds, &tmp, (NUM_LEDS)*sizeof(CRGB) );
`
