### ISSUE TITLE
Would this work with an intel Galileo Gen2?

### ISSUE THREAD

**Issue by TheNumenorean** [FastLED/FastLED#98]
I plan to run a lot of leds (~1200), and thought the additional processing power could be useful.

**Comment by Bre77** [comment]
Intel Galileo Gen 2 is meant to be both hardware and software compatible with Arduino. See https://www.sparkfun.com/products/13096

**Comment by focalintent** [comment]
A lot of things claim software comparability but that is only for things that use the standard arduino libraries - FastLED talks directly to the underlying hardware, so if it is not an atmega328 or one of the supported arm platforms (Freescale k20 or atmel sam3x8) it will be a more significant port.

**Comment by Bre77** [comment]
Ok good to know.
