### ISSUE TITLE
Red and green inversed

### ISSUE THREAD

**Issue by MarcBresson** [FastLED/FastLED#989]
Hello !
For both HSV and RGB systems, red and green color are switched !
i am on the last version of the library and have no idea where it could come from.

**Comment by marmilicious** [comment]
Have you run the RGBCalibrate example that comes with the library to check the color for your strip?
https://github.com/FastLED/FastLED/blob/master/examples/RGBCalibrate/RGBCalibrate.ino

If this doesn't get you sorted out please post a question (with details of your setup) on the FastLED Reddit group.

**Comment by MarcBresson** [comment]
I am closing that, I will do further testing because in my memory, the problem was still happening. If I ever open a new issue, I ll provide more details as to how to reproduce the problem.

Thank you for taking the project back, and good luck.
